### ISSUE TITLE
$color1: null is not a color.

### ISSUE THREAD

**Issue by Effectiva** [bootscore/bootscore#104]
Hi,

With the latest release I get the following issue with a fresh install (with or without a child theme)

$color1: null is not a color.: wp-content/themes/bootscore-main/css/scss/bootstrap/mixins/_buttons.scss on line 41, at column 7 Call Stack: #0 mixin button-variant wp-content/themes/bootscore-main/css/scss/bootstrap/_functions.scss on line 170 #1 import wp-content/themes/bootscore-main/css/scss/bootstrap/_buttons.scss wp-content/themes/bootscore-main/css/scss/bootstrap/bootstrap.scss on line 26 #2 import wp-content/themes/bootscore-main/css/scss/bootstrap/bootstrap.scss (unknown file) on line 2

**Comment by crftwrk** [comment]
Please download files for theme and child here again and check if the bug still remains

- https://github.com/bootscore/bootscore/archive/refs/heads/main.zip
- https://github.com/bootscore/bootscore-child/archive/refs/heads/main.zip

**Comment by Effectiva** [comment]
Thank you for the quick reply, this fixed it!

**Comment by crftwrk** [comment]
👍You‘re welcome
