### ISSUE TITLE
Cart not working

### ISSUE THREAD

**Issue by jonwebprocoder** [bootscore/bootscore#106]
Hi

I am using the woocommerce theme to build a site and the add to cart isn't working - it opens the cart to the right of the page but nothing displays?

https://jonathanh138.sg-host.com/product/silima-cleaning-lotion/

Jon

**Comment by crftwrk** [comment]
Hi Jon,

There is a JavaScript error on your page. Seems this is coming from the Cleantalk Spam Protect plugin. To investigate where the error is exactly coming from, follow these steps:

- Deactivate cleantalk-spam-protect plugin.
- Deactivate all other plugins.
- Download and save your customized child-theme.
- Install and activate default bootcommerce-child for bootScore 5.1.3.0 (your version) https://github.com/bootscore/bootcommerce-child/releases/download/5.1.0.2/bootcommerce-child-main.zip

Does this help?

**Comment by jonwebprocoder** [comment]
Hi

Thanks for getting back to me so quickly - absolutely love this theme so really want to get it working.

i have tried the above and still have the same issue - i notice when i click add to basket it is doing an ajax call to add to basket and then another to get the basket - this appears to be the full basket page as opposed to just the HTML for the side bar? Thought this might help

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/31352149/155706161-4410b2d4-6528-48c0-b85d-935874f8a06d.png">

Jon

**Comment by crftwrk** [comment]
Did you enabled the Redirect to the cart page after successful addition? If so, go to WooCommerce > Settings > Products tab and disable it. Enable AJAX add to cart buttons on archives must be enabled.


<img width="669" alt="Bildschirmfoto 2022-02-25 um 12 45 32" src="https://user-images.githubusercontent.com/51531217/155710169-d49c4f8b-5973-4c60-8879-842e777a6a08.png">

**Comment by jonwebprocoder** [comment]
That's it!!! Thank you ever so much - sorry i didn't spot this

Jon

**Comment by crftwrk** [comment]
You`re welcome 👍
