### ISSUE TITLE
Remove default template

### ISSUE THREAD

**Issue by bene82** [bootscore/bootscore#109]
Thanks for your great work!

I'm asking if is possible to remove **default page and post templates**, this because I'm adding mine and I need just essential ones.

Thanks in advance

**Comment by crftwrk** [comment]
Hi,

simply copy your templates to your child root folder and name them `page.php` and `single.php`. Now your templates overrides default templates.

Solved?

**Comment by crftwrk** [comment]
You cannot remove theme's templates, but you can simply override them by store a copy in your child. You can add new templates as well. When you rename the templates, WordPress recognize them as a new additional template.
