### ISSUE TITLE
bootstrap_5_wp_nav_menu_walker

### ISSUE THREAD

**Issue by mdabbagh-ir** [bootscore/bootscore#11]
do not work sub menu in depth 3.
what's the solution?

**Comment by craftwerkberlin** [comment]
Bootstrap does not support multi-level dropdowns https://github.com/twbs/bootstrap/issues/27659

But you can use snippet to extend menues https://bootstrap-menu.com

However, nav-walker does not support 3rd sub-level too. If snippets above do not work, you must edit it. Nav-walker is a pluggable function in functions.php, you can edit in child-theme.

Does that help?

**Comment by mdabbagh-ir** [comment]
Thanks for the prompt response
How do I change the nav-walker so that the output of the level 3 menu is as follows?

`<ul class="navbar-nav mb-lg-0 fs-6 flex-grow-1">
    <li class="nav-item ms-3">
        <a class="nav-link " href="#">home</a>
    </li>
    <li class="nav-item dropdown ms-3">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">categorys</a>
        <ul class="dropdown-menu dropdown-menu-right menu1" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item dropdown-toggle" href="#">frontend</a>
            <ul class="dropdown-menu menu2 dropdown-menu-right">
                <li><a class="dropdown-item ps-4" href="#">html</a></li>
                <li><a class="dropdown-item ps-4" href="#">css</a></li>
            </ul>
            <a class="dropdown-item dropdown-toggle" href="#">backend</a>
            <ul class="dropdown-menu menu2 dropdown-menu-right">
                <li><a class="dropdown-item ps-4" href="#">php</a></li>
                <li><a class="dropdown-item ps-4" href="#">nodejs</a></li>
            </ul>
        </ul>
    </li>
</ul>`

**Comment by craftwerkberlin** [comment]
Try this snippets first https://bootstrap-menu.com/detail-multilevel.html before touching nav-walker

**Comment by mdabbagh-ir** [comment]
The project is already written with the above HTML codes.

**Comment by craftwerkberlin** [comment]
So, done?

**Comment by mdabbagh-ir** [comment]
No, unfortunately it is not solved.
I'm looking for a way to have an output similar to the above code by modifying the bootstrap_5_wp_nav_menu_walker.php file.

**Comment by craftwerkberlin** [comment]
Yes, click the link in my previous comment. There you will find the snippets you need to make a Bootstrap multi-level menu.

**Comment by mdabbagh-ir** [comment]
The problem with the link https://bootstrap-menu.com/detail-multilevel.html  is that the submenus are displayed with a hover, but my code snippet is displayed by clicking the submenus.

**Comment by craftwerkberlin** [comment]
Understand. I think this is not possible with Bootstrap 5. You can try plugin like this https://wordpress.org/plugins/multilevel-navigation-menu/

**Comment by craftwerkberlin** [comment]
Another one https://codepen.io/typo3-freelancer/pen/poEvyGj

**Comment by cdsaenz** [comment]
I wrote some tweaks for the walker to accept a level beyond two, that exceed the Bootstrap logic (but are necessary for me as WP Menus are multilevel) so I put them in a gist. See this comment in the original walker for the code. I wouldn't go farther than one side menu though, it would be too much :)  https://github.com/AlexWebLab/bootstrap-5-wordpress-navbar-walker/issues/19#issuecomment-1120456030
