### ISSUE TITLE
forums integrated

### ISSUE THREAD

**Issue by ersingo** [bootscore/bootscore#110]
hello is it possible that we can do something for bbpress or any other forum? do you think of such a thing? can you do a job in a way that suits your theme?

**Comment by crftwrk** [comment]
Hi,

That's a nice idea, but it would go beyond the scope of the project. Integrating another third-party plugin will mean to edit and maintain dozens of templates to support this seriously. The integration of WooCommerce is already a big challenge and unfortunately we don't have the capacity to support more plugins.

So you should do this yourself in your child-theme by adapting the CSS or editing templates if necessary. However, we can assist with this if you need.
