### ISSUE TITLE
Issue with related products that are out of place if product category is selected

### ISSUE THREAD

**Issue by akvrmvlakis** [bootscore/bootscore#118]
Hi there! First of all congrats for the work you've done on this theme it's super clean and beautiful. I've got a small issue that only happens at appx 768px and above there is no issue on mobile view but the absurd thing is that it happens with a specific product only and doesn't happen with other products. The issue is that the related products get entangled with the product description totally out of place instead of being down at the bottom. As I mentioned It only happens with a specific product and the only difference between this product and other products is that the product title in its own language is quite large. I have tried everything I have disabled all plugins etc and the issue persists. Even if I don't select a category and leave it uncategorized the issue persists. I am attaching screenshots I would appreciate any help if at all possible. Again congrats on the theme for some reason it reminds me of Google's layouts in some way it's cleanliness and simplicity is pure beauty. 

![cat1](https://user-images.githubusercontent.com/25525915/159486946-156f796a-14f6-4901-98c4-de70672757ba.PNG)

![vv1](https://user-images.githubusercontent.com/25525915/159486954-f4d61f77-e02a-4dea-92bc-4515313a6965.PNG)

![uncategorized1](https://user-images.githubusercontent.com/25525915/159490810-60731466-144d-44dd-8f5e-b456f8194087.PNG)

**Comment by crftwrk** [comment]
Hi,

thank you for reporting. Please share a link to your product, so we can investigate further.

Thank you

**Comment by crftwrk** [comment]
Thanks, we‘ll check this tomorrow. BTW just add something to the product description should solve that ;-)

**Comment by akvrmvlakis** [comment]
Hey thanks so much I added something to the description and it works! I appreciate it alot :)

**Comment by crftwrk** [comment]
Cool! Process is very simple. Just fork the theme, add greek language using https://wordpress.org/plugins/loco-translate/ plugin. Then create a pull request. This will take not more than 20 minutes. If you need help, I'm here.

We're ready to ship version 5.2.0.0 in the next couple of days. If you're ready too, you will make a lot of users from your country happy.

**Comment by akvrmvlakis** [comment]
Hello Bastian sorry to bother again, I got it no worries I found a tutorial on loco translate so I will basically do this locally and then create a pull request on github as instructed.
________________________________

**Comment by crftwrk** [comment]
Take your time

**Comment by crftwrk** [comment]
Hello Alexandros,

looks good, 100% translated :-) 

I did a pull request to your branch to fetch the latest commits. Please merge this first and then create a PR back to main repo. We can delete backup files later.

Just in case something went wrong, I attached the greek files here.

Thank you 🙏

[el.mo.txt](https://github.com/bootscore/bootscore/files/8815789/el.mo.txt)
[el.po.txt](https://github.com/bootscore/bootscore/files/8815790/el.po.txt)

**Comment by akvrmvlakis** [comment]
Thank you very much Bastian I merged as instructed and created a pull request back to main. 🙂

________________________________

**Comment by akvrmvlakis** [comment]
Thank you very much Bastian! 🙂 Will send my email address to store(at)bootscore.me as instructed.

________________________________

**Comment by akvrmvlakis** [comment]
Hello Bastian! I have finally finished my bootscore client project: http://akvrmvlakis.a2hosted.com/ and I am ready to proceed with adding the Greek translation. I have just forked the theme on GitHub. Could you please explain the next steps that need to be taken now whenever you have the time? Thanks.
________________________________

**Comment by crftwrk** [comment]
You did already here https://github.com/bootscore/bootscore/pull/161. So, nothing more to do?

**Comment by akvrmvlakis** [comment]
Hello Basti! Yes correct as far as the translation all the terms that needed translation were translated and the fields that were not and were left in the English default was because this is how developers and people in Greece are referring to them and translating them would only create confusion and look bad.
________________________________

**Comment by crftwrk** [comment]
So, you want to improve translation, right? It‘s very simple. Just update your fork to the latest. Then do translation on a installation. When done, grab .mo and .po file via ftp and add them to your fork. GitHub will ask you then if you want to contribute with a pull request. Simply press yes, that‘s it. By this way you can improve translation from time to time.

**Comment by akvrmvlakis** [comment]
Excellent thank you very much for the instructions I will revise it.
________________________________
