### ISSUE TITLE
New bootscore install fails with PHP error Call to undefined method ScssPhp\ScssPhp\Compiler::setOutputStyle()

### ISSUE THREAD

**Issue by csstup** [bootscore/bootscore#119]
Installed the main theme and the child theme.   

WordPress 5.8.3 running [bootScore Child] theme.

Pages don't render.   I get the following in my logs:

```
[22-Mar-2022 07:36:34 UTC] PHP Warning:  filemtime(): stat failed for /home/louijcst/public_html/wp-581/wp-content/themes/bootscore-child-main/css/lib/bootstrap.min.css in /home/louijcst/public_html/wp-581/wp-content/themes/bootscore-child-main/functions.php on line 11
[22-Mar-2022 07:36:34 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method ScssPhp\ScssPhp\Compiler::setOutputStyle() in /home/louijcst/public_html/wp-581/wp-content/themes/bootscore-main/inc/scss-compiler.php:19
Stack trace:
#0 /home/louijcst/public_html/wp-581/wp-content/themes/bootscore-main/functions.php(263): bootscore_compile_scss()
#1 /home/louijcst/public_html/wp-581/wp-includes/class-wp-hook.php(303): bootscore_scripts('')
#2 /home/louijcst/public_html/wp-581/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#3 /home/louijcst/public_html/wp-581/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#4 /home/louijcst/public_html/wp-581/wp-includes/script-loader.php(2083): do_action('wp_enqueue_scri...')
#5 /home/louijcst/public_html/wp-581/wp-includes/class-wp-hook.php(303): wp_enqueue_scripts('')
#6 /home/louijcst/public_html/wp-581/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#7 /home/louijcst/public_html/wp-581/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /home/louijcst/ in /home/louijcst/public_html/wp-581/wp-content/themes/bootscore-main/inc/scss-compiler.php on line 19
```

**Comment by justinkruit** [comment]
I think you've named the theme folder incorrectly, looking at this error. I see `bootscore-child-main`, so I guess you have the main theme as `bootscore-main`. Please try removing `-main` from both names, and try again.

**Comment by justinkruit** [comment]
Nevermind, I got that wrong. Ignore that.

**Comment by csstup** [comment]
I installed both themes straight from their ZIP files.  Uploaded the main theme zip, installed.  Uploaded the child theme zip, installed.

**Comment by crftwrk** [comment]
Hi @csstup,

I suggest doing this to find out what's wrong:

- Please share a link to your site. If you are on localhost, transfer your project to a public server
- Download latest developed bootScore theme https://github.com/bootscore/bootscore/archive/refs/heads/main.zip and activate it. Check if main-theme works.
- Download latest developed child-theme https://github.com/bootscore/bootscore-child/archive/refs/heads/main.zip and activate it. Check if child-theme works.

**Comment by csstup** [comment]
Downloaded latest bootScore main theme and installed.  Same issue:

[24-Mar-2022 04:07:00 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method ScssPhp\ScssPhp\Compiler::setOutputStyle() in /home/louijcst/public_html/wp-581/wp-content/themes/bootscore-main/inc/scss-compiler.php:20
Stack trace:
#0 /home/louijcst/public_html/wp-581/wp-content/themes/bootscore-main/functions.php(263): bootscore_compile_scss()
#1 /home/louijcst/public_html/wp-581/wp-includes/class-wp-hook.php(303): bootscore_scripts('')
#2 /home/louijcst/public_html/wp-581/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#3 /home/louijcst/public_html/wp-581/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#4 /home/louijcst/public_html/wp-581/wp-includes/script-loader.php(2083): do_action('wp_enqueue_scri...')
#5 /home/louijcst/public_html/wp-581/wp-includes/class-wp-hook.php(303): wp_enqueue_scripts('')
#6 /home/louijcst/public_html/wp-581/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#7 /home/louijcst/public_html/wp-581/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /home/louijcst/ in /home/louijcst/public_html/wp-581/wp-content/themes/bootscore-main/inc/scss-compiler.php on line 20

Running PHP Version 7.4.28.   Is there a specific PHP module needed for Scss compilation?

**Comment by crftwrk** [comment]
> Running PHP Version 7.4.28. Is there a specific PHP module needed for Scss compilation?

Usually not. This should be ok. But as mentioned in my previous comment I think you are on local computer. Again, please transfer your project to a public server and share a link. A different server should solve this by itself.

**Comment by crftwrk** [comment]
> https://louisvillearcade.com/wp-581/

Is this a copy of your project? If you want you can create us an admin and ftp account and send it to `store(at)bootscore.me`. So, we can have a look to it.

Just one more question: Are you sure it is the bootScore theme and have you tried a default WP theme like Twent Twenty-One?

**Comment by csstup** [comment]
This is our development wordpress site.    We're evaluating Wordpress to use for our next generation website, but we had already modeled our existing site using Divi.   Works fine.   

I switched to using an empty page with the bootScore theme activated and PHP still exits with the errors I pasted above.   Other themes render fine.

Googling similar issues, it looks like it may be a plugin that is also using SccsPhp....
https://www.joomshaper.com/forum/question/6442

I'll see if I can find which that might be.    I have several plugins that were only installed for testing, etc.   I would think a theme's PHP libraries would be used before any plugins, but that must not be the case.

**Comment by csstup** [comment]
Found the culprit.   

![image](https://user-images.githubusercontent.com/8303565/159974363-fe26c276-d285-4ea4-88cc-63f06982134b.png)

**Comment by csstup** [comment]
The Responsive Menu plugin is using V1.1.0 of SccsPhp.   Quite old.   I'll check with the plugin maintainer to see if they would consider upgrading.

Are there ways to silo the libraries so they both can co-exist?    I know its not efficient to load both but at least it may be able to function and not just crash the page.

**Comment by crftwrk** [comment]
👍 solved

> Are there ways to silo the libraries so they both can co-exist?

Unfortunately not. Then you have PHP functions twice and this never will work. You can disable scssphp in theme's functions.php, but this makes no sense.

However, you don't need a responsive menu plugin because Bootstrap's navbar is a responsive menu.

**Comment by csstup** [comment]
Fair enough, thanks for the details and work thru on this.     And I appreciate a bunch of the plugins we're "testing" are not likely needed with bootstrap as core.  

This was all to evaluate what it would mean to move to WP and what environment we should use (one of the builders vs completely custom vs what plugins might work for us).   I'm a fan of handcrafted (or at least understanding what does what and where) and we used bootstrap3 on our existing site so evaluating bootscore and how it might work was a natural progression.
