### ISSUE TITLE
Not displaying SALE 

### ISSUE THREAD

**Issue by KozRipefruit** [bootscore/bootscore#122]
Fabulous, super fast theme with one minor bug.. it shows % instead of Sale when the item is on sale.

Example:
https://www.fmhc.com.au/shop

Code = 
<span class="badge bg-danger sale">%</span>
Should be
<span class="onsale">Sale!</span>

**Comment by crftwrk** [comment]
Thank you! You can simply override sale templates in your child.

- `woocommerce/loop/sale-flash.php`
- `woocommerce/single-product/sale-flash.php` 

Copy both files from main-theme to your child keeping the same folder structure `woocommerce/..` and change `%` to `Sale!`

 
Check here how to override template files in child https://bootscore.me/documentation/using-the-child-themes/
