### ISSUE TITLE
is it possible to insert infinite scroll and not pagination?

### ISSUE THREAD

**Issue by ant31zac** [bootscore/bootscore#124]
Hi,
I wanted to ask if it was possible to insert the infinite scroll instead of the pagination?
Thanks

**Comment by crftwrk** [comment]
Hi,

please do all issues related to child-themes in main-theme repo.

Pagination is a pluggable function:

```php
function wpsites_query($query) {
  if ($query->is_archive() && $query->is_main_query() && !is_admin()) {
    $query->set('posts_per_page', -1);
  }
}
add_action('pre_get_posts', 'wpsites_query');

```

Add this to your child `functions.php`. You can set amount of products you want to show per pagination in line `3`. `-1` is infinite.

Check this issue https://github.com/bootscore/bootscore/issues/38 as well.

Solved?

**Comment by ant31zac** [comment]
Yes Solved. Thanks

**Comment by ant31zac** [comment]
@crftwrk not work in this page https://antoniozaccaro.com/negozio.
in other page work https://antoniozaccaro.com/cat/collezioni/.

**Comment by crftwrk** [comment]
Which bootScore version do you use in not working page?

**Comment by ant31zac** [comment]
5.1.3.1

**Comment by crftwrk** [comment]
Please remove function to check

**Comment by ant31zac** [comment]
removed in the page that not work

**Comment by crftwrk** [comment]
You can create a ftp and admin account and send it to store(at)bootscore.me. So we can have a look.

**Comment by ant31zac** [comment]
is it possible that every new page( of the query ) will be added when the scroll arrive at the end of loaded page?

**Comment by ant31zac** [comment]
> is it possible that every new page( of the query ) will be added when the scroll arrive at the end of loaded page?

Basically I load the first 24 elements of the page, scroll to the last elements and when i reach the end the next 24 elements will be added

**Comment by justinkruit** [comment]
Building an infinite scroll is a bit difficult. If you want the easy way, I recommend looking at a plugin like this: https://wordpress.org/plugins/ajax-load-more/

If you want to build it yourself, we could still help with that, but it does require more work.

**Comment by ant31zac** [comment]
okok,
thanks for your explanations
