### ISSUE TITLE
Accordion taking too much space, how to fix?

### ISSUE THREAD

**Issue by kangarooo** [bootscore/bootscore#126]
Accordion taking too much space, how to fix?
![image](https://user-images.githubusercontent.com/73187/160674281-c73aa663-63f4-477a-97df-f817bddfa480.png)

**Comment by justinkruit** [comment]
I expect you have some padding/margin errors. Could you share a link to a development environment so we could take a look at what's going wrong? The exact issue can't be determined with only a screenshot

**Comment by kangarooo** [comment]
http://test.kangarooo.id.lv/v5/

**Comment by crftwrk** [comment]
There are a lot of `<br>` tags inside your accordion. Are you using the classic editor? Please switch to Gutenberg and use HTML Block.

You can try to stop WordPress adding automatic `<p>` and `<br>` tags using a filter in `functions.php`:  https://wpfluent.com/removing-unwanted-and-tags-from-wordpress/

```php
function remove_additional_p($content){
$content = forec_balance_tags($content);
return preg_replace('#<p>\s*+(<br\s*/*>)?|s*</p>#i','',$content);
}
      
add_filter('the_content','remove_additional_p',20,1);

```

**Comment by crftwrk** [comment]
See this is already fixed. So we can close this issue now.
