### ISSUE TITLE
Problem with plugin WC Fields Factory

### ISSUE THREAD

**Issue by nipnet** [bootscore/bootscore#127]
I am using the WC Fields Factory plugin. I have added a few fields to my product that affect price. I noticed that "add to cart" using ajax is causing errors.

On product page and I choose options from WC Fields Factory and then click "add to cart". The product is added to the cart, but without any options selected. When I choose "add to cart" again, the product is added with the WC Fields Factory options

It's about this file
/wp-content/themes/bootscore-main/woocommerce/ajax-cart/ajax-add-to-cart.php 

Please help

**Comment by crftwrk** [comment]
Please share a link to your product site to reproduce the issue.

In next release, the Ajax cart is a pluggable function and can be disabled in child-theme. This is already merged in main branch. You can download latest developed version and disable it. Note that you have to install new child as well.

**Comment by crftwrk** [comment]
Haven't heard anything here for a while. Close the issue now.
