### ISSUE TITLE
How to enqueue css and js files

### ISSUE THREAD

**Issue by AteS-Github** [bootscore/bootscore#129]
hi when i download bootstrap template
gives css and js files
I know how to run these files only on the home page
The theme is getting corrupted when I add it to the sccs folder
If you only work on the main page, I want these files to be active on the whole site, how can I do it, thank you in advance

sample site: https://kombiservisklima.com/
now only js and css files attached on the main page

**Comment by AteS-Github** [comment]
animate.min.css
bundle.min.css
css/style.css
xpoge.css
responsive.css
bootstrap.bundle.min.js
swiper-bundle.min.js
main.js
These are the files I took with the remote rel="stylesheet"> code, I added them to the functions.php folder, it broke the theme again, for example, the menu on the main page is broken in the theme.

**Comment by crftwrk** [comment]
Please do not mix this.

1. Bootstrap scss is included in main-theme and gets compiled automaticly to your child.
2. Custom styles go in your child to _bscore.scss
3. bootstrap.bundle.min.js is included in main-theme
4. Custom JS goes in your child to custom.js
5. All this files are already there, you do not must add them

### Add new files

If you want to add new libraries like animate.min.css, you must enqueue them in child' functions.php

```php
// Animate css
wp_enqueue_style( 'animate, get_stylesheet_directory_uri() . '/path-to-your-file/animate.min.css');
```

Enqueue script can look like this:

```php
// style and scripts
add_action('wp_enqueue_scripts', 'bootscore_child_enqueue_styles');
function bootscore_child_enqueue_styles() {

  // style.css
  wp_enqueue_style('parent-style', get_template_directory_uri() . '/style.css');

  // Animate css
  wp_enqueue_style( 'animate, get_stylesheet_directory_uri() . '/path-to-your-file/animate.min.css');

  // Compiled main.css
  $modified_bootscoreChildCss = date('YmdHi', filemtime(get_stylesheet_directory() . '/css/main.css'));
  wp_enqueue_style('main', get_stylesheet_directory_uri() . '/css/main.css', array('parent-style'), $modified_bootscoreChildCss);

  // custom.js
  wp_enqueue_script('custom-js', get_stylesheet_directory_uri() . '/js/custom.js', false, '', true);
}

```

**Comment by AteS-Github** [comment]
`<?php

/**
 * Bootscore functions and definitions
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package Bootscore
 */


// WooCommerce
//require get_template_directory() . '/woocommerce/woocommerce-functions.php';
// WooCommerce END


// Register Bootstrap 5 Nav Walker
if (!function_exists('register_navwalker')) :
  function register_navwalker() {
    require_once('inc/class-bootstrap-5-navwalker.php');
    // Register Menus
    register_nav_menu('main-menu', 'Main menu');
    register_nav_menu('footer-menu', 'Footer menu');
  }
endif;
add_action('after_setup_theme', 'register_navwalker');
// Register Bootstrap 5 Nav Walker END


// Register Comment List
if (!function_exists('register_comment_list')) :
  function register_comment_list() {
    // Register Comment List
    require_once('inc/comment-list.php');
  }
endif;
add_action('after_setup_theme', 'register_comment_list');
// Register Comment List END


if (!function_exists('bootscore_setup')) :
  /**
   * Sets up theme defaults and registers support for various WordPress features.
   *
   * Note that this function is hooked into the after_setup_theme hook, which
   * runs before the init hook. The init hook is too late for some features, such
   * as indicating support for post thumbnails.
   */
  function bootscore_setup() {
    /*
		 * Make theme available for translation.
		 * Translations can be filed in the /languages/ directory.
		 * If you're building a theme based on Bootscore, use a find and replace
		 * to change 'bootscore' to the name of your theme in all the template files.
		 */
    load_theme_textdomain('bootscore', get_template_directory() . '/languages');

    // Add default posts and comments RSS feed links to head.
    add_theme_support('automatic-feed-links');

    /*
		 * Let WordPress manage the document title.
		 * By adding theme support, we declare that this theme does not use a
		 * hard-coded <title> tag in the document head, and expect WordPress to
		 * provide it for us.
		 */
    add_theme_support('title-tag');

    /*
		 * Enable support for Post Thumbnails on posts and pages.
		 *
		 * @link https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/
		 */
    add_theme_support('post-thumbnails');

    /*
		 * Switch default core markup for search form, comment form, and comments
		 * to output valid HTML5.
		 */
    add_theme_support('html5', array(
      'comment-form',
      'comment-list',
      'gallery',
      'caption',
    ));

    // Add theme support for selective refresh for widgets.
    add_theme_support('customize-selective-refresh-widgets');
  }
endif;
add_action('after_setup_theme', 'bootscore_setup');

/**
 * Set the content width in pixels, based on the theme's design and stylesheet.
 *
 * Priority 0 to make it available to lower priority callbacks.
 *
 * @global int $content_width
 */
function bootscore_content_width() {
  // This variable is intended to be overruled from themes.
  // Open WPCS issue: {@link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1043}.
  // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound
  $GLOBALS['content_width'] = apply_filters('bootscore_content_width', 640);
}
add_action('after_setup_theme', 'bootscore_content_width', 0);





/**
 * Register widget area.
 *
 * @link https://developer.wordpress.org/themes/functionality/sidebars/#registering-a-sidebar
 */
// Widgets
if (!function_exists('bootscore_widgets_init')) :

  function bootscore_widgets_init() {

    // Top Nav
    register_sidebar(array(
      'name' => esc_html__('Top Nav', 'bootscore'),
      'id' => 'top-nav',
      'description' => esc_html__('Add widgets here.', 'bootscore'),
      'before_widget' => '<div class="ms-3">',
      'after_widget' => '</div>',
      'before_title' => '<div class="widget-title d-none">',
      'after_title' => '</div>'
    ));
    // Top Nav End

    // Top Nav Search
    register_sidebar(array(
      'name' => esc_html__('Top Nav Search', 'bootscore'),
      'id' => 'top-nav-search',
      'description' => esc_html__('Add widgets here.', 'bootscore'),
      'before_widget' => '<div class="top-nav-search">',
      'after_widget' => '</div>',
      'before_title' => '<div class="widget-title d-none">',
      'after_title' => '</div>'
    ));
    // Top Nav Search End

    // Sidebar
    register_sidebar(array(
      'name'          => esc_html__('Sidebar', 'bootscore'),
      'id'            => 'sidebar-1',
      'description'   => esc_html__('Add widgets here.', 'bootscore'),
      'before_widget' => '<section id="%1$s" class="widget %2$s card card-body mb-4 bg-light border-0">',
      'after_widget'  => '</section>',
      'before_title'  => '<h2 class="widget-title card-title border-bottom py-2">',
      'after_title'   => '</h2>',
    ));
    // Sidebar End

    // Top Footer
    register_sidebar(array(
      'name' => esc_html__('Top Footer', 'bootscore'),
      'id' => 'top-footer',
      'description' => esc_html__('Add widgets here.', 'bootscore'),
      'before_widget' => '<div class="footer_widget mb-5">',
      'after_widget' => '</div>',
      'before_title' => '<h2 class="widget-title">',
      'after_title' => '</h2>'
    ));
    // Top Footer End

    // Footer 1
    register_sidebar(array(
      'name' => esc_html__('Footer 1', 'bootscore'),
      'id' => 'footer-1',
      'description' => esc_html__('Add widgets here.', 'bootscore'),
      'before_widget' => '<div class="footer_widget mb-4">',
      'after_widget' => '</div>',
      'before_title' => '<h2 class="widget-title h4">',
      'after_title' => '</h2>'
    ));
    // Footer 1 End

    // Footer 2
    register_sidebar(array(
      'name' => esc_html__('Footer 2', 'bootscore'),
      'id' => 'footer-2',
      'description' => esc_html__('Add widgets here.', 'bootscore'),
      'before_widget' => '<div class="footer_widget mb-4">',
      'after_widget' => '</div>',
      'before_title' => '<h2 class="widget-title h4">',
      'after_title' => '</h2>'
    ));
    // Footer 2 End

    // Footer 3
    register_sidebar(array(
      'name' => esc_html__('Footer 3', 'bootscore'),
      'id' => 'footer-3',
      'description' => esc_html__('Add widgets here.', 'bootscore'),
      'before_widget' => '<div class="footer_widget mb-4">',
      'after_widget' => '</div>',
      'before_title' => '<h2 class="widget-title h4">',
      'after_title' => '</h2>'
    ));
    // Footer 3 End

    // Footer 4
    register_sidebar(array(
      'name' => esc_html__('Footer 4', 'bootscore'),
      'id' => 'footer-4',
      'description' => esc_html__('Add widgets here.', 'bootscore'),
      'before_widget' => '<div class="footer_widget mb-4">',
      'after_widget' => '</div>',
      'before_title' => '<h2 class="widget-title h4">',
      'after_title' => '</h2>'
    ));
    // Footer 4 End

    // 404 Page
    register_sidebar(array(
      'name' => esc_html__('404 Page', 'bootscore'),
      'id' => '404-page',
      'description' => esc_html__('Add widgets here.', 'bootscore'),
      'before_widget' => '<div class="mb-4">',
      'after_widget' => '</div>',
      'before_title' => '<h1 class="widget-title">',
      'after_title' => '</h1>'
    ));
    // 404 Page End

  }
  add_action('widgets_init', 'bootscore_widgets_init');


endif;
// Widgets END


// Shortcode in HTML-Widget
add_filter('widget_text', 'do_shortcode');
// Shortcode in HTML-Widget End



//Enqueue scripts and styles
function bootscore_scripts() {

  // Get modification time. Enqueue files with modification date to prevent browser from loading cached scripts and styles when file content changes.
  $modificated_styleCss = date('YmdHi', filemtime(get_stylesheet_directory() . '/style.css'));
  if (file_exists(get_template_directory() . '/css/main.css')) {
    $modificated_bootscoreCss = date('YmdHi', filemtime(get_template_directory() . '/css/main.css'));
  } else {
    $modificated_bootscoreCss = 1;
  }
  $modificated_fontawesomeCss = date('YmdHi', filemtime(get_template_directory() . '/css/lib/fontawesome.min.css'));
  $modificated_bootstrapJs = date('YmdHi', filemtime(get_template_directory() . '/js/lib/bootstrap.bundle.min.js'));
  $modificated_themeJs = date('YmdHi', filemtime(get_template_directory() . '/js/theme.js'));

  // Style CSS
  wp_enqueue_style('bootscore-style', get_stylesheet_uri(), array(), $modificated_styleCss);

  // bootScore
  require_once 'inc/scss-compiler.php';
  bootscore_compile_scss();
  wp_enqueue_style('main', get_template_directory_uri() . '/css/main.css', array(), $modificated_bootscoreCss);

  // Fontawesome
  wp_enqueue_style('fontawesome', get_template_directory_uri() . '/css/lib/fontawesome.min.css', array(), $modificated_fontawesomeCss);

  // Bootstrap JS
  wp_enqueue_script('bootstrap', get_template_directory_uri() . '/js/lib/bootstrap.bundle.min.js', array(), $modificated_bootstrapJs, true);

  // Theme JS
  wp_enqueue_script('bootscore-script', get_template_directory_uri() . '/js/theme.js', array('jquery'), $modificated_themeJs, true);
  
  // IE Warning
  wp_localize_script('bootscore-script', 'bootscore', array(
    'ie_title' => __('Internet Explorer detected', 'bootscore'),
    'ie_limited_functionality' => __('This website will offer limited functionality in this browser.', 'bootscore'),
    'ie_modern_browsers_1' => __('Please use a modern and secure web browser like', 'bootscore'),
    'ie_modern_browsers_2' => __(' <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> ' , 'bootscore'),
    'ie_modern_browsers_3' => __('or', 'bootscore'),
    'ie_modern_browsers_4' => __(' <a href="https://www.microsoft.com/edge" target="_blank">Microsoft Edge</a> ' , 'bootscore'),
    'ie_modern_browsers_5' => __('to display this site correctly.', 'bootscore'),
  ));
  // IE Warning End

  if (is_singular() && comments_open() && get_option('thread_comments')) {
    wp_enqueue_script('comment-reply');
  }
}
add_action('wp_enqueue_scripts', 'bootscore_scripts');
//Enqueue scripts and styles END


// Add <link rel=preload> to Fontawesome
add_filter('style_loader_tag', 'wpse_231597_style_loader_tag');

function wpse_231597_style_loader_tag($tag) {

  $tag = preg_replace("/id='font-awesome-css'/", "id='font-awesome-css' online=\"if(media!='all')media='all'\"", $tag);

  return $tag;
}
// Add <link rel=preload> to Fontawesome END


/**
 * Custom template tags for this theme.
 */
require get_template_directory() . '/inc/template-tags.php';

/**
 * Functions which enhance the theme by hooking into WordPress.
 */
require get_template_directory() . '/inc/template-functions.php';


/**
 * Load Jetpack compatibility file.
 */
if (defined('JETPACK__VERSION')) {
  require get_template_directory() . '/inc/jetpack.php';
}


// Amount of posts/products in category
if (!function_exists('wpsites_query')) :

  function wpsites_query($query) {
    if ($query->is_archive() && $query->is_main_query() && !is_admin()) {
      $query->set('posts_per_page', 24);
    }
  }
  add_action('pre_get_posts', 'wpsites_query');

endif;
// Amount of posts/products in category END


// Pagination Categories
if (!function_exists('bootscore_pagination')) :

  function bootscore_pagination($pages = '', $range = 2) {
    $showitems = ($range * 2) + 1;
    global $paged;
    if ($pages == '') {
      global $wp_query;
      $pages = $wp_query->max_num_pages;

      if (!$pages)
        $pages = 1;
    }

    if (1 != $pages) {
      echo '<nav aria-label="Page navigation" role="navigation">';
      echo '<span class="sr-only">Page navigation</span>';
      echo '<ul class="pagination justify-content-center ft-wpbs mb-4">';


      if ($paged > 2 && $paged > $range + 1 && $showitems < $pages)
        echo '<li class="page-item"><a class="page-link" href="' . get_pagenum_link(1) . '" aria-label="First Page">&laquo;</a></li>';

      if ($paged > 1 && $showitems < $pages)
        echo '<li class="page-item"><a class="page-link" href="' . get_pagenum_link($paged - 1) . '" aria-label="Previous Page">&lsaquo;</a></li>';

      for ($i = 1; $i <= $pages; $i++) {
        if (1 != $pages && (!($i >= $paged + $range + 1 || $i <= $paged - $range - 1) || $pages <= $showitems))
          echo ($paged == $i) ? '<li class="page-item active"><span class="page-link"><span class="sr-only">Current Page </span>' . $i . '</span></li>' : '<li class="page-item"><a class="page-link" href="' . get_pagenum_link($i) . '"><span class="sr-only">Page </span>' . $i . '</a></li>';
      }

      if ($paged < $pages && $showitems < $pages)
        echo '<li class="page-item"><a class="page-link" href="' . get_pagenum_link(($paged === 0 ? 1 : $paged) + 1) . '" aria-label="Next Page">&rsaquo;</a></li>';

      if ($paged < $pages - 1 &&  $paged + $range - 1 < $pages && $showitems < $pages)
        echo '<li class="page-item"><a class="page-link" href="' . get_pagenum_link($pages) . '" aria-label="Last Page">&raquo;</a></li>';

      echo '</ul>';
      echo '</nav>';
      // Uncomment this if you want to show [Page 2 of 30]
      // echo '<div class="pagination-info mb-5 text-center">[ <span class="text-muted">Page</span> '.$paged.' <span class="text-muted">of</span> '.$pages.' ]</div>';	 	
    }
  }

endif;
//Pagination Categories END


// Pagination Buttons Single Posts
add_filter('next_post_link', 'post_link_attributes');
add_filter('previous_post_link', 'post_link_attributes');

function post_link_attributes($output) {
  $code = 'class="page-link"';
  return str_replace('<a href=', '<a ' . $code . ' href=', $output);
}
// Pagination Buttons Single Posts END


// Excerpt to pages
add_post_type_support('page', 'excerpt');
// Excerpt to pages END


// Breadcrumb
if (!function_exists('the_breadcrumb')) :
  function the_breadcrumb() {
    if (!is_home()) {
      echo '<nav class="breadcrumb mb-4 mt-2 bg-light py-2 px-3 small rounded">';
      echo '<a href="' . home_url('/') . '">' . ('<i class="fa-solid fa-house"></i>') . '</a><span class="divider">&nbsp;/&nbsp;</span>';
      if (is_category() || is_single()) {
        the_category(' <span class="divider">&nbsp;/&nbsp;</span> ');
        if (is_single()) {
          echo ' <span class="divider">&nbsp;/&nbsp;</span> ';
          the_title();
        }
      } elseif (is_page()) {
        echo the_title();
      }
      echo '</nav>';
    }
  }
  add_filter('breadcrumbs', 'breadcrumbs');
endif;
// Breadcrumb END


// Comment Button
function bootscore_comment_form($args) {
  $args['class_submit'] = 'btn btn-outline-primary'; // since WP 4.1    
  return $args;
}
add_filter('comment_form_defaults', 'bootscore_comment_form');
// Comment Button END


// Password protected form
function bootscore_pw_form() {
  $output = '
		  <form action="' . get_option('siteurl') . '/wp-login.php?action=postpass" method="post" class="form-inline">' . "\n"
    . '<input name="post_password" type="password" size="" class="form-control me-2 my-1" placeholder="' . __('Password', 'bootscore') . '"/>' . "\n"
    . '<input type="submit" class="btn btn-outline-primary my-1" name="Submit" value="' . __('Submit', 'bootscore') . '" />' . "\n"
    . '</p>' . "\n"
    . '</form>' . "\n";
  return $output;
}
add_filter("the_password_form", "bootscore_pw_form");
// Password protected form END


// Allow HTML in term (category, tag) descriptions
foreach (array('pre_term_description') as $filter) {
  remove_filter($filter, 'wp_filter_kses');
  if (!current_user_can('unfiltered_html')) {
    add_filter($filter, 'wp_filter_post_kses');
  }
}

foreach (array('term_description') as $filter) {
  remove_filter($filter, 'wp_kses_data');
}
// Allow HTML in term (category, tag) descriptions END


// Allow HTML in author bio
remove_filter('pre_user_description', 'wp_filter_kses');
add_filter('pre_user_description', 'wp_filter_post_kses');
// Allow HTML in author bio END


// Hook after #primary
function bs_after_primary() {
  do_action('bs_after_primary');
}
// Hook after #primary END


// Open links in comments in new tab
if (!function_exists('bs_comment_links_in_new_tab')) :
  function bs_comment_links_in_new_tab($text) {
    return str_replace('<a', '<a target="_blank" rel=”nofollow”', $text);
  }
  add_filter('comment_text', 'bs_comment_links_in_new_tab');
endif;
// Open links in comments in new tab END


// Disable Gutenberg blocks in widgets (WordPress 5.8)
// Disables the block editor from managing widgets in the Gutenberg plugin.
add_filter('gutenberg_use_widgets_block_editor', '__return_false');
// Disables the block editor from managing widgets.
add_filter('use_widgets_block_editor', '__return_false');
// Disable Gutenberg blocks in widgets (WordPress 5.8) END


   // style.css
  wp_enqueue_style('parent-style', get_template_directory_uri() . '/yba/css-js/assets/css/style.css');

  // Animate css
  wp_enqueue_style( 'animate, get_stylesheet_directory_uri() . '/yba/css-js/assets/vendor/animate.css/animate.min.css');
  
  // swiper css
  wp_enqueue_style( 'swiper, get_stylesheet_directory_uri() . '/yba/css-js/assets/vendor/swiper/swiper-bundle.min.css');
  
  // xpoge css
  wp_enqueue_style( 'xpoge, get_stylesheet_directory_uri() . '/yba/css-js/css/xpoge.css');

  // responsive css
  wp_enqueue_style( 'responsive, get_stylesheet_directory_uri() . '/yba/css-js/css/responsive.css');

  // swiper.js
  wp_enqueue_script('swiper-js', get_stylesheet_directory_uri() . '/yba/css-js/assets/vendor/swiper/swiper-bundle.min.js', false, '', true);
  
  // main.js
  wp_enqueue_script('main-js', get_stylesheet_directory_uri() . '/yba/css-js/assets/js/main.js', false, '', true);

`

**Comment by AteS-Github** [comment]
i'm sorry but i messed you up
I added it this way, it gave an error, I'm doing something wrong, but could you please check, I got an error in both the main theme and the child theme

**Comment by AteS-Github** [comment]
``// style and scripts
add_action('wp_enqueue_scripts', 'bootscore_child_enqueue_styles');
function bootscore_child_enqueue_styles() {

   // style.css
  wp_enqueue_style('parent-style', get_template_directory_uri() . '/yba/css-js/assets/css/style.css');

  // Animate css
  wp_enqueue_style( 'animate, get_stylesheet_directory_uri() . '/yba/css-js/assets/vendor/animate.css/animate.min.css');
  
  // swiper css
  wp_enqueue_style( 'swiper, get_stylesheet_directory_uri() . '/yba/css-js/assets/vendor/swiper/swiper-bundle.min.css');
  
  // xpoge css
  wp_enqueue_style( 'xpoge, get_stylesheet_directory_uri() . '/yba/css-js/css/xpoge.css');

  // responsive css
  wp_enqueue_style( 'responsive, get_stylesheet_directory_uri() . '/yba/css-js/css/responsive.css');

  // swiper.js
  wp_enqueue_script('swiper-js', get_stylesheet_directory_uri() . '/yba/css-js/assets/vendor/swiper/swiper-bundle.min.js', false, '', true);
  
  // main.js
  wp_enqueue_script('main-js', get_stylesheet_directory_uri() . '/yba/css-js/assets/js/main.js', false, '', true);

}

**Comment by AteS-Github** [comment]
I got an error when I added it like this

**Comment by AteS-Github** [comment]
If you want, I can give you an ftp address and password.

**Comment by crftwrk** [comment]
Of course, not 😉

You can create a ftp account and send it to store(at)bootscore.me. I will enqueue one file, so you can see how it works and do other ones by yourself.

**Comment by AteS-Github** [comment]
I sent

**Comment by crftwrk** [comment]
Enqueued `glass-case.css` in `functions.php` in line `11` and `owl.carousel.min.js` in line `14`. Use this snippets to enqueue your other files.

```php
// glass-case.css
wp_enqueue_style('glass-case', get_stylesheet_directory_uri() . '/yba/css-js/css/glass-case.css');

// owl.carousel.min.js
wp_enqueue_script('owl-carousel', get_stylesheet_directory_uri() . '/yba/css-js/js/owl.carousel.min.js', false, '', true);
```

### DO NOT

- `bootstrap.min.css`
- `bootstrap.min.js`
- `font-awesome.min.css`
- `jquery-3.4.1.min.js`

These files are already in theme. Using them twice will not work.

**Comment by AteS-Github** [comment]
`<?php

// style and scripts
add_action('wp_enqueue_scripts', 'bootscore_child_enqueue_styles');
function bootscore_child_enqueue_styles() {

  // style.css
  wp_enqueue_style('parent-style', get_template_directory_uri() . '/style.css');
  
  // animate.min.css
  wp_enqueue_style('animate-css', get_stylesheet_directory_uri() . '/yba/css-js/assets/vendor/animate.css/animate.min.css');
  
  // swiper-bundle.min.css
  wp_enqueue_style('swiper-bundle', get_stylesheet_directory_uri() . '/yba/css-js/assets/vendor/swiper/swiper-bundle.min.css');
  
  // style.css
  wp_enqueue_style('style-dosya', get_stylesheet_directory_uri() . '/yba/css-js/assets/css/style.css');
  
  // xpoge.css
  wp_enqueue_style('xpoge-css', get_stylesheet_directory_uri() . '/yba/css-js/css/xpoge.css');
  
  // responsive.css
  wp_enqueue_style('responsive-css', get_stylesheet_directory_uri() . '/yba/css-js/css/responsive.css');
  
  // swiper-bundle.min.js
  wp_enqueue_script('swiper-bundle', get_stylesheet_directory_uri() . '/yba/css-js/assets/vendor/swiper/swiper-bundle.min.js', false, '', true);

  // main.js
  wp_enqueue_script('main', get_stylesheet_directory_uri() . '/yba/css-js/assets/js/main.js', false, '', true);

  // owl.carousel.min.js
  wp_enqueue_script('owl-carousel', get_stylesheet_directory_uri() . '/yba/css-js/js/owl.carousel.min.js', false, '', true);

  // Compiled main.css
  $modified_bootscoreChildCss = date('YmdHi', filemtime(get_stylesheet_directory() . '/css/main.css'));
  wp_enqueue_style('main', get_stylesheet_directory_uri() . '/css/main.css', array('parent-style'), $modified_bootscoreChildCss);

  // custom.js
  wp_enqueue_script('custom-js', get_stylesheet_directory_uri() . '/js/custom.js', false, '', true);
}

// WooCommerce
require get_template_directory() . '/woocommerce/woocommerce-functions.php';
`

**Comment by AteS-Github** [comment]
`https://kombiservisklima.com/sepet/`

yes, I added it this way, looking at what you added, the site menu is broken, I'll take care of it with a plugin anyway

**Comment by AteS-Github** [comment]
For example, I noticed that the cart page, the archive page, is a single post and the header on the pages shows a title on the menu, I think we can solve this with code.

**Comment by crftwrk** [comment]
👍

**Comment by AteS-Github** [comment]
Thank you very much for your help
