### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by justinkruit** [bootscore/bootscore#13]
After working with the CSS thanks to issue #12, I noticed that the entire project uses 4 spaces, instead of the default 2. I also noticed you don't use a code formatter (seen from the ; missing sometimes in the CSS). Are you alright with it if I try to format the entire project? So default 2 spaces, classes sorted, and correct indentation in PHP.

I completely understand if you don't want it, just want to suggest it.

**Comment by justinkruit** [comment]
May I ask, do you use any IDE? Maybe I can help you out with also acquiring some formatting tools on your own 😁

**Comment by crftwrk** [comment]
Not yet. So far I've been fine with my editor and a few plugins. But I like to learn ;-)

One more thing. I'm cleaning up GitHub and want to push the whole project out of my personal profile into an organisation profile for better handling the project. Can I invite you as a member there?

**Comment by justinkruit** [comment]
I'm using VSCode myself, but with a few good extensions it is a pretty solid IDE.

And yes, I would love to! Great idea to put it into an organisation, would definitely make the management easier.

**Comment by crftwrk** [comment]
That's a good idea, will check that. I use VSCode Editor as well, so VSCode is the best choice ;-)

Invited to new repo. I will try to push all themes and plugins to this new repo in the next days.

**Comment by justinkruit** [comment]
By the way, do you want me to work in branches on this repo, and then make a pull request? Or do you prefer if I did it in a fork and then pull requested? Orrr would you rather that I just commit to the main branch now?

**Comment by crftwrk** [comment]
Think committing to main branch is fine? Whats your choice?

**Comment by justinkruit** [comment]
I think for small changes I'll commit to the main branch, and for big changes, like the formatting of the entire repo, I'll create a branch which can be removed later. Is that a good plan?

**Comment by crftwrk** [comment]
Perfect plan!

**Comment by justinkruit** [comment]
Can I have writing access then? :-P
GitHub Desktop just alerted me that I don't have writing access to the repo, while trying to create a fork.

**Comment by crftwrk** [comment]
Changed your rule to owner, should work now.

**Comment by crftwrk** [comment]
Thank you very mich for this! 👍

**Comment by justinkruit** [comment]
No problem! 😁
