### ISSUE TITLE
Woocommerce gutenberg blocks still has own Add to cart style

### ISSUE THREAD

**Issue by kangarooo** [bootscore/bootscore#130]
Woocommerce gutenberg blocks still has own Add to cart style
![image](https://user-images.githubusercontent.com/73187/161424580-5185697b-127a-460c-8b68-830e130fbcb3.png)

**Comment by crftwrk** [comment]
Gutenberg Blocks are not supported. Use WooCommerce shortcodes https://woocommerce.com/document/woocommerce-shortcodes/#section-9

For example `[recent_products]`

**Comment by kangarooo** [comment]
Was able to format gutenberg block _bscore_custom.scss
.wc-block-grid__product-add-to-cart a {
    @extend .btn;
    @extend .btn-primary;
}

Thx woocommerce shortcodes are better.

**Comment by crftwrk** [comment]
👍 You're welcome.
