### ISSUE TITLE
Wrong timezone

### ISSUE THREAD

**Issue by lennertfabriek** [bootscore/bootscore#134]
Hi Basti!

First of all, I don't think this is a problem with your theme. But maybe it is;p

It's about https://eetcafedebuorren.nl/

I have at the bottom of the page a section with opening hours. When the restaurant is open the hours will be green and with an open sign next to the title. But the problem is that the code is running 2 hours behind the actual time. So when The opening hour is 07:00 it gets green at 09:00.

The wordpress timezone is amsterdam. And if I use the code; date_default_timezone_set('Europe/Amsterdam'); The time is changing on the front and with 2 hours different (earlier) than the custom field.

**Comment by lennertfabriek** [comment]
echo date("H:i"); 
 
is btw 2 hours earlier. And with the default timezone amsterdam the frontend gets 2 hours earlier

**Comment by crftwrk** [comment]
Hi Lennart,

of course, this has nothing to do with the theme. Are you using ACF? If so, you should open this issue there https://github.com/AdvancedCustomFields/acf. 

I had a similar problem with sending scheduled mails in Mailchimp. Solved this roughly by changing the timezone. Not nice, but works ;-)

BTW you should take the safari-pinned-tab icon seriously:

<img width="263" alt="Bildschirmfoto 2022-04-05 um 16 12 59" src="https://user-images.githubusercontent.com/51531217/161775031-0d09f70e-417d-4ffe-b331-57d7e0e05254.png">

**Comment by lennertfabriek** [comment]
Thanks! I have always problems with the pinned tabs. But this was something I still need to do with this website

Thanks thanks thanks

**Comment by lennertfabriek** [comment]
And

date('H:i', current_time('timestamp'))

Did the job

**Comment by justinkruit** [comment]
From what I see, current_time('timestamp') should get the current timestamp with time zone. But from what I read in the documentation, wp_date('H:i') should be the "better" way, and more future proof.
