### ISSUE TITLE
Create multiple SCSS files

### ISSUE THREAD

**Issue by srjlulla** [bootscore/bootscore#137]
First of all, incredible theme + exceptional work & support. Kudos to you guys!

I have a doubt that I've been circling around for a while now. I use css/scss/_bscore_custom.scss for all the global custom SCSS.

However, I have a habit of creating separate CSS files for one-off pages to improve performance.

**Main question** - is there a way to create multiple custom SCSS files that are not combined together?

**Comment by crftwrk** [comment]
Thank you!

> Main question - is there a way to create multiple custom SCSS files that are not combined together?

You can add as many SCSS files as you want in `css/scss/_bootstrap.min.css` using `@import`. Note that this folder structure and filenames changed by the next release. All SCSS will be combined to one single CSS file at the end to reduce file requests for performance reason. So, no it's not possible to compile different SCSS files to different CSS files.

What you can do is to enqueue new CSS files in child's `functions.php` and use normal CSS.

Does this help?

**Comment by srjlulla** [comment]
Yes, I've been currently following the normal CSS process for this. Just wanted to know if there was an SCSS way.

**Comment by crftwrk** [comment]
> Yes, I've been currently following the normal CSS process for this. Just wanted to know if there was an SCSS way.

👍
