### ISSUE TITLE
Footer on woocommerce /shop page is not full width

### ISSUE THREAD

**Issue by akvrmvlakis** [bootscore/bootscore#139]
Hello Basti, I am facing this issue with the footer for some reason I can't seem to get it to appear full width on the assigned shop page for woocommerce. I understand that this page corresponds to content-product.php I have tried to manipulate it with no success and was wondering if you could point me to the right direction. I have made a woocommerce folder on my child theme and copied content-product.php there everything seems to be working fine it reacts to changes made on it but I am unable to make the footer fullwidth as in the rest of the pages. This is the shop page: https://akvrmvlakis.a2hosted.com/shop/ and I want to make the footer look like here on the home page: https://akvrmvlakis.a2hosted.com/ These are the contents of content-product.php: 

```<?php

/**
 * The template for displaying product content within loops
 *
 * This template can be overridden by copying it to yourtheme/woocommerce/content-product.php.
 *
 * HOWEVER, on occasion WooCommerce will need to update template files and you
 * (the theme developer) will need to copy the new files to your theme to
 * maintain compatibility. We try to do this as little as possible, but it does
 * happen. When this occurs the version of the template file will be bumped and
 * the readme will list any important changes.
 *
 * @see     https://docs.woocommerce.com/document/template-structure/
 * @package WooCommerce/Templates
 * @version 3.6.0
 */

defined('ABSPATH') || exit;

global $product;

// Ensure visibility.
if (empty($product) || !$product->is_visible()) {
  return;
}
?>

<div class="col-md-6 col-lg-4 col-xxl-3 mb-4">
  <div <?php wc_product_class('card h-100 d-flex text-center', $product); ?>>
    <?php
    /**
     * Hook: woocommerce_before_shop_loop_item.
     *
     * @hooked woocommerce_template_loop_product_link_open - 10
     */
    do_action('woocommerce_before_shop_loop_item');

    /**
     * Hook: woocommerce_before_shop_loop_item_title.
     *
     * @hooked woocommerce_show_product_loop_sale_flash - 10
     * @hooked woocommerce_template_loop_product_thumbnail - 10
     */
    do_action('woocommerce_before_shop_loop_item_title');
    ?>
    <div class="card-body d-flex flex-column">
      <?php
      /**
       * Hook: woocommerce_shop_loop_item_title.
       *
       * @hooked woocommerce_template_loop_product_title - 10
       */
      do_action('woocommerce_shop_loop_item_title');
      /**
       * Hook: woocommerce_after_shop_loop_item_title.
       *
       * @hooked woocommerce_template_loop_rating - 5
       * @hooked woocommerce_template_loop_price - 10
       */
      do_action('woocommerce_after_shop_loop_item_title');

      /**
       * Hook: woocommerce_after_shop_loop_item.
       *
       * @hooked woocommerce_template_loop_product_link_close - 5
       * @hooked woocommerce_template_loop_add_to_cart - 10
       */
      do_action('woocommerce_after_shop_loop_item');
      ?>
</div>
</div>
</div>
```

Many thanks in advance and much love I'll move on with the translation as soon as I am done with this project.

**Comment by crftwrk** [comment]
Hi,

Seems there is a closing `</div>` tag missing somewhere. Think this is in `woocommerce.php`, because this bug is on product pages too https://akvrmvlakis.a2hosted.com/product/folder-a4-1-όψη/.

Have you edited this file in your child? If so, delete it and start doing changes with a fresh copy of this file.

Does this help?

**Comment by akvrmvlakis** [comment]
Hello Basti,

Indeed you were right! I placed a copy of woocommerce.php on my child theme and deleted from that file lines 36,37,38 and it worked. Both the /shop and product pages have a regular footer now like the rest of the site.  I am including you the part of code from woocommerce.php that caused the issue thank you so much for this It's much appreciated I've been stuck on it for days.

`  <?php woocommerce_breadcrumb(); ?>
      <div class="row">
        <div class="col">`

**Comment by crftwrk** [comment]
You‘re welcome 👍
