### ISSUE TITLE
Update Bootstrap 5.2.0

### ISSUE THREAD

**Issue by crftwrk** [bootscore/bootscore#140]
- [x] Update Bootstrap 5.2.0-beta1 https://github.com/bootscore/bootscore/commit/7389d0785d674eafccc9b74fbc45de32ea11d051
- [x] Update variables docs
- [x] Check Scrollspy and docs
- [x] Update header.php docs
- [x] Update FA6 docs
- [x] Update Google Fonts docs
- [x] Update translation docs
- [x] Dark mode Accordion
- [x] Remove `/scss/bootscore/_offcanvas.scss` https://github.com/bootscore/bootscore/pull/159
- [x] Rename page-blank-without-container to page-blank.php https://github.com/bootscore/bootscore/pull/163
- [x] Store page and single templates in folder https://github.com/bootscore/bootscore/pull/163
- [x] Remove navbar-light classes in header.php https://github.com/bootscore/bootscore/commit/54985949a75219db1e7139e21bca867619ed07e0
- [x] Added responsive offcancas to _admin_bar.scss https://github.com/bootscore/bootscore/commit/627abe95e946c8ab4a63cb7b418c9a5eddebc621
- [x] Change badge `text-bg-*` classes https://github.com/bootscore/bootscore/commit/ca17c9d617497689cb92e79358f8e2886d01122e
- [x] Pagination border hotfix https://github.com/bootscore/bootscore/commit/571c3aa953582b901a362f992c528d2ede7dd0f9
- [x] Modal bS Cookie Settings plugin hotfix https://github.com/bootscore/bootscore/commit/150fa4c1bcbdc93f1a2f88e33bed1ce70f1f74cb
- [x] Sidebar to responsive offcanvas https://github.com/bootscore/bootscore/pull/171
- [x] Disable/rewrite smooth scroll docs
- [x] Rewrite IE alert docs
- [x] Update child-themes 
- [x] Update Bootstrap 5.2.0 stable https://github.com/bootscore/bootscore/commit/da15257ff2d69e854198a618aa6843477250275e
- [x] Update version numbers https://github.com/bootscore/bootscore/commit/de7f69ebd6ccad0fed7ead497580c232180a808d
- [x] Revisit Pagination border hotfix https://github.com/bootscore/bootscore/commit/571c3aa953582b901a362f992c528d2ede7dd0f9, new hotfix https://github.com/bootscore/bootscore/commit/16eb38e8f6452df919d5ef9d0c0339e408400405
- [x] Revisit Modal bS Cookie Settings plugin hotfix https://github.com/bootscore/bootscore/commit/150fa4c1bcbdc93f1a2f88e33bed1ce70f1f74cb
- [x] Update readme.txt https://github.com/bootscore/bootscore/commit/f5ba759b366c4b1588c7d21767f6e27268c5ec74
- [x] Update guide for page / post templates https://github.com/bootscore/bootscore/pull/163

**Comment by justinkruit** [comment]
I guess this is in anticipation for the 5.2 release? Honestly can't wait, looks like it has some nice improvements.

But at the same time, still at least 19 Todo items, and 7 in progress, so that can still be a few weeks or months unfortunately.

**Comment by crftwrk** [comment]
Check here https://dev.bootscore.me/. It's the actual Bootstrap main branch. Scrollspy will be a big challenge.

**Comment by vahidalvandi** [comment]
like

**Comment by justinkruit** [comment]
> Most major things are done and I'm sure they deliver in weeks, not in months.

So naive... 😂

**Comment by crftwrk** [comment]
> So naive... 😂

Yes, but now we get closer 😉
