### ISSUE TITLE
How to use the pagination ?

### ISSUE THREAD

**Issue by neerbappoo** [bootscore/bootscore#144]
I got this piece of code to fetch my blog post : 

![image](https://user-images.githubusercontent.com/8381087/165719745-a9663e13-817d-497e-bd8d-4c97fa87888e.png)

Then I echo the pagination before the endif like so : `<?php echo bootscore_pagination(); ?>`

The pagination does not appear.

What am I doing wrong ?

**Comment by crftwrk** [comment]
Pagination and amount of posts is a pluggable function and you can simply override this. Delete your snippet and add following to your child's `functions.php`:

```php
function wpsites_query($query) {
  if ($query->is_archive() && $query->is_main_query() && !is_admin()) {
    $query->set('posts_per_page', 6);
  }
}
add_action('pre_get_posts', 'wpsites_query');
```

Now pagination is shown after 6 posts. Check this issue https://github.com/bootscore/bootscore/issues/38 as well.

Solved?

**Comment by neerbappoo** [comment]
@crftwrk See in my $arg `'post_type'     => 'blog',`
This is a custom post type.

**Comment by crftwrk** [comment]
Pagination is for all post types in archives.

**Comment by neerbappoo** [comment]
I see, in that case, how would I use the archive-equal-height for a post type name "blog"?

**Comment by crftwrk** [comment]
Copy `archive-equal-height` to your child root folder and rename it `archive.php`.

https://bootscore.me/documentation/category-archive-author-templates/

**Comment by crftwrk** [comment]
Haven't heard anything here for a while. Close the issue now.
