### ISSUE TITLE
Pagination function won't detect first page? Fix

### ISSUE THREAD

**Issue by cdsaenz** [bootscore/bootscore#146]
First thanks, Bootscore is fabulous. 
This is a minor nitpick. I'm using a heavily modified theme (lots of rules rewriting) so I'm not sure if it's me or not:

- When a "paged" list of woo products is first shown (first page) the link for page 1 is not marked active.
- When navigating to the page 2 link it works fine.
- Apparently, the problem occurs when there's no page parameter as in the first page - and what fixed it for me is the added line below to set the page number to 1 when not in the url.

Hope it helps somebody else, in case it's not my site's problem :) 

```php
function bootscore_pagination($pages = '', $range = 2) {
    $showitems = ($range * 2) + 1;
    global $paged;
    // added line
    if(empty($paged)) $paged = 1;
    if ($pages == '') {
      global $wp_query;
      $pages = $wp_query->max_num_pages;

      if (!$pages)
        $pages = 1;
    }
```

**Comment by cdsaenz** [comment]
Oh you're right this is for all sorts of pagination.  I'd love to contribute but I never learned how to create a PR.. Old School guy :D just know the commit/push commands!

**Comment by crftwrk** [comment]
Creating a PR is super simple. Just fork the theme, change the code and then press the pull request button. Less than 2 minutes ;-)

**Comment by cdsaenz** [comment]
Thanks for the help! I forked, edited the code in the browser and commited to a new branch in my fork (cdsaenz-pagination-pagenumber). Then created the pull request at https://github.com/cdsaenz/bootscore/pull/1
Hope it's alright. What's the next step? You take it from there?

**Comment by justinkruit** [comment]
Almost right, you need to make the pull request to this repository, not your own fork. 😉

**Comment by crftwrk** [comment]
You are always welcome.
