### ISSUE TITLE
Single product and product archive sidebar

### ISSUE THREAD

**Issue by mrky007** [bootscore/bootscore#150]
What would be the correct was to setup the following:
1. Product archive has sidebar
2. Single product has no sidebar

**Comment by crftwrk** [comment]
- Install Widget Context plugin https://wordpress.org/plugins/widget-context/
- In widget settings choose "Show widget on selected"
- Choose "Archive of "Products" posts"

Solved?

**Comment by mrky007** [comment]
This isn't about widget hiding. It's about product archives having a sidebar and single product template not having a sidebar.

**Comment by crftwrk** [comment]
> This isn't about widget hiding. It's about product archives having a sidebar and single product template not having a sidebar.

The sidebar in WooCommerce pages is dynamic. If no sidebar widget is active then the sidebar is hidden and content takes 100% width. So, you have to show the widgets only in archive pages and hide them in product pages. 

Doing it like described in my previous comment is exactly the result what you want to do.

**Comment by mrky007** [comment]
And it works perfectly, just tried it. Thanks for the help I thought that there is some theme specific step to do for that.

**Comment by crftwrk** [comment]
You're welcome 👍

> I thought that there is some theme specific step to do for that.

All shop pages uses `woocommerce.php`, it's not possible to select different templates there. Only way is to show or hide sidebar widgets.
