### ISSUE TITLE
Woocommerce template hierarcy and myaccount navigation.php

### ISSUE THREAD

**Issue by seanvandermolen** [bootscore/bootscore#152]
I have a woocommerce folder in my bootcommerce child theme.  I wanted to customize the myaccount navigation so I created the myaccount subfolder and copied the navigation.php but it would not apply.  I finally edited the navigation.php file in the bootscore-main theme directory and it did what I wanted.

This should work, or is there something that I'm missing?

![image](https://user-images.githubusercontent.com/7504775/166970152-76f1679e-de81-4a71-8a57-d4007818a7b3.png)

**Comment by crftwrk** [comment]
Transferred this issue to main theme. We do all issues regarding to child themes there.

There are two navigations. `navigation.php` is the navigation which you see in your dashboard. The offcanvas navigation is located in `woocommerce/myaccount/my-account-offcanvas.php` in line 25. So, you have to do changes in this file as well.

But `my-account-offcanvas.php` is not a WC file, it is an own file, and you can't easily override that file by saving a copy of it in child. To override this file you need to register it in your `header.php`. Check here https://github.com/bootscore/bootscore/issues/61 how to override `my-offcanvas-account.php`.

Solved?

**Comment by crftwrk** [comment]
Haven't heard anything here for a while. Close the issue now.
