### ISSUE TITLE
Header modal

### ISSUE THREAD

**Issue by as-miller** [bootscore/bootscore#156]
I want a button that would trigger a modal window for a contact form. Just using basic modal example from Bootstrap 5 docs. When modal comes up, the whole screen is greyed out and the page needs to be refreshed to proceed. Example image is attached. Using header.php file in the bootScore child theme. What am I missing?

Thanks.
<img width="1237" alt="Screen Shot 2022-05-18 at 6 24 13 PM" src="https://user-images.githubusercontent.com/10378244/169165977-85343cbd-4eaf-44af-8bb3-299162db5f7e.png">

**Comment by crftwrk** [comment]
It seems that you placed the modal inside the `<div class="fixed-top bg-light">`. Scroll down to the bottom of the `header.php` and insert modal before the closing `</header>` tag. Trigger button can be placed in navbar.

```html
      </div><!-- .fixed-top .bg-light -->
        <!-- insert modal here -->
    </header><!-- #masthead -->
```

Solved?

**Comment by as-miller** [comment]
Solved, thank you!
