### ISSUE TITLE
Google Fonts Documentation

### ISSUE THREAD

**Issue by iwasthesword** [bootscore/bootscore#164]
I was setting up some fonts and noticed the docs are a bit outdated. (Sorry if this is not the right place to report this)
Since the scss files moved it's not necessary to adjust the path to `../../fonts` and the default `../fonts/` from google-webfonts-helper would work. Also the snippet include the wrong path.

**Comment by crftwrk** [comment]
Nice catch! Google fonts docs are for the official 5.1.3.x releases. You are using the latest main (5.2.0.0) branch where the scss structure has been changed. But is not official released yet.

Docs for 5.2.0 are already rewritten, but not published yet. There are some more points in the docs that have changed.

**Comment by crftwrk** [comment]
Closed by 5.2.0.0 release https://bootscore.me/documentation/google-fonts/ 👍
