### ISSUE TITLE
please show as video or tutorial 

### ISSUE THREAD

**Issue by vahidalvandi** [bootscore/bootscore#169]
please show as video or tutorial for run and create new theme with sass support

**Comment by crftwrk** [comment]
Yes, video tutorials would be nice. Unfortunately nobody of us has the time to do this. So, maybe a user wants to contribute and create some vids (you want?).

But theme is well documented. For your question about Sass check here https://bootscore.me/documentation/theme/bootstrap-css-sass/ (Short video as well).

In conclusion there are two files in your child-theme's `scss` folder:

- `_bscore_variables.scss` Add Bootstrap Sass variables here 
- `_bscore_custom.scss` Add usual CSS or SCSS syntax here

Save files and reload your page. Files compiles automatically by scssphp. Nothing more to do.

Does this help?

**Comment by vahidalvandi** [comment]
how i can and run saas compiler ?

**Comment by crftwrk** [comment]
> Save files and reload your page. Files compiles automatically by scssphp. Nothing more to do.

Compiler runs by itself.

**Comment by crftwrk** [comment]
> dont need install or run or watch any service for php sass?

No. Please just do it like I described above.
