### ISSUE TITLE
Move archive-*.php, author-*.php and category-*.php templates out of the theme into a separate repo

### ISSUE THREAD

**Issue by crftwrk** [bootscore/bootscore#172]
All files are very useful but „dead“ files until you are copy them to your child and start renaming. The idea behind this issue is to keep only archive.php in theme and move all other templates to a separate repo. Users can download them and cherrypick which one they want to use.

- It‘s not possible to select them in the backend
- archive.php works for category and author too
- If an user want  to have a separate category.php, just copy it to your child
- This will remove 15 files in the theme root folder. 
- It‘s maybe more clear that child-theme can be extended by this templates.

What do you think?

**Comment by rolzav** [comment]
II think it's a great idea. Personally, I vote +

**Comment by rolzav** [comment]
I think it's a great idea. Personally, I vote + for it

**Comment by justinkruit** [comment]
I was kinda hesitant, but one of my biggest annoyance of bootScore is that the files feel kinda cluttered, and this would definitely clean it up. We just have to decide what is gonna be the "main" look of bootScore.

**Comment by crftwrk** [comment]
In v4 version, there was a cookie banner and even the preloader part of the theme. They went out step by step into plugins and since v5 I try to clean up the repo step-by-step again by reorganising the folders, files, renaming etc. without disturbing users too much. So, in my opinion the theme itself should be "bare" and clean but heavy extendable by additional files and plugins.

| Before  | After |
| ------------- | ------------- |
| ![before](https://user-images.githubusercontent.com/51531217/173632454-5571efda-8084-4cb7-9bb0-5d37f3b377a8.png)  | ![after](https://user-images.githubusercontent.com/51531217/173632529-b722d373-3dcd-491f-95df-70d5dfa0ad79.png)  |

**Comment by justinkruit** [comment]
A thing I have in my own theme, is everything separated in template-parts in subfolders. So for example, for posts I gave /template-parts/post/post-single.php. Maybe something like that using subfolders would be nice? It would remove the need of folders like page-templates.

**Comment by crftwrk** [comment]
I‘m absolutely in. But can they be overriden in child by storing a copy of the file there?

**Comment by justinkruit** [comment]
I know you removed your question, but I checked anyway. As long as you use `get_template_part()`, it will check the child theme first.

**Comment by crftwrk** [comment]
https://github.com/bootscore/bs-loop-templates

> As long as you use get_template_part(), it will check the child theme first.

Yes, maybe I asked wrong. Better: Does this have any affect on existing child-theme installations? If so, is there a way to check theme's root folder first and if there file do not exists then check subfolder?

I'm definitely open for improvements.
