### ISSUE TITLE
Redifine scss output and input paths in child theme?

### ISSUE THREAD

**Issue by alexut** [bootscore/bootscore#173]
I have a previously bootstrap site and I would like to adapt it to bootscore. Is there any way I can redefine the paths for scss compilation to my old structure?

**Comment by iwasthesword** [comment]
You can probably tweak [/inc/scss-compiler.php](https://github.com/bootscore/bootscore/blob/main/inc/scss-compiler.php) to your needs. Might need to take a look at the ScssPhp docs to help you figure it out

**Comment by alexut** [comment]
@crftwrk basically I use gulp with browser-sync to develop the themes I make, all my past year workflow is based on that. I use gulp to render the pages in HTML and automatically import them as pages in WordPress. All the resources my themes are using are in the assets folder. I love your theme and plan to work with it rather than reinvent the wheel each time I develop a new theme. I would scrap the scss compiler altogether but it's sometimes useful to have a quick scss editor. If it's something that can be solved without too much hassle then great, if not I will see what I can do. Thanks !

**Comment by crftwrk** [comment]
Understand, you want disable scssphp completely and use gulp instead, right?

**Comment by alexut** [comment]
Not looking to disable it, sorry, it's true I'm not using it during development, but it would be good if I can just redefine the scss compilation paths when pushing the site on the live server - so if the client wants subsequent changes I can do them directly on the site. Again, if this is too much of a hassle I'll just skip it completely.

**Comment by crftwrk** [comment]
Lets try this:

1. Download https://github.com/bootscore/bootscore/archive/refs/heads/pluggable-scssphp.zip, unzip, rename to `bootscore-main.zip`, zip again and upload.
2. Create folder `inc` in child and copy file `scss-compiler.php` from main-theme to it.
3. Open `scss-compiler.php` in child and replace in line 9 `require_once "scssphp/scss.inc.php";` with `require_once(get_template_directory() . '/inc/scssphp/scss.inc.php');`
4. Override compiler in child's `function.php`
```php
  function register_scssphp() {
    // Register scssphp
    require_once('inc/scss-compiler.php');
  }
```
5. Edith paths in `scss-compiler.php` and enqueue styles in `functions.php` lines 11 and 12

Tested and works. Let me know if that's what you need. So maybe we can do a PR.

**Comment by crftwrk** [comment]
Haven't heard anything here for a while. Close the issue now.
