### ISSUE TITLE
"Variable undefined", when trying to merge color maps

### ISSUE THREAD

**Issue by anyway** [bootscore/bootscore#175]
Hi,

first of all... thanks for sharing such a great theme!

My issue is... I want to add a custom color to the bootstrap color map in `_bscore_variables.scss` and I am using the following code::

```
$custom-colors: (
    "nbk-red": #8d2717
);
$theme-colors: map-merge($theme-colors, $custom-colors);
```

But this does not seem to work. My compiler drops "Undefined variable". When I put the code at the end of `/bootstrap/_variables.scss`, it works.

Is that not supported in your theme, or am I doing something wrong? I'm working directly inside the theme, without a child-theme. Of course I can solve this somehow differently, but wanted to stick to the bootstrap standards in this case.

**Comment by anyway** [comment]
Ah okay... I did not know these correlations yet, thank you for the clarification.

**Comment by justinkruit** [comment]
No problem! I spend like half an hour myself to figure this out a few months ago 😂

**Comment by anyway** [comment]
Well then it is good that you already had the answer in the drawer ;-)
