### ISSUE TITLE
Child theme not compiling SCSS

### ISSUE THREAD

**Issue by BHWWills** [bootscore/bootscore#178]
When I edit _bscore_variables.scss in the main theme it works, but when I do it in the child it doesn’t seem to compile?

**Comment by crftwrk** [comment]
This has nothing to do with child, it seems that your server stops compiling for whatever reason.

Try to force scss compile when environment is development. Add following snippet to `wp-config.php`:

```php
/* Dev mode to force recompile scss and add source map */
define('WP_ENVIRONMENT_TYPE', 'development');
```

This will slow down your page because compiler starts on every pageload. So, delete this line when development is finished.

Does this help?

**Comment by BHWWills** [comment]
Now I get this error: Warning: filemtime(): stat failed for /Users/BHWW/Sites/localhost/breakthrough/wp-content/themes/bootscore-child-main/css/main.css in /Users/BHWW/Sites/localhost/breakthrough/wp-content/themes/bootscore-child-main/functions.php on line 11

**Comment by crftwrk** [comment]
Please share a link to your site. There seems something on your host what theme does not like.

**Comment by BHWWills** [comment]
I’m running a local MAMP site to test everything out?

**Comment by crftwrk** [comment]
> I’m running a local MAMP site to test everything out?

Yes, and that seems to be the issue. Please transfer to a public server. Usually this will work fine. If not we can check it there. 

https://bootscore.me/documentation/support-contribute/

**Comment by crftwrk** [comment]
Why you use variables in both themes? Use them just in child. BTW I‘m using Mamp on Mac too without any problems, but some users reported errors with theme on their local machine. So, maybe check your Mamp settings?

**Comment by crftwrk** [comment]
Ah ok ;-) You can use 5.2.0 beta, but you must download child 5.2.0 here from GitHub as well because paths changed.

**Comment by vahidalvandi** [comment]
i have same problem , it work in parent scss but not work in child theme 
why?

**Comment by vahidalvandi** [comment]
i download master branch parent work fine. 
please relase new tag 

https://github.com/bootscore/bootscore/releases/tag/5.1.3.2

**Comment by vahidalvandi** [comment]
how i can disable in production version

**Comment by vahidalvandi** [comment]
please add configureable in wp-confing.php if 
 
`define('WP_ENVIRONMENT_TYPE', 'development'); 
` active but in 
`define('WP_ENVIRONMENT_TYPE', 'production'); ` disable automaticaly

**Comment by crftwrk** [comment]
Please open a new issue for this and describe detailed what should be the benefit of it. So, we can discuss and solve it there.

**Comment by justinkruit** [comment]
It only compiles when the scss files are newer than the css files, or when the environment is set to development. So if you don't modify the scss files, it won't compile.
