### ISSUE TITLE
How to change the excerpt length

### ISSUE THREAD

**Issue by avdsm** [bootscore/bootscore#179]
Tell me please! How and where can I change the number of words in the short description of blog categories?

**Comment by crftwrk** [comment]
Use filter to customize the excerpt:

```php
// Excerpt length
function bootscore_excerpt_length( $length ) {
  return 50;
}
add_filter( 'excerpt_length', 'bootscore_excerpt_length' );
```

Snippet goes to `functions.php`. Change `50` to how many words you want to show.

**Comment by avdsm** [comment]
Thanks

**Comment by crftwrk** [comment]
You're welcome 👍
