### ISSUE TITLE
Disable scssphp in wp-config.php

### ISSUE THREAD

**Issue by vahidalvandi** [bootscore/bootscore#180]
for incrase performance and disable php scss in function.php and Avoid interfering with versions of the on-site and local control versions for remove two line  
```
 require_once 'inc/scss-compiler.php';
  bootscore_compile_scss();
```
 I suggest that php scss work with bellow config 
`define('WP_ENVIRONMENT_TYPE', 'development'); `active but in
`define('WP_ENVIRONMENT_TYPE', 'production'); `disable automatically

**Comment by crftwrk** [comment]
This seems to be a good idea, because some users asked already for that and want to use other tools. @justinkruit any idea?

**Comment by vahidalvandi** [comment]
i waill create PR please accpet it

**Comment by justinkruit** [comment]
I don't think production mode should completely disable the compiler. A separate option for that would be better.

**Comment by vahidalvandi** [comment]
need a standard option for disable phpscss in production for incrase speed and optimize ram , cpu

**Comment by justinkruit** [comment]
What do you mean?

**Comment by vahidalvandi** [comment]
Where does the specified source compile only changes in the production state?

**Comment by justinkruit** [comment]
Please explain further what you mean, instead of just copying the exact same text.

**Comment by crftwrk** [comment]
You can now disable scssphp and use gulp or anything else to compile rtl CSS https://github.com/bootscore/bootscore/pull/375.
