### ISSUE TITLE
Auto update?

### ISSUE THREAD

**Issue by vahidalvandi** [bootscore/bootscore#182]
Do this theme support auto update ?

**Comment by crftwrk** [comment]
Not yet, because we still doing some breaking changes. When there are absolutely no breaking changes anymore, we can add an auto updater. Maybe 5.3.0.0.

**Comment by vahidalvandi** [comment]
Thank you

**Comment by crftwrk** [comment]
Discussed here https://github.com/bootscore/bootscore/issues/30
