### ISSUE TITLE
bS Contact Form 7

### ISSUE THREAD

**Issue by avdsm** [bootscore/bootscore#185]
Good afternoon
Installed the feedback plugin on the page https://vosmarket.am/contacts/.
Letters arrive, however on a file place I receive only its name. The file itself does not exist.
Please tell me how to do to get the file?
It is desirable not only an image, but also a ZIP archive.

**Comment by justinkruit** [comment]
Does this work correctly with other themes? Because this feels like a CF7 config error instead of a bootScore error.

**Comment by avdsm** [comment]
I'm sorry, everything is working fine.
I just put it in the wrong place
[file-388]

**Comment by justinkruit** [comment]
Good to hear everything is working fine 👍
