### ISSUE TITLE
Problems compiling scss

### ISSUE THREAD

**Issue by ucalegonte** [bootscore/bootscore#186]
I am new to the project, but after following the guide for installing this theme and its parent, I noticed that the customizations placed in the child's scss files (_bscore_custom.scss and _bscore_variables.scss) seem not being compiled or otherwise completely ignored.

**Comment by crftwrk** [comment]
It seems that your project stops auto compile for whatever reason. Activate the dev mode by adding following snippet to `wp-config.php`:

```php
/* Dev mode to force recompile scss and add source map */
define('WP_ENVIRONMENT_TYPE', 'development');
```

Theme compiles now on every pageload. This will slow down the loading time. So, delete snippet when you are finished.

Same here
- https://github.com/bootscore/bootscore/issues/21
- https://github.com/bootscore/bootscore/issues/178
- https://github.com/bootscore/bootscore/issues/177

Solved?

**Comment by ucalegonte** [comment]
Solved, thanks.
I downloaded the version from https://bootscore.me/ and everything worked immediately.
