### ISSUE TITLE
Refactor offcanvas cart

### ISSUE THREAD

**Issue by crftwrk** [bootscore/bootscore#215]
Idea from @Axos11

Branch: https://github.com/bootscore/bootscore/tree/Refactor-offcanvas-cart

- [x] Add success/danger alert to offcanvas in product pages https://github.com/bootscore/bootscore/commit/048b8845dc6f6f668edee98998a73bfa4ca99493
- [x] Open offcanvas **after** success/failed product added to cart https://github.com/bootscore/bootscore/commit/1c846028ac3b86a2c7e118139b07096cbb4dcd8a
- [x] Exclude affiliate products from Ajax https://github.com/bootscore/bootscore/commit/2ab3689fe267376bff5a07d460d5d60758602d7d
- [x] Add loading spinner to `add_to_cart_button` https://github.com/bootscore/bootscore/commit/16cf2a9e84a46329f13d3bd3b10ba6cf09fd8139
- [x] Add success/danger alert to offcanvas in archive pages https://github.com/bootscore/bootscore/commit/086330dc6bb5be56bc6eaec1e8bc0feff2ebc53c
- [x] Remove cart-loader https://github.com/bootscore/bootscore/commit/9d9e06c2aea12d0011abbf848d7858854c751052,  https://github.com/bootscore/bootscore/commit/27976fbea0600bd5c7c6f6a475d85be09f798bb3
- [x] Move all ajax cart based scripts to `ajax-add-to-cart.php`. Ajax function can be disabled by adding empty function to child https://github.com/bootscore/bootscore/commit/96ccea202cc65f57057d9822bc52660a0726c52d
- [x] Improve button loader https://github.com/bootscore/bootscore/commit/e2d6289a05088b33242f1834b5eff645e6720c70
- [x] ~~Create stretched link for out of stock products to prevent click Read more button https://github.com/bootscore/bootscore/commit/a33ca0ba96a4ac70539c89a07d5143aaf748082c~~
- [x] Hide `.btn-loader` in `.single_add_to_cart_button.disabled` variable product (refactor btn loader) https://github.com/bootscore/bootscore/commit/605263d4e3b67412072a01715a1c60ef7ffdc4c8
- [x] ~~Add `title` to `single_add_to_cart_button` in loop https://github.com/bootscore/bootscore/commit/598d1f1b4454f8826985a7c2210568bd5a814fe1~~ Revert https://github.com/bootscore/bootscore/commit/598d1f1b4454f8826985a7c2210568bd5a814fe1
- [x] Add product title to alert-danger https://github.com/bootscore/bootscore/commit/f201e3b9ec4aefccaad1e0269c31d6d100219306
- [x] Make alert strings translation-ready https://github.com/bootscore/bootscore/commit/58c8479841dc1663365ba120a63d30134e934f00
- [x] Fetch product title from button attribute instead of card https://github.com/bootscore/bootscore/commit/d4ce5030f606db4335de68a8bed55fa28bd16f40
- [x] Move back the ajax header minicart to woocommerce-functions.php https://github.com/bootscore/bootscore/commit/1e1ef2dac27efe25625a39ad44a1e36b703ab37b
- [x] Cleanup `ajax-add-to-cart.php` and `woocommerce.js` https://github.com/bootscore/bootscore/commit/bf7310184f0b9a1ebc72ba2b7aa50d24564abf5c
- [x] Rename `_wc_offcanvas_cart.scss` to `_wc_ajax_cart.scss` https://github.com/bootscore/bootscore/commit/9b7bd21932fc50bd7e2b94a1336724012edc6e20
- [x] Add German translation to offcanvas alerts https://github.com/bootscore/bootscore/commit/deab11f413a8df07dd2b6f703a68573e906dbe05
- [x] Fix empty cart on browser back button https://github.com/bootscore/bootscore/pull/329/commits/e8bea45eb8c2c54694ae7fb4933118e4a16c92cb

Maybe fixes this
- https://github.com/bootscore/bootscore/issues/200#issuecomment-1206965794
- https://github.com/bootscore/bootscore/pull/205
- https://github.com/bootscore/bootscore/pull/209
- https://github.com/bootscore/bootscore/issues/319
- https://github.com/bootscore/bootscore/issues/277

**Comment by justinkruit** [comment]
For the opening after adding to cart, we could potentially use the `added_to_cart` js trigger WC sends. Haven't used it before, so not completely sure if it'll do what we want tho
