### ISSUE TITLE
SCSS complier doesn't add the news SCSS rules

### ISSUE THREAD

**Issue by Zazou49** [bootscore/bootscore#219]
Hello,

I'm still learning a lot with SASS / SCSS but I noticed since yesterday evening that the code I add in `_bscore_custom.scss` and `_bscore_variables.scss` is not taken into account by the compiler. I mean that there is no trace of the code on the site. The compilation seems to be done correctly since there is no error message displayed. 

Only alternative I've found is to add the CSS code directly to style.css

Can I find the compiler logs somewhere? I admit I don't really understand why it goes wrong.

**Comment by crftwrk** [comment]
Hi,

use the developer mode when scssphp stops working for whatever reason.

- https://github.com/bootscore/bootscore/issues/85#issuecomment-1028871089
- https://bootscore.me/documentation/theme/bootstrap-css-sass/#Developer_mode

This will slow down your pageload, delete it when finished.

**Comment by Zazou49** [comment]
Hello Basti,
I enabled the developer mode, loaded 3-4 pages but it doesn't seem to have changed anything, I still don't see the changes.

**Comment by Zazou49** [comment]
How many times it takes to regenerate the map files ? On local, I loaded few posts and disabled the option. 

On Live, I loaded 10 pages, waited 2-3 mins and still missing the map file.

**Comment by crftwrk** [comment]
Just one pageload, a link to your project would be very helpfull.

**Comment by Zazou49** [comment]
Sure, I sent you a message on https://bootscore.me/

**Comment by crftwrk** [comment]
I see, you do not have dev mode enabled? Please add this snippet to `wp-config.php`:

```php
/* Dev mode to force recompile scss and add source map */
define('WP_ENVIRONMENT_TYPE', 'development');
```

scssphp will now recompile on every page load, no matter if you have changed something in a scss file or not.

**Comment by Zazou49** [comment]
Hello,
Yes of course, I added the code and loaded a page. I removed it afterwards to avoid the production site being slow for several hours.

I tried again this morning, the map file is not created and the main.css file is not updated. (While the page is loading much longer so I think in the background the compiler did its job).

**Comment by crftwrk** [comment]
The map file is only created when dev mode is enabled, but dev mode forces recompile on every page load as well. So, enable dev mode, do your changes in scss files and reload page.  When development is finished, delete dev snippet again for better performance. Dev mode is useful if scssphp stops working for whatever reason, which is exactly your case.

**Comment by Zazou49** [comment]
Yes I understand, that's exactly what I did. I don't understand why it still doesn't work. 

- enable dev mode with the snippet
- made a modification in a scss file
- load a page
- disable the dev mode

**Comment by crftwrk** [comment]
@justinkruit ?

**Comment by justinkruit** [comment]
Hmm, this looks like a weird case. Would you mind providing me with an admin account and ftp details to take a deep look at this problem? This doesn't look like something I can easily replicate.

**Comment by Zazou49** [comment]
Hello,
Thank you @justinkruit, I need to contact my server administrator to clone the site for the sandbox. It may takes few days.

**Comment by crftwrk** [comment]
Closed as duplicate 

- https://github.com/bootscore/bootscore/issues/228
- https://github.com/bootscore/bootscore/issues/186
- https://github.com/bootscore/bootscore/issues/178
- https://github.com/bootscore/bootscore/issues/177
- https://github.com/bootscore/bootscore/issues/85
- https://github.com/bootscore/bootscore/issues/21
