### ISSUE TITLE
Anchor linking doesn't work in offcanvas menu with smooth scrolling

### ISSUE THREAD

**Issue by iwasthesword** [bootscore/bootscore#227]
Menu items linking to anchors dont work correctly with the offcanvas and smooth scrolling. When clicking in a anchor link on offcanvas menu it will go half-way to the destination and then stop as soon as the offcanvas closes. Disabling smooth scrolling (`$enable-smooth-scroll: false;`) fix this. Any idea how to fix this without disabling smooth scrolling?

How to replicate:

1. Create new site
2. Add page `page` with big spacers and anchor `test` at the end
3. Add menu item targeting the anchor "test" eg: `/page/#test`
4. Access page in mobile mode and try clicking the menu item

**Comment by crftwrk** [comment]
This is a known issue regarding to Chrome/Edge and Offcanvas https://github.com/twbs/bootstrap/issues/36681. Using Collapse navbar instead Offcanvas should solve this.

**Comment by crftwrk** [comment]
This seems to be fixed in both browsers.
