### ISSUE TITLE
SCSS stopped compiling in BootScore Child theme

### ISSUE THREAD

**Issue by peteoa12** [bootscore/bootscore#228]
It worked great for a while and then just stopped all of the sudden. I checked for PHP errors, made sure main.scss was still being enqueued, and other known issues. It is not compiling the scss to main.css anymore on save. I am not getting any errors.

**Comment by peteoa12** [comment]
It worked great for a while and then just stopped all of the sudden. I checked for PHP errors, made sure main.scss was still being enqueued, and other known issues. It is not compiling the scss to main.css anymore on save. I am not getting any errors.

**Comment by crftwrk** [comment]
Add this to `wp-config.php`:

```php
/* Dev mode to force recompile scss and add source map */
define('WP_ENVIRONMENT_TYPE', 'development');
```

https://bootscore.me/documentation/theme/bootstrap-css-sass/#Developer_mode
