### ISSUE TITLE
FontAwesome SCSS instead of default CSS

### ISSUE THREAD

**Issue by androidacy-user** [bootscore/bootscore#234]
Not all sites need the massive entire FontAwesome css library, but bootScore includes it.

We'd like to see the FontAwesome SCSS included instead for maximum customization (and so we don't have to mess around with fighting to dequeue the default file and including the SCSS ourselves).

**Comment by crftwrk** [comment]
Check https://github.com/bootscore/bootscore/issues/46 for some general thoughts about icons.

Read https://github.com/bootscore/bootscore/pull/160 why FontAwesome is not included in SCSS.

If you have any idea how to improve FA handling, you're welcome to open a PR.
