### ISSUE TITLE
Compiling SCSS takes +30s

### ISSUE THREAD

**Issue by madshostrup** [bootscore/bootscore#252]
When adding custom styling to _bscore_custom.scss and reloads the page it takes 31,6 seconds for it to load. When refreshing after that it refreshes instantly. I'n not sure it's an issue or just the way it should be, but it's a bit too long to wait for when you want to see the styling changes you are doing.

**Comment by crftwrk** [comment]
Of course, it needs some time to compile SCSS files, but 31,6 seconds seems too long. The speed for compiling depends on your server and PHP settings. Please try another server and/or update PHP version to latest.

**Comment by madshostrup** [comment]
Just tried to change server and update to PHP 8. It's a bit faster but still takes longer than I like. 
Would it be an idea to include bootstrap in another file, so it doesn't need to compile every time there are custom changes?

**Comment by crftwrk** [comment]
We need compiler to use the power of Sass and edit Bootstrap correctly. Variables and mixins won't work with a precompiled Bootstrap. Adding source and compiler to the theme was a huge milestone for us as well. So, we do not change this.

But I agree that 30 seconds is much too long. Usually it should take 3-5 seconds. Here https://dev.bootscore.me/ is the dev_mode activated, means that theme compiles on every page load again. As you see, it's much faster. It's not the compiler itself that takes long time, it's the server.

**Comment by justinkruit** [comment]
Well technically it can be made that Bootstrap and your own code can compile separately, but then things like `@extend` won't work anymore. So to keep most functionality the current system is the best.

**Comment by sean-au** [comment]
Is it possible to pre-compile bootstrap on the parent theme, and use a npm package to compile the scss files quickly?

The only downside is won't work if developing via ftp

**Comment by NeaMitika** [comment]
I have the problem that it compiles on every reload... it doesnt matter if i have modified any scss.... i am using LocalWP and i have tried to add 

define('WP_ENVIRONMENT_TYPE', 'production');

Nothing changed... i dont know if it is an error with LocalWP or Bootscore

And another issue it is that it seems the theme doesnt work with the latest php version (this could be a problem with LocalWp too not sure)

**Comment by justinkruit** [comment]
From my experiments with LocalWP, it always overrides the environment and sets it to `local`, even when adding a line to the wp-config.php.

Quickly googled it, and it indeed is preset by Local: https://localwp.com/help-docs/advanced/using-wp_get_environment_type-to-code-for-different-environments/ _"How to change the WP_ENVIRONMENT_TYPE of a Local site"_

**Comment by NeaMitika** [comment]
Yep 100% LocalWP conflict, i switched to Xampp and it works fine, thanks for the FLASH response

**Comment by crftwrk** [comment]
https://github.com/bootscore/bootscore/pull/375 solves this issue.
