### ISSUE TITLE
bootscore-main 5.2.0.1 breaks bootscore-bootcommerce

### ISSUE THREAD

**Issue by bamhost** [bootscore/bootscore#257]
I have wordpress 6.0.2

I use the bootscore-main theme with the bootcommerce-child theme with no modifications other than in the functions.php file. I updated from bootscore-main 5.2.0.0 to bootscore-main 5.2.1.0. 

After the update, inside the WP Dashboard, a notice appeared as follows:
"Your theme (bootCommerce Child) contains outdated copies of some WooCommerce template files. These files may need updating to ensure they are compatible with the current version of WooCommerce."

And the frontend of my website is broken with an internal 500 server error.

I removed the only file I modified, which is the functions.php file, the error is still there. I switched my theme to the bootscore-main theme, both the 500 error and the notice in the dashboard disappeared, so clearly the issue is with the bootcommerce-child theme.

On the bootscore website, the update for bootscore-main states:
"There are no breaking changes. If you are using bootScore 5.2.0.0, simply [download](https://bootscore.me/#download) and update theme via the WordPress theme-uploader."

I went back to the bootscore website to download the latest bootcommerce-child theme, only to find there is no update. My site is running the latest version 5.2.0.0 I've looked everywhere for a list of file changes thinking I might be able to troubleshoot the issue, but all I found is a changelog that is of no help whatsoever.

I'm so happy that I have not brought my clients website live yet, this would have been a complete disaster.

Updating the bootscore-main theme itself is not idea. Even though I'm using the bootcommerce-child theme, to update bootscore-main, you literally have to activate the bootscore-main theme, update it, and then re-enable the child theme and then update it. This process seems quite messed up since you literally have to break your or your clients website in order to update. What's even more disturbing is to do this and complete updates, only to find that the website is broken.

What do I need to do to get the bootcommerce-child theme working again? On your test site all you need to do is enable the bootcommerce-child theme to see the errors.

Thank you for any help.

**Comment by crftwrk** [comment]
Hi,

as you mentioned, update from 5.2.0.0 to 5.2.1.0 doesn‘t break anything.

500 error is a server error. That means that your server is (temporary) out of service. This has nothing to do with theme or update.

About the WC file. Latest WooCommerce with this template file change arrived yesterday. You should give us a few days to react. However, change in WC template is only the version number and not any code. We decided to ship this with 5.2.2.0 update. Please check here why https://github.com/bootscore/bootscore/pull/255

**Comment by justinkruit** [comment]
The 500 error could actually be from the theme if there is a big php error. If you really think it's because of the theme, you could replicate the error and send the error log from your php.

**Comment by crftwrk** [comment]
You can try to downgrade to 5.2.0.0 https://github.com/bootscore/bootscore/releases/download/v5.2.0.0/bootscore-main.zip and check if that helps, but I‘m pretty shure that it is not the theme, because we did not made any significant changes.

**Comment by bamhost** [comment]
Hello Basti,

I've got the site setup on 2 separate hosting accounts, and only have one of them upgraded while I troubleshoot this. Additionally, I always run backups before any updates so that I can quickly restore.

I'm pulling the php error log now. I should have looked at that before I did anything...long night.

I'll post back.

**Comment by bamhost** [comment]
Can someone tell me where this line of code comes from?: <?php bootscore_ie_alert(); ?>

That's the line of code that caused the internal server error. As soon as I removed it from the header.php file, the error disappeared.

I'm getting ready to start going through all of my bootscore backups to find the earliest install that has that line of code, but thought I would ask here.

**Comment by justinkruit** [comment]
Ahh, I see. This change has been made in bootScrore 5.2.0.0, mentioned here: https://bootscore.me/blog/bootstrap/bootscore-5-2-0-0/#Internet_Explorer_Alert

It's a deprecated piece of code, and in the latest update it has been removed.

**Comment by crftwrk** [comment]
Yes, you have to remove this. In 5.2.0.0 we changed the Ie alert from PHP to js. We published a post in an earlier 5.1.x.x version that you should remove this, because we will remove empty function behind this hook in 5.2.0.0.

**Comment by bamhost** [comment]
Hello Justin & Basti,

Do you send out notices for important changes like this?...I'm positive that I received a notice that bootscore 5.2.1.0 was available so just thought I would ask if notices for important changes are sent out as well. 

Is there somewhere that we can go that literally lists changes? especially important ones like this? I realize you have it posted in your blog, but is there a page that list them?

Before finally posting this issue, I had clicked through every single link on github.com/bootscore thinking surely someone else had this same problem...because you know, usually you're not the only one getting an error. Finally I gave up and posted the issue in the bootcommerce section...and as you can tell from Basti moving my post, I posted it in the wrong place. lol

It would just be nice to be able to go to a page for important changes to be sure that we've made necessary changes before wasting everyone's time...like I've done today.

**Comment by justinkruit** [comment]
I totally agree with that this change maybe isn't clearly mentioned, and we'll improve on that! It's something we need to get a more streamlined process in, which we'll get over time I'm sure.

Yes, the outdated template file can be ignored for now, it's nothing drastic and we'll soon release a new version containing the new template file.

And you haven't wasted our times, we're here to help 😁

**Comment by crftwrk** [comment]
If there is a breaking change, we publish a post with instructions and send a newsletter. So, if you want to be updated it is a good choice to subscribe to the newsletter.

You wasted not our time, we are here to help and by this issue we decided quickly to readd empty IE function. All good.

> And just to be sure... In regards to the notice I am getting on the wp dashboard that the bootcommerce theme has outdated template files... although annoying, I can just ignore it?

Yes, you can ignore it. If you do not want to see this alert, go in main-theme to this file https://github.com/bootscore/bootscore/blob/main/woocommerce/myaccount/form-login.php and change in line 16 4.1.0 to 6.0.0. That‘s it ;-)

**Comment by bamhost** [comment]
Hello Basti,

I am signed up for the newsletter...that's why I received your notice that 5.2.1.0 was available.

Thank you for letting me know what file I can change to get rid of the notice on the dashboard.

Thank you both for your help!

**Comment by crftwrk** [comment]
👍 You're welcome

**Comment by crftwrk** [comment]
@bamhost there is a new release with fixes your points https://github.com/bootscore/bootscore/releases/tag/v5.2.1.1

Download main zip file in the release section or grab it from the site https://bootscore.me/#download and upload it via the theme uploader.

Thank you for pointing this out.

**Comment by bamhost** [comment]
Hello Justin & Basti,
While sleeping I kept going over the updates for the bootscore theme. Specifically the child themes, and this is just my thought and I don't know how difficult it would be for you to do. Because we all use child themes so that changes and customizations that we make are not overridden when updates are made to the parent theme. I was thinking that when updates need to be included in a child theme that perhaps rather than us having to download and install the entire child theme update and then have to re-apply our changes and customizations, it would be so much more time efficient if in addition to a link to download the entire child theme zip that includes the updates, if a link to a text file could be listed below the zip that only includes the specific changes?

Otherwise, what we would actually have to do is download the child theme update, unzip it, and then do a file compare between our current version, and the new version, to find the changes, just so that we don't have to re-apply our changes and customizations.

Anyways, this was just a thought. Feel free to remove this post...I just don't know any other way to communicate with you ;o)

**Comment by crftwrk** [comment]
All good, this here is the best place to communicate.

Since we added compiler and source in v5.1.1.1 we started a roadmap to refactor theme step-by-step. The end of this roadmap reached by v5.2.0.0. From this version there should be in my point of view no breaking changes and you do not must update your child anymore.

What we did in v5.2.1.0 is removing the empty IE alert function. You did not removed the hook as described in 5.2 blog and that‘s why your child crashed. Our mistake was to remove function too early, because we thought all users have removed this already. So, function is now readded and we‘ll keep it until v6. 

So, all should be go fine. If there is a bug with a users project, we‘re here to help. Most problems could be solved in minutes.

Does this clear it up?

**Comment by bamhost** [comment]
Hello All...I hope you are well and safe!

I'm upgrading the bootcommerce child theme and I feel hesitant and a little lost. I'm updating from 5.1.3.1 to 5.2.1.1 

When I do this, is the upgrade going to write over my existing bootcommerce child template which will force me to reformat everything?

If it does not write over my existing template, are there any changes between the 2 versions that may break something? lol..sorry to ask, like I said, I feel a little lost and hesitant after my last upgrade that you so kindly assisted me in fixing in this post.

Thank you for your time and help.

**Comment by crftwrk** [comment]
Hi,

yes, if you update child via theme uploader, then it will override your child. A child should be never be updated this way.

However, the main question is: Which version do you use in main-theme? If you use already 5.2.x.x, then there are no changes in child exept the version number.

**Comment by bamhost** [comment]
Hey guys,

With the last upgrade, since last week, I am getting the following notice for an out of date template file:

bootscore-main/woocommerce/global/quantity-input.php version 7.2.0 is out of date. The core version is 7.2.1,

I waited to contact you since the last time I posted before you had a chance to get all tmpl updated. 

Are there any actual changes to this file or just the version number?

Thank you for your help.

**Comment by crftwrk** [comment]
Hi,

this template is already updated and merged into the `main` branch. So, you can simply download and update theme here. 

WooCommerce goes wild since v6.9 and changes templates in every release and minor patch. To avoid to release a new version every two days, we decided waiting for WC 7.3 (template changes as well) release on January 10 https://developer.woocommerce.com/2022/12/27/woocommerce-7-3-beta-2/.

However using the outdated file does not affect your site functionality.

Hope that helps

**Comment by bamhost** [comment]
Hello, sorry to bother, but I pulled the file from the latest bootscore-main for the above mentioned quantity-input.php file, and now the quantity field is broken on single product pages across all browsers. Specifically the - and + signs have disappeared and now only a empty text box is there. There are no errors anywhere...inspecting the page or in the php logs, or woocommerce status page. I really don't want to post the url to the product detail page publicly here. Have you seen this issue yet?

And now I am getting:
bootscore-main/woocommerce/cart/cart-shipping.php version 3.6.0 is out of date. The core version is 7.3.0, 
I know you said you are waiting a bit to avoid releasing a new version every couple of days, I'm just concerned that this is related to the cart shipping, so thought I should check with you.

I'm finally bringing the customer's site live today and would hate for things not work when he logs in and starts testing things lolol

Thank you for any help.

**Comment by crftwrk** [comment]
Hi

First, an outdated Woo template isn't a bad thing and will always happen. Don't be stressed.

Second, `cart-shipping.php` was updated by WooCommerce 7.3 which was released yesterday and updated file is already merged https://github.com/bootscore/bootscore/pull/354. 7.3 is the version what we waited for and new bootScore with both updated templates will be released on Monday.

If you have questions about Woo templates and release cycle, I highly recommend to follow WooCommercer Developers on Twitter https://twitter.com/DevelopWC. There you get information about their scheduled releases and changed templates. To check which template is already updated here in bootScore, check the closed PR's https://github.com/bootscore/bootscore/pulls?q=is%3Apr+is%3Aclosed

Hope this clears it up

**Comment by bamhost** [comment]
Did you see where I stated the Quantity broke after updating? It's in the first paragraph of my post. My customer hasn't even logged in yet and has already mentioned that to me and asked me to put it back like it was with the - and + symbols.

I do realize that an outdated template isn't necessarily a bad thing...that's the first thing I learned about wordpress. What you do not understand is this customer of mine...he questions everything, and I mean everything. He has been using Joomla for over 10 years, moving him to wordpress is new to him and he is quite nervous about it...I'm just trying to be prepared to explain many things to him today...the notices being only one thing.

**Comment by crftwrk** [comment]
Please share a link to your site to check this

**Comment by bamhost** [comment]
is there any way I can provide the link to you privately? I'd rather not post it publicly.

**Comment by crftwrk** [comment]
mail it to store(at)bootscore.me

**Comment by crftwrk** [comment]
Got it. Are you sure that you updated this file https://github.com/bootscore/bootscore/blob/main/woocommerce/global/quantity-input.php correctly? It seems that this is the default Woo template on your site and not this from theme. 

However, just backup your site, then download and install  https://github.com/bootscore/bootscore/archive/refs/heads/main.zip, which is closed to the release on Monday. Clear cache and let me know when you have done this to check.

**Comment by bamhost** [comment]
Hello again, yes, it's me again.

I am having a problem with 3rd level submenus and their items not showing when the parent menu item is clicked. Just to be sure it wasn't a coding mistake on my end, I switched to the bootscore main them, and the issue is there as well.

I've slipped you an email with the url, so that you can see first hand, I also included a snapshot jpg that shows the problem, and also the html code for that parent menu item and its siblings.

In the header.php file, I have changed the depth to 3, but doesn't help anything. And when inspecting the html code the depth for the parent menu item is always set to 0. Not sure if this is what is breaking 3rd level submenus.

I've spent 2 days searching the web for help, to no avail. Thought maybe since you are more familiar with the bootcommerce template that you could point me in the direction I need to go.

Thank you for any guidance you can lend.

**Comment by crftwrk** [comment]
Check here https://github.com/orgs/bootscore/discussions/347 how to set menu to 3 levels.

Please open for new questions a new discussion or issue to keep things sorted. This issue is closed. 

Thank you

**Comment by bamhost** [comment]
you are awesome...your instructions fixed it in seconds.

Thank you so much!!!
