### ISSUE TITLE
Publish to packagist.org

### ISSUE THREAD

**Issue by sean-au** [bootscore/bootscore#262]
Hi and thanks for putting together such a great template. 

Are you able to publish to packagist.org? 

I am using bedrock to manage wordpress/themes/plugins via composer, and while I can require via git, it would be easier via packagist since you already have the composer.json file in place

**Comment by crftwrk** [comment]
@twosg can you help here out?

**Comment by twosg** [comment]
@crftwrk Its easy you simply need to submit it at https://packagist.org/packages/submit

**Comment by crftwrk** [comment]
https://packagist.org/packages/bootscore/bootscore
