### ISSUE TITLE
JSON-LD schema markup for SEO

### ISSUE THREAD

**Issue by sean-au** [bootscore/bootscore#264]
I am currently working on JSON-LD style (google's preferred format) schema markup in a child theme. 

I have started doing it, since Yoast SEO charges $89 a year for their woocommerce SEO plugin.

Is this something that should be put together in a PR for the main theme?

**Comment by crftwrk** [comment]
Yes, of course improvements are always welcome. I have currently no experience with JSON-LD, so can you provide an rough example how it works?

**Comment by justinkruit** [comment]
I don't think this would be fitting to put in the main theme as not everyone would want it possibly. Maybe this is a good idea for a separate plugin?

**Comment by sean-au** [comment]
Sure, I'll send more info when I get home.

Here is and example if you look in the head for <script
type="application/jsonld">

https://pureblueessentials.com.au/shop/bath-soak-cedar-and-frankincense-1kg/

It's not wordpress but I shared it because I coded everything from scratch

**Comment by crftwrk** [comment]
I agree @justinkruit, think this is something what users can do in child.
