### ISSUE TITLE
hello i have Woocommerce problem

### ISSUE THREAD

**Issue by AteS-Github** [bootscore/bootscore#268]
WooCommerce in wordpress update
  Install new version of theme on WooCommerce pages
  How do I install the new version without losing the changes I made on my old bootScore WooCommerce Child Theme?

**Comment by crftwrk** [comment]
If you have already updated to 5.2.0.0 you can simply update to 5.2.1.1.

If you are coming from 5.1.x.x, follow this steps to modify your child https://bootscore.me/blog/bootstrap/bootscore-5-2-0-0/.

**Comment by crftwrk** [comment]
Haven't heard anything here for a while. Close the issue now.
