### ISSUE TITLE
Clicking 'Read more' on out of stock product still triggers the cart modal to open and doesn't redirect to product page. 

### ISSUE THREAD

**Issue by nickcarswell** [bootscore/bootscore#277]
Example [v](https://wardingtons.co.uk/product-category/brandy/)

**Comment by crftwrk** [comment]
Yes, the Read more button is not supported yet. We will refactor the whole offcanvas cart in a further release  https://github.com/bootscore/bootscore/issues/215, then Read more button will work fine.
