### ISSUE TITLE
Panels disappeared from wordpress page preferences

### ISSUE THREAD

**Issue by balrogmedia** [bootscore/bootscore#278]
Hello,

I am using the great bootscore on my wordpress istes. a few days ago I noticed that the featured image panel wasn't available anymore on the page options on the right column. of the editor. Then I noticed that other panels were gone, including the WP-rocket option. Please see the attachments in case I am not clear. On one attachment I show the site with the missing panels, in the other the one with all the panels.
I went into preferences, but the options are missing there too.

I tried to disable all plugins, and switch theme, but it didn't make a difference.

I would be highly grateful if anyone could point me the right directions. Many thanks in advance!
 
<img width="296" alt="Screenshot 2022-10-05 at 19 24 37" src="https://user-images.githubusercontent.com/98542232/194124479-aee74d28-69c5-4c50-afc3-5cae289ec688.png">
<img width="741" alt="Screenshot 2022-10-05 at 19 25 45" src="https://user-images.githubusercontent.com/98542232/194124482-1a45369d-95f6-4ee1-80ec-bbfead67bb6e.png">
<img width="741" alt="Screenshot 2022-10-05 at 19 26 42" src="https://user-images.githubusercontent.com/98542232/194124488-26996513-3779-4c96-95e7-9d9df1fb950f.png">

**Comment by balrogmedia** [comment]
forgot one screenshot. Here you see all the options I have, which are limited and I enabled everything I could.
<img width="275" alt="Screenshot 2022-10-05 at 19 38 10" src="https://user-images.githubusercontent.com/98542232/194125530-5bfafdfc-28f0-4f39-906d-ab4698904003.png">

**Comment by crftwrk** [comment]
This has for sure nothing to do with theme or one of our plugins. If you want, you can create an admin account and send user and password to store(at)bootscore.me. So, I can look what's happen.

**Comment by justinkruit** [comment]
I would also recommend looking at the console in the dev tools, as Gutenberg is sensitive to JS errors. But I agree with @crftwrk , this is not done by bootScore.

**Comment by crftwrk** [comment]
Close this now because it's not related to the theme.
