### ISSUE TITLE
User selection is invisible!

### ISSUE THREAD

**Issue by androidacy-user** [bootscore/bootscore#293]
Hello!

With bootScore 5.1.2,2 and WP 6.0.2 when a user selects something, the selection is invisible. This only seems to occur with bootScore, and I cannot reproduce on bootstrap itself.

Example: https://www.androidacy.com

**Comment by crftwrk** [comment]
Hello,

where can something be selected on your page? There are a lot of components but I do not see a selection?

**Comment by iwasthesword** [comment]
Text is being selected (you can select and try to drag and it will show it's being selected) but it's not being colored as the variables are wrong:
```
::selection {
    color: var(--bs-white);
    background-color: var(--bs-primary);
}
```
and checking you theme the variable `--bs-primary` doesn't exist and is replaced by `--primary` instead.

**Comment by crftwrk** [comment]
Yes, thats why the default Bootstrap `var(--bs-primary)` variables do not work in your case. You must remove `bs-` prefix like in example above.

**Comment by crftwrk** [comment]
`--bs-` is the default Bootstrap prefix https://getbootstrap.com/docs/5.2/customize/css-variables/#root-variables

**Comment by crftwrk** [comment]
This is not a break. bootScore uses default Bootstrap variables for additional CSS https://github.com/bootscore/bootscore/blob/main/scss/bootscore/_colors.scss. If you change prefix, of course they won't work.

**Comment by iwasthesword** [comment]
> This is not a break. bootScore uses default Bootstrap variables for additional CSS https://github.com/bootscore/bootscore/blob/main/scss/bootscore/_colors.scss. If you change prefix, of course they won't work.
> 
> This is your color :root, no `--bs` there:
> 
> <img alt="screenshot" width="428" src="https://user-images.githubusercontent.com/51531217/196245959-0f493613-a119-4606-bc83-139edbb2e810.png">

Not sure this would work, but shouldn't we use something like then?
```
::selection {
  color: var(--#{$prefix}white);
  background-color: var(--#{$prefix}primary);
}
```

**Comment by crftwrk** [comment]
> Not sure this would work, but shouldn't we use something like then?

Works ;-) Somebody want to create a PR?

**Comment by iwasthesword** [comment]
> Do we then want to continue using css variables, or do we want to use the scss variables? So instead use `$primary` to get that color.

I was looking through the codebase for more examples of using CSS variables and haven't found any (at least not in the `bootscore` folder) so SCSS variables would be best IMO

**Comment by crftwrk** [comment]
This one uses color variables as well https://github.com/bootscore/bootscore/blob/main/scss/bootscore_woocommerce/_wc_colors.scss
