### ISSUE TITLE
Utility API usage with bootscore

### ISSUE THREAD

**Issue by wpre** [bootscore/bootscore#306]
I tried to use the Utility API: 

Created the file: scss/bootscore/_utilities_custom.scss

```
$utilities: map-merge(
  $utilities, (
    "border-bottom": map-merge(
      map-get($utilities, "border-bottom"),
      ( responsive: true ),
    ),
  )
);
```

Imported it via _bscore_style.scss. 

This works only if I only put this line at the end of the file: 

@import "../bootstrap/utilities/api";

But this creates all the utilities and pastes at the end of main.css. 

Is there a way to generate only what is requested in the _utilities_custom.scss to avoid double css entries in main.css?

**Comment by crftwrk** [comment]
@justinkruit any idea?

**Comment by justinkruit** [comment]
As you're doing map-merge, you're adding it to the utilities var, so yeah that will create them all. The API included from Bootstrap is the file that creates all the classes, so it's required. If you only want the border-bottom, you should completely override the $utilities var or use these instructions: https://getbootstrap.com/docs/5.2/utilities/api/#remove-utilities

**Comment by wpre** [comment]
@justinkruit Thanks for your explanation. I just want to enable responsive classes for border-bottom. 

I solved this issue by adding a new file under child-theme/scss: **_bscore_utilities.scss**

```
@import "bootstrap/functions";
@import "bootstrap/variables";
@import "bootstrap/maps";
@import "bootstrap/mixins";
@import "bootstrap/utilities";

$utilities: ()!default;
$utilities: map-merge(
  $utilities, (
    "border-bottom": map-merge(
      map-get($utilities, "border-bottom"),
      ( responsive: true ),
    ),
  )
);
```

And I import this in child-theme main.css before bootstrap.scss to make sure utilities api runs afterwards and only once. 

This seems to work fine but I am not sure this is the right way? Any comments?

**Comment by crftwrk** [comment]
> This seems to work fine but I am not sure this is the right way?

If it works fine, then it seems to be the right way 😎

**Comment by crftwrk** [comment]
Close this now, but it is pinned to the top. So, everyone can read and use this.

**Comment by crftwrk** [comment]
https://github.com/bootscore/bootscore/pull/645
