### ISSUE TITLE
Search doesn't stay open on mobile after clicking icon

### ISSUE THREAD

**Issue by mikemacgregor** [bootscore/bootscore#312]
I've fussed with this for a while and can't figure it out. When I click the search icon on mobile, the search form from my custom HTML widget opens briefly but immediately closes, making it not usable. What is the trick for it to stay open, or why does it close immediately? Thanks for the help.

https://www.draftbuddy.com/

**Comment by crftwrk** [comment]
The Top Nav Search widget position is made for the default `searchform.php`. If you click on the search button, the collapse opens and searchform gets focused. If searchform loses focus, the collapse hides. You can use any other widgets in this position, but not another saerchform. In your case, there is a searchform that gets not focused by clicking the search button. Collapse opens, checks that form is not focused and closes collapse. 

This is done by a snippet in main-theme https://github.com/bootscore/bootscore/blob/main/js/theme.js in line`21`:

```js
// Close collapse if searchform loses focus
$('.top-nav-search input:first-of-type').on('focusout', function () {
  $('#collapse-search').collapse('hide');
});

```

Delete or comment snippet and let me know if that works. Maybe we can improve this using a snippet that closes collapse on click somewhere outside like this:


```js
// Close collapse if click outside searchform
$(document).on("click", function (event) {
  if ($(event.target).closest("#collapse-search").length === 0) {
    $('#collapse-search').collapse('hide');
  }
});

```

**Comment by mikemacgregor** [comment]
Yes, that seems to have worked. I commented out the first part in theme.js and added the second one to custom.js in my child theme (and included a note about adjusting the parent theme). Thanks very much!

**Comment by crftwrk** [comment]
Do you want to create a PR to change this in main-theme?
