### ISSUE TITLE
bootcommerce-child error  when i save the sass file after editing 

### ISSUE THREAD

**Issue by menokemo** [bootscore/bootscore#313]
i get this error when im trying to edit  style  in sass file

Compilation Error
Error: Can't find stylesheet to import.
  ╷
2 │ @import "bootstrap/bootstrap";
  │

**Comment by crftwrk** [comment]
This file is inked in https://github.com/bootscore/bootcommerce-child/blob/main/scss/main.scss, line `2` and fetches https://github.com/bootscore/bootscore/blob/main/scss/bootstrap/bootstrap.scss from main-theme. 

This error means that file in main-theme does not exist or path is wrong. This can have several reasons.

- Theme folder was renamed or folder structure changed.
- An outdated child is used with an updated main or vise versa. Please let me know versions of main and child to investigate further.

**Comment by crftwrk** [comment]
Haven't heard anything here for a while, will close this issue now.

**Comment by menokemo** [comment]
I don't change anything I have just installed the main theme  and the child theme in normal way there is nothing changed 
Thx

**Comment by crftwrk** [comment]
This issue was closed almost a year ago because there was no response. If you still have this bug, please open a new issue and make sure that you have included a link to your project to reproduce.
