### ISSUE TITLE
Affilate links

### ISSUE THREAD

**Issue by 615LdoO7Db** [bootscore/bootscore#319]
Is there going to be any option for those that need to have physical products, downloads and affiliate links? At present the button on the product page for affiliate links just doesn't work.

**Comment by crftwrk** [comment]
Offcanvas cart doesn't support affiliate products yet https://bootscore.me/documentation/woocommerce/#AJAX_Cart.

But we're refactoring the ajax cart in a further update https://github.com/bootscore/bootscore/issues/215. By this update, cart will work with affiliate products too. It's far from stable, but if you want you can test a preview:

- Download branch https://github.com/bootscore/bootscore/archive/refs/heads/Refactor-offcanvas-cart.zip
- Unzip file, rename folder to `bootscore-main` and zip again
- Upload zip file via theme-uploader
- Clear cache

Demo: https://dev.bootscore.me/shop/, last item is an affiliate product
