### ISSUE TITLE
function wpsites_query makes breaks the filter loop_shop_per_page

### ISSUE THREAD

**Issue by aalwash** [bootscore/bootscore#325]
Hi,

First of all, thank you for this amazing theme!

I've noticed something strange, I have my own custom-functions.php
Just an easy function to show 200 products per page.

```
/**
 * Change number of products that are displayed per page (shop page)
 */
add_filter( 'loop_shop_per_page', 'new_loop_shop_per_page', 30 );

function new_loop_shop_per_page( $cols ) {
    // Return the number of products you wanna show per page.
    $cols = 200;
    return $cols;
}
```

After a lot of debugging (took me almost 2+ hours), I found out that the function wpsites_query() (in bootscore/bootscore/functions.php) overwrites this behaviour causing always to show max 24 products per page.

Is there any reason why this is done like this?

A work around (for now is) to make my own wpsites_query() function, so the one from the functions.php isn't called
The real fix would be using loop_shop_per_page filter, instead of hardcode overwriting it to 24

If you agree with the fix, I can push a PR for you guys

**Comment by aalwash** [comment]
See the original class-wc-query in woocommerce how they do it -- https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/class-wc-query.php#L502

They use posts_per_page query param, before falling back to the loop_shop_per_page filter

**Comment by crftwrk** [comment]
Yes, that's because the theme has already this function https://bootscore.me/documentation/functions/.

Simply override function in your child:

```php
function wpsites_query($query) {
  if ($query->is_archive() && $query->is_main_query() && !is_admin()) {
    $query->set('posts_per_page', 64);
  }
}
add_action('pre_get_posts', 'wpsites_query');
```

Now 64 products are shown instead 24.

**Comment by aalwash** [comment]
Hmm, oke
Well I will close this issue for now, hopefully it will save another developer a lot of debugging time :)
