### ISSUE TITLE
Slow Compile on Pages

### ISSUE THREAD

**Issue by jane-tif** [bootscore/bootscore#326]
Just installed it on a fresh install (first use of 5.2) - and every file change is taking ages to re-load in the browser (30 secs +). I expect slow loading when editing .scss files - however it is taking this long to reload every single file edit - i.e. single.php. Seems like compile is forced on every page reload - even though I have ensured that `define('WP_ENVIRONMENT_TYPE', 'development');` is not set. Any ideas?

**Comment by crftwrk** [comment]
Please check here https://github.com/bootscore/bootscore/issues/252

If you are using LocalWP, this comment might be helpfull https://github.com/bootscore/bootscore/issues/252#issuecomment-1332001484

**Comment by crftwrk** [comment]
Closed as duplicate https://github.com/bootscore/bootscore/issues/252
