### ISSUE TITLE
Error on loop/pagination.php in Woocommerce

### ISSUE THREAD

**Issue by nguyenbahoangnam2510** [bootscore/bootscore#339]
Hi everyone, I've discovered an issue of pagination in Woocommerce template, when nagivate to shop page, I haven't found pagination, it still showing in product archive page, however when switch to new page, Products loop still remain and haven't change at all. All i have to do is copy original pagination.php from Woocommerce to child theme to make it work

**Comment by crftwrk** [comment]
Hi,

do you have a link to your site to check?

I've set the loop to 8 products per page here https://dev.bootscore.me/shop/ and pagination seems to work fine?

**Comment by crftwrk** [comment]
Did you set up the amount of products before pagination in the Customizer settings? Don't do that, use a simple function and pagination will work fine:

```php
function wpsites_query($query) {
  if ($query->is_archive() && $query->is_main_query() && !is_admin()) {
    $query->set('posts_per_page', 8);
  }
}
add_action('pre_get_posts', 'wpsites_query');
```

**Comment by nguyenbahoangnam2510** [comment]
Sorry for my late comment, thanks about your reply, when replace original woocommerce pagination code i notice some minor different but not significantly so i forgot it ^^

**Comment by crftwrk** [comment]
So, it works fine now?
