### ISSUE TITLE
Wrong register password message 

### ISSUE THREAD

**Issue by dlyr** [bootscore/bootscore#340]
According to https://github.com/woocommerce/woocommerce/blob/c9748dda099b1e0bf73a4f9c615c2bc0cdb8b4a3/plugins/woocommerce/templates/myaccount/form-login.php#L99

https://github.com/bootscore/bootscore/blob/7685ca4b860e1cb4104b9b51085f61091b811652/woocommerce/myaccount/my-account-offcanvas.php#L123
 'A password will be sent to your email address.' should be changed to 'A link to set a new password will be sent to your email address.'

**Comment by crftwrk** [comment]
Agree, do you want to PR this?
