### ISSUE TITLE
pagination in categories

### ISSUE THREAD

**Issue by ersingo** [bootscore/bootscore#38]
Hello my friend;

pagination doesn’t work when i click on categories. I didn’t make any changes. Is this an error? The number of posts to be displayed is set to 5. It works in searches and on the homepage. but when I click on categories it doesn’t paginate. It shows all the posts.

I see that on your site as well :)

**Comment by crftwrk** [comment]
Hello ersingo,

where do you see this exactly? Please share two links, where it works and where not.

**Comment by ersingo** [comment]
this is my demo homepage. pagination works here. - https://demosite.gen.tr/woogle/

pagination also works while searching. https://demosite.gen.tr/woogle/?s=deneme

but when I click on any category there is no pagination. All articles are listed.
https://demosite.gen.tr/woogle/category/webmaster/

**Comment by crftwrk** [comment]
I see. You mentioned that you see this on bootscore.me site as well. Can you please share the links to this sites? Amount of posts is set to 24 by default.

This is a pluggable function. Add following snippet to your child functions.php and change 24 in line 3 to 5. Let me know if this helps.

```php
function wpsites_query($query) {
  if ($query->is_archive() && $query->is_main_query() && !is_admin()) {
    $query->set('posts_per_page', 24);
  }
}
add_action('pre_get_posts', 'wpsites_query');
```

**Comment by ersingo** [comment]
I hadn't noticed that. It looks correct on the homepage and search page. Why doesn't it work in categories? Can't we skip this function?

then there is no problem with your site. I thought you listed 10 posts. Sorry.

**Comment by crftwrk** [comment]
The amount of posts per pagination in category is set by function, not in WP backend. So, you must paste the function from my previous comment to your child-theme's functions.php and change number 24 to 5. Please check here https://bootscore.me/documentation/functions/. There is an example with exactly this snippet.

Solved?

**Comment by ersingo** [comment]
I am grateful. thanks

**Comment by cleverington** [comment]
I know this ticket is closed and its been almost two years, but the problem here is that the default `pre_get_posts()` within Bootscore's parent theme uses a priority of `10`. If you _don't_ set a priority, it defaults to _below_ the parent theme's default of 24.

To override the default, you need to set the priority to 20.

```php
add_action( 'pre_get_posts', function( $query ) {
    if ($query->is_archive() && $query->is_main_query() && !is_admin()) {
        
        $query->set('posts_per_page', '6');
    }
}, 20, 1 );
```
