### ISSUE TITLE
Some Irritations concerning the favicon docu:

### ISSUE THREAD

**Issue by kreincke** [bootscore/bootscore#419]
Due to the fact, that you ["seriously recommend replacing ALL icons and colors before going live to show site correct in all browsers and search results"](https://bootscore.me/documentation/header-php/), I've just tested the way you've described. At least for the favicons, there are some minor issues.

Basis: First I've created the favicon zip file as you've described it in your docu concerning the header.php. Then I've uploaded the set of replaced facicon-files. At last I've checked the results via Favicon checker:

* iOS Safari: works.
* Android Chrome: works.
* Windows 8 and 10: Feedback "There is no Browser Configuration file at https://xyz/browserconfig.xml ". If I put it manually in the ROOT directory xyz, the feedback is: "The Browser Configuration file is present. [But] https://fxyz/mstile-150x150.png is missed." That's valid, because the file is still inside the bootscore-child/img/favicon. If I look at the header section of head.php, I cannot find any entry containing "echo get_stylesheet_directory_uri(); ?>/img/favicon/browserconfig.xml". So, I assume, that anything mishappens with the integration of that file or the description in your docu has forgotten to mention, that both, the file browserconfig.xml and the file mstile-150x150.png have to be put into the ROOT manually.
* Mac OS X El Capitan Safari: works
* Classic, desktop browsers: works. But the test remarks, that favicon is ill-formed and does not contain a layer of 48x48. (But the file can be read by GIMP and contains all 3 Layers) This is a bit silly, because the Favicon checker is a tool of https://realfavicongenerator.net/. So, I think, we can ignore it: the tool fails its own test.

Additionally, there are some irritations in the steps you described:

* YOU: "Adjust colors for Safari pinned tab icon and Windows phones in lines 26, and 27." WE: In which file shall we adjust the values? Really in safari-pinned-tab.svg? Line 26 and 27 seem not to contain general color information. 
* YOU: "Adjust theme-color in line 28, this should be your primary-color." WE: In which file shall we do that.

Perhaps you could improve the descriptions and fix the browserconfig.xml issue - if and when you have some time in between

Many thanks for your patience. KR

**Comment by crftwrk** [comment]
The favicons are described in the docs for header.php https://bootscore.me/documentation/header-php/. That‘s why you will find thise lines in header.php.

**Comment by crftwrk** [comment]
It's not possible to edit docs via PR, because this are WordPress posts and not hosted here. You can drop text here and we will publish it on bootscore.me.

About the Windows icons: You're right, this should be fixed. Do you want to do this?

**Comment by kreincke** [comment]
In section Logo replace the last bullet sentence by this [referring to the play by its name instead of line numbers]
* If you want to use another image format such as .jpg or .png, store your images in the same folder and adjust the path in the section `<!-- Navbar Brand -->`in file `header.php` (If your child theme does still not contain such a file, copy it from *bootscore-main*) 

In section favicons, replace the second bullet sentence by:
* Adjust colors for Safari pinned tab icon by modifying `[...] img/favicon/safari-pinned-tab.svg" color="#0d6efd" [...]` near line 28 in file  `header.php` 

In section favicons, insert a new third bullet sentence by:
* Adjust colors for Windows phones by modifying `[...] msapplication-TileColor" content="#ffffff" [...]` near line 29 in file  `header.php` 
* 
In section favicons, update the former third, now fourth bullet sentence by 
* Adjust theme-color (= your primary-color) by modifying `[...] name="theme-color" content="#ffffff" [...]` near line 30 in file  `header.php` 

Hoping that this helps KR

**Comment by crftwrk** [comment]
I think we should follow the WordPress codex, remove the entire favicons and let the Customizer do it. We can mention in the docs that the https://wordpress.org/plugins/favicon-by-realfavicongenerator/ plugin will create the best results.
