### ISSUE TITLE
Navbar element link not working is has dropdown menu 

### ISSUE THREAD

**Issue by balrogmedia** [bootscore/bootscore#432]
Hello,

if I create a menu with a menu item page A and a submenu with other pages, then the link on page A isn't clickable.

how to go around the issue please?
the link on SLOT isn't clickable

![Screenshot 2023-03-22 at 09 53 06](https://user-images.githubusercontent.com/98542232/226850170-6799cd89-1479-4f88-a019-50d0c8f5775b.png)
![Screenshot 2023-03-22 at 09 53 35](https://user-images.githubusercontent.com/98542232/226850286-0fa82828-1504-44b4-87ed-7a2e14725dc9.png)

**Comment by balrogmedia** [comment]
here https://casinoonlinesoldiveri.it/

thank you!

**Comment by crftwrk** [comment]
Works fine on my devices?

**Comment by crftwrk** [comment]
Ah sorry, you mean the parent link? Of course, this is just the dropdown-toggler and does not link to a site. You have to add some JS to make this clickable.

Check here https://github.com/orgs/bootscore/discussions/224#discussioncomment-3459118

```js
$('#bootscore-navbar .nav-link.dropdown-toggle').click(function () {
  location.href = this.href;
});

```

**Comment by balrogmedia** [comment]
ok, I tried, thanks

Now the sub nav opens when hovering over which is nice. But the parent link still doesn't link to the page

**Comment by balrogmedia** [comment]
I've done it, also tried to add that CSS here scss/_bscore_custom.scss as described.

The parent link "SLOT" is still not clickable to another page

**Comment by crftwrk** [comment]
I see, you are not working on a child-theme and you do not have a `custom.js` registered. In which file you have added the script?

**Comment by balrogmedia** [comment]
that is confusing :)

I am working on a child theme, I renamed it to "COSV" and I added the script to the custom.js
![Screenshot 2023-03-23 at 13 03 27](https://user-images.githubusercontent.com/98542232/227198342-cbbf6693-5308-4011-ba00-69954b258ee9.png)
The script is kind of working because the dropdown actually does open on hover over. But the parent link is not clickable still

**Comment by crftwrk** [comment]
Yes, this is correct. But I do not see it in the console on your site. Do you have a caching plugin enabled? If so, clear site cache.

**Comment by balrogmedia** [comment]
you are right, I cleared the CSS with wp rocket and now it works :)

however, I see that on mobile the sub menus are collapsed. that is not very elegant.

is there a way to have them not collapsed?
thanks

**Comment by crftwrk** [comment]
> however, I see that on mobile the sub menus are collapsed. that is not very elegant.

That‘s true. But there is no other way to open dropdown-toggler on hover and make it clickable to a site because Bootstrap doesn‘t link dropdown-toggler and opens dropdown by click. On mobile devices there is no hover state to open dropdown, that‘s why dropdowns on mobile must stay open.

**Comment by balrogmedia** [comment]
I sit perhaps possible to use a different menu for mobile? So i wouldn't put child dropdowns on it?

**Comment by crftwrk** [comment]
You can, but it makes no sense to have different functionality. dropdown-toggler is not linked to a site anymore on mobile if you doing this. However open on hover and link toggler to a site is against all Bootstrap standards and I will never use it on one of my sites.
