### ISSUE TITLE
[Feature Request] editor-style.scss

### ISSUE THREAD

**Issue by Effectiva** [bootscore/bootscore#442]
### Describe the feature that you'd like

Hi,

In the folder scss i've added the file editor-style.scss, but its not compiling to editor-style.css?
My other main files main.scss does work?

### Checklist

- [X] I have searched the issues and this feature has not been requested.

**Comment by crftwrk** [comment]
Hi, 

unfortunately you cannot use SCSS compiler for editor https://github.com/orgs/bootscore/discussions/424. You have to enqueue an usual CSS file https://codex.wordpress.org/Editor_Style.

**Comment by Effectiva** [comment]
Hi, 

Yes thats right, but when I try to enqueue editor-style.css it works, however the compiler doesn't compile editor-style.scss to editor-style.css

**Comment by crftwrk** [comment]
> however the compiler doesn't compile editor-style.scss to editor-style.css

Yes, that's not possible https://github.com/orgs/bootscore/discussions/424#discussioncomment-5228488

**Comment by Effectiva** [comment]
Ah ok, that would be nice if its possible in the future. Clients do like to have a styled backend (blocks). I did try to work with wp-scss but that doesn't work/gives errors (I did disable the built in compiler)
