### ISSUE TITLE
[BUG] SCSS variables does not compile

### ISSUE THREAD

**Issue by michalpruszynski** [bootscore/bootscore#443]
### Describe the bug

I've added into _bscore_variables.scss:
```
$primary: red;
$primary-rgb: rgb(10,20,30);
$body-bg: #000;
```

and nothing happens. Its a fresh install. I've worked with bootscore a few times before and compile scss was never an issue.

### Steps to reproduce

1. install bootscore
2. install bootscore-child
3. delete other themes
4. activate bootscore-child

**Comment by crftwrk** [comment]
Your variables work fine on my site. Did you tried to enable dev_mode to force recompile? https://bootscore.me/documentation/theme/bootstrap-css-sass/#Developer_mode
