### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by bnbrndn** [bootscore/bootscore#445]
[Thu Apr 06 16:04:39.679217 2023] [php:error] [pid 108208] [client 141.101.98.88:23036] PHP Fatal error:  Uncaught Error: Call to a member function is_empty() on null in /var/www/html/web/app/themes/bootcommerce-child-main/woocommerce/cart/mini-cart.php:25

Getting this on my staging and production enviroment.

**Comment by crftwrk** [comment]
Hi,

please share a link to your site and describe in more detail e.g. which theme version, plugins etc.

Thank you
