### ISSUE TITLE
Image handling modified?

### ISSUE THREAD

**Issue by kreincke** [bootscore/bootscore#447]
### Describe the bug

Up to 5.2.3.2 in the default index.php / search.php we got the abstract of the post on the right side and the featured image on the left side. The Featured Image was rendered in a way, that it got the same height(!) like the text of the abstract. ( I promise: I do not want to reawaken our old image discussions!), even if the ratio of the image has to be changed.

In 5.2.3.3 the ratio of the image is preserved, even if the picture is not filling the space of the left area. Do you have any idea what has caused this changings and how I could get back the old behaviour?

### Screenshots and Additional Info

Here a screenshot of two posts, created with bs 5.2.3.2:
![featured-image-ratio-changed-5 2 3 2](https://user-images.githubusercontent.com/1419632/230953658-9833f740-8a9b-49f8-ab01-939cfdb9580f.png)

Here a screenshot of the same posts in the same environment, created with bs 5.2.3.3:
![featured-image-ratio-preserved-5 2 3 3](https://user-images.githubusercontent.com/1419632/230953781-43ee6279-d3f8-4f3a-911d-579723d1055e.png)

**Comment by kreincke** [comment]
Please close this: after havin setup all from the beginning, the old behaviour was back. No idea why. Sorry.

**Comment by crftwrk** [comment]
No, you are right. Accidentally removed fallback for previous horizontal cards. Sorry, I create a quick PR.

https://github.com/bootscore/bootscore/blob/a47125428f509981f6376758e17dad90c78f78c4/scss/bootscore/_archive.scss#L5-L45

**Comment by kreincke** [comment]
You are great! Many thanks. During the last three days, I tried to resolve this issue (on a completely wrong level), because the behavior came back and disappeared accidentally. It's so good to hear that there is a systematical solution.

If I look in the 5.2.3.3 download tarball or the main branch or the branch 5.2.3.3 (which is 
 16 commits behind main) in none of them there is a file in bootscore/scss/bootscore/_archive.scss. 

Shouldn't it be sufficient, to add your lines into _bscore_custom.scss of my child theme - until 5.3.0 will be released?

Again: Many thanks for not giving up me!

heartfully KR

**Comment by crftwrk** [comment]
> Shouldn't it be sufficient, to add your lines into _bscore_custom.scss of my child theme - until 5.3.0 will be released?

Yes, but we will ship a patch soon. But instead adding the CSS, it seems better to change your HTML, because new cards are 1000x better (improvements based on your blurred image mention). 


https://github.com/bootscore/bootscore/blob/f3429db54e49f9dd3c90af918065b549c1aa4e87/archive.php#L32-L80

**Comment by kreincke** [comment]
It's good to hear that. Will you release a version 5.2.3.4? Or is there another method by which I can identify that the updates have been integrated into it?

**Comment by crftwrk** [comment]
Simply track your issues and check linked PRs. When issued are closed, PRs are merged. Yes, release will be 5.2.3.4.
