### ISSUE TITLE
WP Multisite Support?

### ISSUE THREAD

**Issue by davidwtalley** [bootscore/bootscore#45]
I'm very interested in this theme, but I need one that works well on WordPress multisite. I don't find any clear answer in docs or promo information on the website, but I would suggest that point would be useful to add.

**Comment by crftwrk** [comment]
Hi David,

personally, I have no experience with multisite projects and theme has not yet been tested with this. But bootScore is just a theme and you can create different child-themes as much as you want and assign them to each site. That should work.

If you want to test it, I'm happy about a feedback and we will add this to the docs.

**Comment by crftwrk** [comment]
Haven't heard anything here for a while. Close the issue now.
