### ISSUE TITLE
[BUG] ? Question concerning new footer info in 5.2.3.4: Doubled CR-Line?

### ISSUE THREAD

**Issue by kreincke** [bootscore/bootscore#455]
### Describe the bug

5.2.3.4 introduces the new footer info at the bottom of a page. It is separated from the other content by a horizontal line. As you've told, it shall enable the authors to edit their specific copyright lines via a widget. This part works well.

Nevertheless, line 80 of the file footer.php still contains the old copyright line from release 5.2.3.3 and earlier, just under the new footer-info code. So, if you insert your own copyright line via a widget, you nevertheless get a second copyright line inserted/created on the template level.

Is that behavior intended? 

[ By the way: If this is a bug, I would say that there is no need to create a hotfix release for it. It's no big deal to delete line 80 and it is easy to communicate that workaround. What do you think?]

### Screenshots and Additional Info

![footer-info-double-crline](https://user-images.githubusercontent.com/1419632/232690537-927fe6c3-5ef4-45e2-a354-9854d5089d5a.png)

**Comment by crftwrk** [comment]
As mentioned in previous comments, copyright with site title and auto updated year will never be removed. Because it's useful and fits for most user needs. But this CR has now a class and can simply removed by CSS:

```css
.bootscore-copyright {
  display: none;
}
```

So, you can use the default CR, hide it and do your own in widget area or simply use both.

**Comment by kreincke** [comment]
I appreciate this solution. It's a good middle-way. I've checked it (https://fodina.de) and it works. So we can close this 'not-bug'. KR
