### ISSUE TITLE
[BUG] Woocommerce - Unable to update the number of products displayed per page

### ISSUE THREAD

**Issue by hsankala** [bootscore/bootscore#468]
### Describe the bug

I'm attempted to update the number of products per page using a code snippet as specified from woocommerce

https://woocommerce.com/document/change-number-of-products-displayed-per-page/

```
/**
 * Change number of products that are displayed per page (shop page)
 */
add_filter( 'loop_shop_per_page', 'new_loop_shop_per_page', 20 );

function new_loop_shop_per_page( $cols ) {
  // $cols contains the current number of products per page based on the value stored on Options –> Reading
  // Return the number of products you wanna show per page.
  $cols = 50;
  return $cols;
}
```
But it is not updating the number of products shown on the category page.  I'm using bootscore parent theme Version: 5.2.3.1 and the child theme Version: 5.2.0.0

Without using this code snippet I've also attempted to update the number of products shown per page using the site customizer:

WooCommerce -> Product Catalog -> Rows per Page - This appeared to work for my test one site using just using parent theme but not a site I'm developing using a child theme.  But on this test site I saw another issue with pagination not working please see my video of this below.

I have a video here of a test site I was using to try and recreate this issue:  https://youtu.be/NKXloYBD2pQ

This is a staging site that I'm setting up for a client, where I saw the original issue of not being able to update the number of products being displayed per page: https://youtu.be/TQ7NgT6WtVY  I'm trying to update the site to display 50 products per page but it's not using the value from the WooCommerce customizer or the snippet in the functions.php

### Steps to reproduce

Clean WordPress installation, I loaded 100 dummy products using a plugin called 'WP Dummy Content Generator' and then in the parent theme I updated the functions.php to with the following code 

/**
 * Change number of products that are displayed per page (shop page)
 */
add_filter( 'loop_shop_per_page', 'new_loop_shop_per_page', 20 );

function new_loop_shop_per_page( $cols ) {
  // $cols contains the current number of products per page based on the value stored on Options –> Reading
  // Return the number of products you wanna show per page.
  $cols = 50;
  return $cols;
}

**Comment by crftwrk** [comment]
Hi,

loop is globally set to 24 items before pagination. Use this function to change number:

```php
function wpsites_query($query) {
  if ($query->is_archive() && $query->is_main_query() && !is_admin()) {
    $query->set('posts_per_page', 64);
  }
}
add_action('pre_get_posts', 'wpsites_query');
```

Now 64 are displayed. Use `-1` for infinite loop. 

Solved?

**Comment by hsankala** [comment]
Solved.  Many Thanks! @crftwrk 

It was a bit weird on the test site what I saw with the paging not showing the next page of products, I'll have another look and test it some nice clean site later.
