### ISSUE TITLE
SIMILAR ARTICLES

### ISSUE THREAD

**Issue by AteS-Github** [bootscore/bootscore#472]
### Describe the feature that you'd like

Hİ
HOW TO USE SIMILAR POSTS ADD-ON WITHOUT E-COMMERCE

### Why is this feature needed? What problem does it solve?

SIMILAR ARTICLES MUST BE RECOMMENDED WITHOUT E-COMMERCE

### Checklist

- [X] I have searched the issues and this feature has not been requested.

**Comment by crftwrk** [comment]
Hi,

thank you for opening this feature request, please check this first:

- Take much more time and effort to explain issue in deep detail. We do not want to read between the lines, your request should be described crystal clear.  
- Do NOT use capital letters for the body text. THIS IS LOUD, UNFRIENDLY AND HARD TO READ!

After reading this issue 10 times, I think you want something like related posts, right? For now, you have to code this by yourself, this issue https://github.com/bootscore/bs-grid/issues/8 will help you how to do this.

Maybe we can add related posts feature in a further release.

**Comment by AteS-Github** [comment]
thanks

**Comment by crftwrk** [comment]
We will create related posts by the next bS Swiper plugin release.
