### ISSUE TITLE
[BUG] Duplicate class property 

### ISSUE THREAD

**Issue by hsankala** [bootscore/bootscore#488]
### Describe the bug

There is a duplicate class property here causing HTML validation to fail.

It has both `class="form-control"` and `class="search-field field form-control"`

https://github.com/bootscore/bootscore/blob/6b8146936b5f1bbe61dc24dccdabbd680eb8deef/woocommerce/product-searchform.php#L27

**Comment by crftwrk** [comment]
Thank you for figuring this out. Want to fix this quickly and create a PR? So we can ship this with 5.3 release this week.

**Comment by hsankala** [comment]
No worries just passing through my first website made with Bootscore through a validator brought them to my attention.

I'm in no rush for a fix, just interested in making the theme better in the future!
