### ISSUE TITLE
[BUG] Javacript block HTML validation fail

### ISSUE THREAD

**Issue by hsankala** [bootscore/bootscore#489]
### Describe the bug

The specified parameter `charset="UTF-8"` in a Javascript block below is causing HTML validation failure using (https://validator.w3.org/), for the reason stated

https://github.com/bootscore/bootscore/blob/6b8146936b5f1bbe61dc24dccdabbd680eb8deef/woocommerce/ajax-cart/ajax-add-to-cart.php#L19

![image](https://github.com/bootscore/bootscore/assets/14014749/64d9f9a5-fc12-4229-a493-967bcf1edf68)

**Comment by crftwrk** [comment]
Correct, `<script>` is enough. Want to fix this quickly and create a PR? So we can ship this with 5.3 release this week.

**Comment by hsankala** [comment]
No worries just passing through my first website made with Bootscore through a validator brought them to my attention.

I'm in no rush for a fix, just interested in making the theme better in the future!
