### ISSUE TITLE
[Feature Request] Woocommerce function checks when Woo is disabled

### ISSUE THREAD

**Issue by seanvandermolen** [bootscore/bootscore#490]
### Describe the feature that you'd like

When using bootcommerce child theme, if the Woocommerce plugin is disabled the theme crashes when attempting to use Woocommerce functions.

bootcommerce-child-main | header.php - line 156 updated with
`            <div class="widget_shopping_cart_content"><?php if (function_exists('woocommerce_mini_cart')) { woocommerce_mini_cart(); }?></div>`

bootscore-main | my-account-offcancas.php line 28-30 updated with

`        <?php if (function_exists('wc_get_account_menu_items')) { foreach (wc_get_account_menu_items() as $endpoint => $label) : ?>
          <a href="<?php echo esc_url(wc_get_account_endpoint_url($endpoint)); ?>" class="list-group-item list-group-item-action"><?php echo esc_html($label); ?></a>
        <?php endforeach; }?>`

### Why is this feature needed? What problem does it solve?

There are time where it would be necessary to run the site without Woocommerce plugin installed/ enabled.  A couple of scenarios

> Troubleshooting plugin conflicts
> Dev environment for styling 

Currently, the theme will cause PHP faults and stop rendering the front end without the checks.  

It's possible there are other instances where additional checks would help, the are the two that I needed to fix in a clean environment.

### Checklist

- [X] I have searched the issues and this feature has not been requested.

**Comment by crftwrk** [comment]
Thank you! This is already solved, merged by https://github.com/bootscore/bootscore/pull/473 and will be released this week. bootcommerce-child is obsolete and repo will be closed.

All WooCommerce related scripts, cart etc. are activated if WooCommerce is installed now. Download latest [bootscore-main](https://github.com/bootscore/bootscore/archive/refs/heads/main.zip) and latest [bootscore-child](https://github.com/bootscore/bootscore-child/archive/refs/heads/main.zip) branch, install WooCommerce and activate/deactivate plugin. Theme checks if WooCommerce is active or not by itself. This has no breaking changes to existing bootcommerce-child installations. Main-theme can be used as a stand-alone theme with a shop as well without doing anything in the code.
