### ISSUE TITLE
[Feature Request] Description

### ISSUE THREAD

**Issue by AteS-Github** [bootscore/bootscore#517]
### Describe the feature that you'd like

hello i have a problem with a site
It doesn't work when I pull through css and js functions.php
but when i add header it works
why is this problem thanks in advance

### Checklist

- [X] I have searched the issues and this feature has not been requested.

**Comment by crftwrk** [comment]
You are using a heavy modified main-theme with outdated Bootstrap 3.3.2. Because theme structure has deeply changed, we are not able to help here out.
