### ISSUE TITLE
page-full-width-image

### ISSUE THREAD

**Issue by trockendock** [bootscore/bootscore#519]
### Describe the bug

so, I am adopting the "**template page-full-width-image**"

I understand it is using flexbox. 

But the thing is now, that if I want to add another line below the `h1` (lets say a `<p>`, e.g.), this is not on a new line, but just on the same one as the h1
` <header class="entry-header featured-full-width-img height-75 bg-dark text-light mb-3" style="background-image: url('<?= $thumb['0']; ?>')">
          <div class="<?php echo bootscore_container_class(); ?> entry-header h-100 d-flex align-items-end pb-3">
            <h1 class="entry-title"><?php the_title(); ?></h1>
           <p>Paragraph on new line</p>
          </div>
        </header>`
        
In my opinion, this template should be in such a way that it not only accepts one line of text but multiple elements/lines.

Question: how to solve that?

### Screenshots and Additional Info

current behaviour:
![Bildschirm­foto 2023-06-26 um 14 56 23](https://github.com/bootscore/bootscore/assets/6531978/455f8dad-687f-4249-bca4-83fd865376bc)
![Bildschirm­foto 2023-06-26 um 14 55 53](https://github.com/bootscore/bootscore/assets/6531978/92f29027-a48b-441e-8fba-e1485c324698)

**Comment by crftwrk** [comment]
I see. Simply wrap the `<h1>` in a `<div>` and add the  `<p>` inside this `<div>`:


```php
<header class="entry-header featured-full-width-img height-75 bg-dark text-light mb-3" style="background-image: url('<?= $thumb['0']; ?>')">
  <div class="<?php echo bootscore_container_class(); ?> entry-header h-100 d-flex align-items-end pb-3">
    <div>
      <h1 class="entry-title"><?php the_title(); ?></h1>
      <p>Paragraph on new line</p>
    </div>
  </div>
</header>
```

Do you want to change this quickly and create a pull request? Think this might be useful for other users.
