### ISSUE TITLE
WooCommerce Ajax Cart

### ISSUE THREAD

**Issue by IceflowRE** [bootscore/bootscore#521]
I have different problems with the ajax add to cart.

First i enabled the to cart redirection in the WC settings.

## on shop page
`Add to cart` adds the product to the cart and redirects.

## on product page

`Add to cart` triggers
- `?wc-ajax=ace_add_to_cart` which returns 302
- `/cart` returns 200
-> which contains the product but a redirect is not happening and the html returned by `/cart/` is not displayed.

## on subscription page with switching

`Switch subscription` triggers
- `?wc-ajax=ace_add_to_cart` which returns 200
-> contains a json
```json
{"fragments":{"div.widget_shopping_cart_content":"<div class=\"widget_shopping_cart_content\">\r\n\r\n  <p class=\"woocommerce-mini-cart__empty-message woocommerce-info m-3\">No products in the cart.<\/p>\r\n\r\n\r\n<\/div>","span.cart-content":"    <span class=\"cart-content\">\r\n          <\/span>\r\n\r\n    ","notices_html":"<ul class=\"woocommerce-error\" role=\"alert\">\n\t\t\t<li>\n\t\t\tSorry, this product cannot be purchased.\t\t<\/li>\n\t<\/ul>\n"},"cart_hash":"436ce4e5a632b19ca854e340b383bb43"}
```
implies that the product cannot be purchased.
- `/cart` returns 200
-> contains the html for the empty cart.

**Comment by IceflowRE** [comment]
Using the theme `twenty twenty three` works fine for all cases, but also not using the ajax functions as far as i see.

**Comment by crftwrk** [comment]
> First i enabled the to cart redirection in the WC settings.

This won't work, redirection must be disabled. If you want to redirect, the entire AJAX functionality must be disabled. Check https://bootscore.me/documentation/woocommerce/#AJAX_cart for WC settings and how to disable AJAX cart in child.

> on subscription page with switching

Sentence above should solve this issue. Please share a link to your project to check.

**Comment by IceflowRE** [comment]
> > First i enabled the to cart redirection in the WC settings.
> 
> This won't work, redirection must be disabled. If you want to redirect, the entire AJAX functionality must be disabled. Check https://bootscore.me/documentation/woocommerce/#AJAX_cart for WC settings and how to disable AJAX cart in child.
> 
> > on subscription page with switching
> 
> Sentence above should solve this issue. Please share a link to your project to check.

Thanks this solved almost all issues, except the subscription switching, i disabled the ajax cart for now, then everything works fine.
The subscription type is a `Variable subscription`.

> Please share a link to your project to check.
Sadly iam not able to do so.

**Comment by crftwrk** [comment]
You're welcome.

Well, it's very hard to debug something blind, but let's try this for the subscription plugin:

- Download and install latest developed theme https://github.com/bootscore/bootscore/archive/refs/heads/main.zip
- Open `wc-functions.php` and delete following line
https://github.com/bootscore/bootscore/blob/3d027e11395da97efab18fa1f90e93572f54f240/woocommerce/wc-functions.php#L48

Now, all AJAX scripts are removed. Let me know if that works. If so, we can enqueue file in `ajax-add-to-cart.php` and script is not loaded when AJAX cart is disabled by function.

**Comment by IceflowRE** [comment]
The bug is gone with 3d027e11395da97efab18fa1f90e93572f54f240, i could not identify what exactly was the reason since 5.3.0 (with wc-cart-fragments patch).

Should have tested that before, sorry for the noise in that regard.

Anyway huge thanks for your time and help <3
