### ISSUE TITLE
[BUG] Duplicate wc-ajax=add_to_cart

### ISSUE THREAD

**Issue by memeq1** [bootscore/bootscore#532]
### Describe the bug

bootscore to v5.3.1. After update i have duplicate request wc-ajax=add_to_cart. I see this same problem in offical site and dev.

### Steps to reproduce

1. Go to https://bootscore.me/shop/
2. Click add to cart button
3. Go to developer console 
4. duplicate ?wc-ajax=add_to_cart

### Screenshots and Additional Info

![image](https://github.com/bootscore/bootscore/assets/5739180/5e95425b-cb77-493b-ba47-31b44c1e87e1)

[screen](https://github.com/bootscore/bootscore/assets/5739180/41c3dbdf-5400-4eed-b012-2093d88b231a)

### Website link

https://bootscore.me/shop/

**Comment by memeq1** [comment]
Yes, this click event causes wc-ajax to be called twice. I modified/removed the event. Works

**Comment by crftwrk** [comment]
Do you have removed the entire click event?

**Comment by memeq1** [comment]
Yes, I'm missing the notification in the mini cart, but I don't have any duplicate quantity and call add_to_cart. I keept  only triggers

```php   $(document.body).on('adding_to_cart', function() {
                offCanvasCart.addClass('loading').offcanvas('show');
            })

            $(document.body).on('added_to_cart', function(){
                offCanvasCart.removeClass('loading');
           
            });

           ```

**Comment by crftwrk** [comment]
Ok, got it. Of course, the alerts have an AJAX request as well. Why this is now twice since WooCommerce dropped the `wc-cart-fragments` is mystic, but I think we have to accept this.

Again, thanks for reporting
