### ISSUE TITLE
Firefox last scroll pos

### ISSUE THREAD

**Issue by Kemal-Sulic** [bootscore/bootscore#54]
Hi guys, 

recently I noticed that the last scroll position is not saved when reloading the page in Firefox. I searched the net but only found posts almost as old as me hehe....

Does anyone know why this happens?

**Comment by crftwrk** [comment]
It seems that this has something to do with smooth-scroll https://github.com/bootscore/bootscore/issues/51. Without this script, Firefox saves the scroll position on reload correctly. Check here https://dev.bootscore.me/2013/01/10/markup-image-alignment/

**Comment by crftwrk** [comment]
We'll fix this here https://github.com/bootscore/bootscore/issues/51
