### ISSUE TITLE
img src not show

### ISSUE THREAD

**Issue by menokemo** [bootscore/bootscore#550]
hello every one 
i have a problem  that i try to insert img  but  its not showing  in the page 

 <section class="about">
        <div class="container">
            <div class="about-pic">
                <img src="./img/my-pic/User-Avatar-Profile-PNG.png" alt="mk-prof-pic">
            </div>
            <div class="about-text">
            </div>
        </div>
    </section>

its only showing the alt value

**Comment by menokemo** [comment]
its only showing the alt value  but not showing the img itself.  I did make sure for the path even I change the image itself  but not helping. 

Thanks alot for your patience

**Comment by crftwrk** [comment]
This has nothing to do with the theme. However, I do not know where you have inserted the image, but I had a quick view to your code above. 

`<img src="./img/my-pic/User-Avatar-Profile-PNG.png" alt="mk-prof-pic">`

You are using a relative URL and have a missing . in the path. It is not a path to a WordPress media inage as well. Use absolute (full) URL for the src.

**Comment by menokemo** [comment]
> This has nothing to do with the theme. However, I do not know where you have inserted the image, but I had a quick view to your code above. 
> 
> `<img src="./img/my-pic/User-Avatar-Profile-PNG.png" alt="mk-prof-pic">`
> 
> You are using a relative URL and have a missing . in the path. It is not a path to a WordPress media inage as well. Use absolute (full) URL for the src.

 I do use a localhost . Always I do use relative path. I did never use a absolute URL. Also I did change the theme and everything works good only in the bootscore

**Comment by crftwrk** [comment]
Ok, please transfer your project to a public server and share a link to check this.

**Comment by crftwrk** [comment]
Didn't get any feedback here and closing this issue now.
