### ISSUE TITLE
[BUG] WooCommerce subscription switch

### ISSUE THREAD

**Issue by IceflowRE** [bootscore/bootscore#564]
### Describe the bug

Bootscore is not able to switch subscriptions and returns 
```
{
	"fragments": {
		"div.widget_shopping_cart_content": "<div class=\"widget_shopping_cart_content\">\r\n\r\n  <p class=\"woocommerce-mini-cart__empty-message woocommerce-info m-3\">No products in the basket.</p>\r\n\r\n\r\n</div>",
		"span.cart-content": "    <span class=\"cart-content\">\r\n          </span>\r\n\r\n    ",
		"notices_html": "<ul class=\"woocommerce-error\" role=\"alert\">\n\t\t\t<li>\n\t\t\tSorry, this product cannot be purchased.\t\t</li>\n\t</ul>\n"
	}
}
```
the product cannot be purchased, because [Limit subscription](https://woocommerce.com/document/subscriptions/store-manager-guide/#limit-subscription) is set to `Limit to one of any status`.

If using bootscore theme on switching `/?wc-ajax=ace_add_to_cart` is called with payload
```
-----------------------------6351900761022413022355843451
Content-Disposition: form-data; name="attribute_type"

Premium
-----------------------------6351900761022413022355843451
Content-Disposition: form-data; name="quantity"

1
-----------------------------6351900761022413022355843451
Content-Disposition: form-data; name="add-to-cart"

81
-----------------------------6351900761022413022355843451
Content-Disposition: form-data; name="product_id"

81
-----------------------------6351900761022413022355843451
Content-Disposition: form-data; name="variation_id"

86
-----------------------------6351900761022413022355843451
Content-Disposition: form-data; name="add-to-cart"

81
-----------------------------6351900761022413022355843451--
```

but on using twenty twenty three `/product/subscriptions/?switch-subscription=169&item=43&_wcsnonce=c884ef4b43` (where `product/subscriptions` is the product page) is called with payload
```
-----------------------------92260278125604018363965668702
Content-Disposition: form-data; name="attribute_type"

Premium
-----------------------------92260278125604018363965668702
Content-Disposition: form-data; name="quantity"

1
-----------------------------92260278125604018363965668702
Content-Disposition: form-data; name="is-descendent-of-single-product-block"

false
-----------------------------92260278125604018363965668702
Content-Disposition: form-data; name="add-to-cart"

81
-----------------------------92260278125604018363965668702
Content-Disposition: form-data; name="product_id"

81
-----------------------------92260278125604018363965668702
Content-Disposition: form-data; name="variation_id"

86
-----------------------------92260278125604018363965668702--

```

Related to #521, but i thought it would be better to open a new issue.

If you need more information, i am happy to assist. Regarding a test page, i have to request if i can pass it to you. If you do not need one, the better.

### Steps to reproduce

Go to the product page of the subscription.
Select another subscription.
Click switch.

**Comment by IceflowRE** [comment]
> We do not have this plugin and cannot reproduce this issue. Please make sure that you share always a link to a reduced test case in bug reports.

Is there an option to send you a test case privately (that only member of bootscore can acceess that link)?

**Comment by crftwrk** [comment]
No, we do open source and public. Please set up a new WordPress, install bootScore, Woocommerce, supscription plugin and add a sample product. This testing site can you use then for further bug reports.

**Comment by IceflowRE** [comment]
> Disable the ajax cart should solve this https://github.com/orgs/bootscore/discussions/569#discussioncomment-6968025

Results in
```
Uncaught ReferenceError: wc_add_to_cart_params is not defined
    <anonymous> /product/subscriptions/?switch-subscription=169&item=43&_wcsnonce=b57e1bcb1a&auto-switch=true:446
    jQuery 10
    <anonymous> /product/subscriptions/?switch-subscription=169&item=43&_wcsnonce=b57e1bcb1a&auto-switch=true:432
    jQuery 13
        e
        t
        setTimeout handler*Deferred/then/l/<
        c
        fireWith
        fire
        c
        fireWith
        ready
        P
        EventListener.handleEvent*
        <anonymous>
        <anonymous>
subscriptions:446:11
    <anonymous> /product/subscriptions/?switch-subscription=169&item=43&_wcsnonce=b57e1bcb1a&auto-switch=true:446
    jQuery 10
    <anonymous> /product/subscriptions/?switch-subscription=169&item=43&_wcsnonce=b57e1bcb1a&auto-switch=true:432
    jQuery 13
```

You can find the plugin files [here](https://github.com/pronamic/woocommerce-subscriptions/tree/main).

Also i might be able to send you an example website in a week, maybe earlier.

**Comment by crftwrk** [comment]
If AJAX cart is disabled, theme has the same functionality as the default themes. However, let's wait for the example, then we can check.

**Comment by IceflowRE** [comment]
Website: https://temp.gretas-research.de
Username: `test`
Password: `test`
Shop: https://temp.gretas-research.de/shop/

You can "purchase" the basic subscription first its free and then try to switch to premium, (you wont be able to checkout because no payment provider is enabled), but for testing purposes we do not need that anyway.

I installed bootscore and bootscore-child, the later is the activated one. The child theme has no changes.

**Comment by crftwrk** [comment]
Now we get closer. Well, got a copy of subscription plugin v5.4.0 and did the same setup like you. Basic variation free and Premium paid. Both sold individually and seems to work fine? If once has been added to the cart, you can switch between variations.

Check https://dev.bootscore.me/product/subscription-2/

**Comment by IceflowRE** [comment]
> Now we get closer. Well, got a copy of subscription plugin v5.4.0 and did the same setup like you. Basic variation free and Premium paid. Both sold individually and seems to work fine? If once has been added to the cart, you can switch between variations.
> 
> Check https://dev.bootscore.me/product/subscription-2/

It is not about switching while one is being added to the cart. It is about switching while you already had one purchased, so you switch your active subscription.

In the subscriptions settings you have to allow `Allow Switching between subscriptions variations`.

If you want you can import the products [wc-product-export.csv](https://github.com/bootscore/bootscore/files/12616795/wc-product-export.csv). Then we should have the same product settings.

**Comment by crftwrk** [comment]
This is the subscription imported via your csv https://dev.bootscore.me/product/subscriptions/.

I cannot say what's wrong on your site.

**Comment by IceflowRE** [comment]
Are you sure you enabled switching?
![image](https://github.com/bootscore/bootscore/assets/10883690/0974d5ea-84be-4bc5-9435-443b0a806d48)

Iam not able to switch the subscriptions.

**Comment by IceflowRE** [comment]
Yes on your site it is working now.

> Now I have Allow Between Subscription Variations enabled.
> 
> Please empty cart and reload the page https://dev.bootscore.me/product/subscriptions/. It works?

Yes, it is working now.

> You mentioned above that twenty twenty three theme works fine. Please install another Bootstrap theme https://wordpress.org/themes/understrap/ and let me know if your plugin is working with this one. I tested it and subscription switch works exactly as in bootScore.

Yes understrap is redirecting me to the checkout. You mean with your plugin the woocommerce plugins? I have no other plugins installed.

> If Understrap works well for you, roughly delete/comment following snippets in `bootscore-main` to make sure that all scripts which may have a conflict are disabled:
> #### Ajax cart
> 
> https://github.com/bootscore/bootscore/blob/abdb20a200d8ad1c7c979108ee70fd3f440f7f59/woocommerce/wc-functions.php#L29-L41
> 
> #### WooCommerce JS
> 
> https://github.com/bootscore/bootscore/blob/abdb20a200d8ad1c7c979108ee70fd3f440f7f59/woocommerce/inc/wc-enqueue.php#L28
> 
> #### Theme JS
> 
> https://github.com/bootscore/bootscore/blob/abdb20a200d8ad1c7c979108ee70fd3f440f7f59/inc/enqueue.php#L42

Disabling everything you mentioned until here, will also then redirect me to the checkout.

> If plugin still not work, you can try at least disable Bootstrap's JS to check if there is a conflict (think not).
> 
> https://github.com/bootscore/bootscore/blob/abdb20a200d8ad1c7c979108ee70fd3f440f7f59/inc/enqueue.php#L39

Did not try this.

**Comment by IceflowRE** [comment]
Adding to cart works with `https://dev.bootscore.me/product/subscription-variable` but not with `https://dev.bootscore.me/product/subscriptions`

**Comment by crftwrk** [comment]
> Disabling everything you mentioned until here, will then redirect me to the checkout.

This gives you the answer. You should disable AJAX cart as usual and then delete/check each snippet in `js/theme.js` and `woocommerce/js/woocommerce.js`. Once you find the culprit snippet, we can take a closer look.

**Comment by IceflowRE** [comment]
Having AJAX cart disabled and `js/theme.js` and `woocommerce/js/woocomerce.js` enabled, redirects. 

I think the error might be here https://github.com/bootscore/bootscore/blob/main/woocommerce/inc/ajax-add-to-cart.php#L38-L91, but at this point iam out of ideas, i just can say that it do not work as described here

> Adding to cart, while switching, works with `https://dev.bootscore.me/product/subscription-variable` but not with `https://dev.bootscore.me/product/subscriptions`

**Comment by crftwrk** [comment]
> Having AJAX cart disabled and js/theme.js and woocommerce/js/woocomerce.js enabled, redirects.

Yeah, this leads back to https://github.com/bootscore/bootscore/issues/564#issuecomment-1713999046. Sure, AJAX script prevents redirection to checkout. If you want to redirect after added to cart, you must disable AJAX script. 

I see, your site is working fine now. So, this isn't a bug and we will do no changes there.

**Comment by IceflowRE** [comment]
Hopefully it stays like that, if you want to investigate further, it is still broke on your own site https://dev.bootscore.me/product/subscriptions/.

**Comment by crftwrk** [comment]
> if you want to investigate further, it is still broken on your own site

Of course, because AJAX cart is enabled. Subscription plugin with this settings does not work together with AJAX cart. You have to disable it.

**Comment by IceflowRE** [comment]
> > if you want to investigate further, it is still broken on your own site
> 
> Of course, because AJAX cart is enabled. Subscription plugin with this settings does not work together with AJAX cart. You have to disable it.

Why is it working here then? https://dev.bootscore.me/product/subscription-variable/

**Comment by crftwrk** [comment]
The difference is that your subscription is limited to one of any status

Me https://dev.bootscore.me/product/subscription-variable/

![me](https://github.com/bootscore/bootscore/assets/51531217/08cfe7b7-0edd-40ae-ab2c-d8fe6ef975ce)

You https://dev.bootscore.me/product/subscriptions/

![yours](https://github.com/bootscore/bootscore/assets/51531217/759f5b52-a599-4e47-9803-e09171e8dd17)
