### ISSUE TITLE
[Feature Request] Filter to remove fontawesome

### ISSUE THREAD

**Issue by androidacy-user** [bootscore/bootscore#566]
### Describe the feature that you'd like

Hello!

Since we use FontAwesome Pro, we remove the default FA styles provided by this theme. However, currently we have to manually edit the functions.php from the parent theme, as trying to override it in the child theme is hit and miss and requires us to mess with priorities which causes other conflicts anyway.

We'd like to see a filter (i.e., "bootscore_fontawesome_enqueue") or similar that can prevent this arguably non-essential file from being loaded.

### Why is this feature needed? What problem does it solve?

Some people like us may prefer to use their own version of fontawesome or even remove it entirely.

### Checklist

- [X] I have searched the issues and this feature has not been requested.

**Comment by crftwrk** [comment]
If you have an idea, please create a PR. But @justinkruit is FA pro user as well, maybe he has an idea or can quickly explain how he solves that.

**Comment by justinkruit** [comment]
I see the mentioned using priorities etc. Have you tried making a new function in your child theme, dequeue fontawesome in there, and then register that function as a hook with a later priority? That should solve this issue. (Can't write an example at the moment, as I'm on my phone haha)

**Comment by justinkruit** [comment]
> That's more work than a `//` on the enqueue or a `add_filter('who_says_you_cant_code_onmobile', '__retrun_false');`. The idea here is to make it as easy as possible to opt out of FA.

`Function "__retrun_false" not found. Maybe develop on pc?` 😜

Currently looking into this, with the idea to add more filters in general.

**Comment by smileBeda** [comment]
So, if I am not totally obtuse, you can and should do this:

1. In the child theme do the usual parent and child themes styles enqueue stuff. So generally that means `add_action( 'wp_enqueue_scripts', 'bootscore_child_enqueue_styles', 10 );` and in the CB, you just use the default parent enqueue and child enqueue
2. Then, in the child theme, in a _separate_ callback you do `add_action( 'wp_enqueue_scripts', 'go_away', 11 );` where the CB does:
```
function go_away(){
	wp_dequeue_style( 'fontawesome' );
}
```

This should work. The reason you need priority 11 is that the parent theme uses default 10, and if you load this dequeue on the same priority it wont work.

I suggest to also do `remove_filter('style_loader_tag', 'bootscore_fa_preload');` so you do not get any overhead (even if the fa styles are gone, this fn still runs unless you remove it)

This should do the trick.
