### ISSUE TITLE
header.php help file incorrect

### ISSUE THREAD

**Issue by oitconz** [bootscore/bootscore#588]
Documentation Error: 
Page:  https://bootscore.me/documentation/header-php/

**Under Subheading : Favicon, touch-icons and theme colors**
The following two lines are incorrect: 

- Adjust colors for Safari pinned tab icon and Windows phones in lines 26, and 27.
- Adjust theme-color in line 28, this should be your primary-color.

They should read :
- Adjust colors for Safari pinned tab icon and Windows phones in lines 28, and 29.
- Adjust theme-color in line 30, this should be your primary-color.

Also it possibly would help to let coders know the changes above are made by copying the values for those lines from the downloaded site.manifest

**Comment by crftwrk** [comment]
Thank you for reporting, this has been fixed.

The entire favicon area will be deleted by v5.4 and goes back to the WP Customizer.
