### ISSUE TITLE
Add Quantity on content-product.php 🆘 

### ISSUE THREAD

**Issue by Lo1176** [bootscore/bootscore#60]
Hi!
I would like to add the Quantity arrows section directly on content-product.php next to the add to cart button.
How can I do this?
<img width="223" alt="Capture d’écran 2021-12-23 à 17 17 44" src="https://user-images.githubusercontent.com/56685868/147266663-1e812149-b74b-43d0-8017-68cb48b247a6.png">
[here](https://www2.maison-chateau-laguiole.fr/categorie-produit/iroquois-color/)

**Comment by crftwrk** [comment]
Hi Lo,

you posted this already here https://github.com/bootscore/bootscore/issues/50

**Comment by Lo1176** [comment]
Nope Basti, this is to add the Quantity to `product-content.php` or `woocomerce.php`.
It is already displayed on `content-single-product.php` by default, and with your peace of code it is "sublime"!
But it is not in `content-product.php` by default.
Do you have an idea to add it?

**Comment by Lo1176** [comment]
I've find something good here.
[https://woocommerce.com/document/override-loop-template-and-show-quantities-next-to-add-to-cart-buttons/#](https://woocommerce.com/document/override-loop-template-and-show-quantities-next-to-add-to-cart-buttons/#)

It'll be fine!
🙏

**Comment by Lo1176** [comment]
Sorry, I still have an issue. 😞 

I have 2 in_stock displayed on my content-product : 

<img width="586" alt="Capture d’écran 2021-12-23 à 20 11 22" src="https://user-images.githubusercontent.com/56685868/147282946-a079617f-b980-4a6b-9767-0b3719acdd91.png">

One is from the simple.php file and I can't removed this line 
```php
echo wc_get_stock_html($product); // WPCS: XSS
```
because it will removed it from the content-single-product too.

And I can't find what to do ...

**Comment by Lo1176** [comment]
I finally used css with `:first-child` and `display: none;`
But I'm curious to know where it is in Woocommerce

**Comment by crftwrk** [comment]
Related to https://github.com/bootscore/bootscore/issues/50, this one does the trick:

```php
/**
 * Override loop template and show quantities next to add to cart buttons
 */
add_filter( 'woocommerce_loop_add_to_cart_link', 'quantity_inputs_for_woocommerce_loop_add_to_cart_link', 10, 2 );
function quantity_inputs_for_woocommerce_loop_add_to_cart_link( $html, $product ) {
  if ( $product && $product->is_type( 'simple' ) && $product->is_purchasable() && $product->is_in_stock() && ! $product->is_sold_individually() ) {
    $html = wc_get_template_html( 'single-product/add-to-cart/simple.php' );
  }
  return $html;
}
```
