### ISSUE TITLE
[BUG] Bad accessibility behavior

### ISSUE THREAD

**Issue by sir-lexonarkz** [bootscore/bootscore#604]
### Describe the bug

In the SCSS bootscore color the outline was put to outline 0.

So if you use tab to navigate in the page links and buttons aren't outline.

Major issue for accessibility.

### Steps to reproduce

Use tabulation to navigate in a page
Links and buttons aren't outline

### Screenshots and Additional Info

This issue is from :

bootscore/_colors.scss 

// Reset focus
:focus {
  outline: none !important;
  outline: -webkit-focus-ring-color none !important;
  outline-color: -webkit-focus-ring-color none !important;
  outline-style: none !important;
  outline-width: 0 !important;
}

**Comment by crftwrk** [comment]
You're right, this is a very very old snippet. Do you want to fix and create a pull request?

**Comment by sir-lexonarkz** [comment]
done
