### ISSUE TITLE
[BUG] Redundant (and sometimes problematic) IMG max-with in parent default style

### ISSUE THREAD

**Issue by smileBeda** [bootscore/bootscore#607]
### Describe the bug

In the Parent theme there is a CSS rule defaulted in the main.css:
```
img {
  height: auto;
  max-width: 100%;
}
```
_https://github.com/bootscore/bootscore/blob/7d7fbac9d0880c32625a864b863457e0d022d736/scss/bootscore/_markups.scss#L19_

This is redundant because, as it being a Bootstrap Theme, if we want responsive images, we should use `img-fluid` class which sets the _exact_ same CSS, _but only when that class appears in the `img` markup_

Now, this might not seem a problem to have the CSS "double", and usually it is even a welcome thing, _however_ this causes issues where you actually want the image to be _not_ responsive (for example full width images that use `width-100`

In that case, you need to overwrite the redundant rule in the child custom scss.
Which is of course not a big deal, just that at this point the rule is triplicated 🥲 

I filed this in "bug", maybe you will disagree... my suggestion would be to not duplicate the CSS especially as a Bootstrap theme will, technically, rely on the bootstrap classes (which can be easily added to any image, even WordPress image outputs.)

Let me know what you think.

**Comment by crftwrk** [comment]
This came from the [underscores](https://underscores.me) boiler template.

Check https://dev.bootscore.me/2013/01/10/markup-image-alignment/, open console and remove it. Featured image gets crashed and all other images have fallback to:

```css
html :where(img[class*=wp-image-]) {
  height: auto;
  max-width: 100%;
}
```

If you remove this as well, images will overflow the container:

![screenshot](https://github.com/bootscore/bootscore/assets/51531217/1302e2c8-32a4-43e7-a924-60fa18494b6a)

**Comment by smileBeda** [comment]
Right, got that... but would it not be more adequate to add `img-fluid` to the markup of those images?
I understand the failsafe... 

I guess I will just overwrite it in the scss - no big deal.

**Comment by crftwrk** [comment]
> Right, got that... but would it not be more adequate to add img-fluid to the markup of those images?

Yes, of course. The link above leads to the WP test data which are used by the WP theme reviewers. We have to check all images on this site. Quickly checked the offcanvas cart images, they affected as well for example.

**Comment by crftwrk** [comment]
Double checked the boiler template, and this snippet is still present. Figured out that the `img` selector is used for the classic editor while `html :where(img[class*=wp-image-])` is used in blocks.

Generate a theme on [Underscores](https://underscores.me) and check line `519` in `style.css`. Think we should not do there any changes.
