### ISSUE TITLE
Pagination loads sr-only span, which is deprecated in BS 5.3

### ISSUE THREAD

**Issue by smileBeda** [bootscore/bootscore#614]
### Describe the bug

It appears to me the parent theme loads `Page navigation` span with class `sr-only` which is not anymore part of Bootstrap, instead, `visually-hidden` should be used, if I understand https://getbootstrap.com/docs/5.3/getting-started/accessibility/#visually-hidden-content properly. And as a matter of facts I can see (and I am not señor yet) the `Page navigation` string on the screen even if I am not using assistive tech. 

It does not appear as an issue as long you keep the FA styles - but as soon you dequeue them (which I do regularly, as I use BS Icons), the `sr-only` has no CSS anymore.
That CSS indeed comes from FA styles as far I can see.

My suggestion is to fully replace the class with `visually-hidden` so even if one dequeues FA, the assistive class does not "fail"

I might miss something.. please let me know before I do a PR

### Steps to reproduce

- Install Theme 
- Dequeue FA
- Load an archive that has more than one page.

### Screenshots and Additional Info

<img width="926" alt="Screenshot 2023-10-29 at 15 42 39" src="https://github.com/bootscore/bootscore/assets/11800236/5c6280af-2605-409c-9376-66d9311cc964">

https://github.com/bootscore/bootscore/blob/042759bc6f7843e1ba1d39ead8a80fb45f5c75b2/inc/pagination.php#L36
https://github.com/bootscore/bootscore/blob/042759bc6f7843e1ba1d39ead8a80fb45f5c75b2/inc/pagination.php#L49

**Comment by crftwrk** [comment]
Yes, you‘re right. This seems to be left over from Bootstrap 4. Want to quickly create a PR?

**Comment by smileBeda** [comment]
I’ll send you the pr first thing in the (my) morning.
