### ISSUE TITLE
HTML5 compliance for pagination

### ISSUE THREAD

**Issue by smileBeda** [bootscore/bootscore#619]
### Describe the bug

As per HTML5 the `nav` element does not require a `navigation` role, we can remove it.

Not sure if you want to keep it though. Pre-PR clarifying that.

### Steps to reproduce

1. Install Bootscore theme
2. Run HTML5 validation on a paginated element

### Screenshots and Additional Info

Source at https://github.com/bootscore/bootscore/blob/cc2f622eea250a683efaef29e47fc6ac22d2c6fe/inc/pagination.php#L35
Suggested edit: remove `role="navigation`

**Comment by crftwrk** [comment]
Agree, PR?
