### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by yourdigitalcanvas** [bootscore/bootscore#62]
I am working on my clients website. When I activate either bootscore-main or the bootscore child I created I get a 500 server error (see screenshot). If I activate a different wordpress theme eg TwentyTwentyOne there is no error.
![Screenshot from 2021-12-24 13-14-01](https://user-images.githubusercontent.com/70503253/147327984-ec53836e-246a-430b-8ceb-d74c900c4a54.png)
When I activate the theme on my own server dev site there is no error.
Does anyone know if there are some server settings or something that would cause this to happen.
Thanks in advance.

**Comment by justinkruit** [comment]
Could you please share some PHP error logs from the server? This should show why the 500 error accured.

**Comment by crftwrk** [comment]
It is possible that the server's PHP memory limit is too low for scssphp.

Please try to install version 5.1.1.0 https://github.com/bootscore/bootscore/releases/tag/v5.1.1.0 without compiler. If that works install latest version again and increase PHP memory limit in `.htaccess` or server settings in hoster's admin panel.

**Comment by crftwrk** [comment]
Haven't heard anything here for a while. Close the issue now.
