### ISSUE TITLE
[BUG] Description Sidebar LEFT

### ISSUE THREAD

**Issue by zsvendo** [bootscore/bootscore#628]
### Describe the bug

I need the sidebar to be on the left but I found that if you put order-md-last on line 30 as mentioned in woocommerce.php it would work but it doesn't, in fact just changing the columns.php file removing the order-md-last class , but I don't want to touch the original files. What is the resolution?

**Comment by crftwrk** [comment]
Duplicate of https://github.com/orgs/bootscore/discussions/627
