### ISSUE TITLE
Get wp_title() in header.php

### ISSUE THREAD

**Issue by neralex** [bootscore/bootscore#638]
### Describe the bug

I'm trying to retrieve the title string with function wp_title() in the header.php before wp_head() is called with an empty result. It works in other themes but it seems to be supressed in this theme. How I can get it back to work?

Reference: 
https://developer.wordpress.org/reference/functions/wp_title/

### Steps to reproduce

```
$page_title = wp_title('&#8211;', false, 'right');
echo $page_title; // just empty but why?
wp_head();
```

**Comment by crftwrk** [comment]
Why not simply use `<?php the_title(); ?>`?

**Comment by neralex** [comment]
Becauase It returns only the title of a post or page and if you have a page as "Front page", then you will get only the title of the page and not the title of the whole site.

I need this for the og:title meta-tag. How did you got it solved on bootscore.me?

`<meta property="og:title" content="bootScore » A powerful free Bootstrap 5 WordPress Starter Theme">`

**Comment by crftwrk** [comment]
Backend Settings > General - Site Title and tagline

<img width="966" alt="screenshot" src="https://github.com/bootscore/bootscore/assets/51531217/28cf9107-372e-438b-8de5-f732fc3163c0">

**Comment by neralex** [comment]
There is all fine on my settings. I just disabled all plugins and tried it with the main- and with child-theme but I'm getting the same empty result. Yoast is to much to fill some simple meta-values in the header.php.

**Comment by crftwrk** [comment]
Can't explain why your code does not work. On bootscore.me it's done with Yoast. But you can load site name and description as well.

- `<?php bloginfo('name'); ?>`
- `<?php bloginfo('description'); ?>`
- `<?php the_title(); ?>`


And put something like this to your `head`:

```php
<title><?php bloginfo('name'); ?> » <?php the_title(); ?></title>
```
