### ISSUE TITLE
my-offcanvas-account separeted offcanvas login and register

### ISSUE THREAD

**Issue by Lo1176** [bootscore/bootscore#64]
Hi!
First of all, I wish you all the best for you and your bootscore theme!

I was thinking of the register page/offcanvas.
Don't you think that it would be less confusing to separate the login from the registration.
That the # offcanvas-user opens a registration offcanvas with a "link"/new_offcanves at the bottom for "already registered users"?

**Comment by crftwrk** [comment]
Hi Lo,

thank you, a happy new year to you too.

The offcanvas Login/Registration is just a modified (classes and ids) copy of `my-account.php`. We will not do changes like  splitting Registration/Login in separate files. 

BTW, it makes no sense to have a registration form on a shop where users can create an account without buying anything. You might get a lot of fake users. Account should be created in checkout process, that's why in default WooCommerce settings the registration is switched off.

**Comment by Lo1176** [comment]
Good remark, you're right.
But I'm going to need users to log in to validate the warranty for a product they've been offered. So I will do something like that.

**Comment by crftwrk** [comment]
Perfect ;-)

**Comment by cdsaenz** [comment]
> Hi Lo,
> 
> thank you, a happy new year to you too.
> 
> The offcanvas Login/Registration is just a modified (classes and ids) copy of `my-account.php`. We will not do changes like splitting Registration/Login in separate files.
> 
> BTW, it makes no sense to have a registration form on a shop where users can create an account without buying anything. You might get a lot of fake users. Account should be created in checkout process, that's why in default WooCommerce settings the registration is switched off.

Happy new year! Thanks a lot guys, I was scratching my head and 1) thanks for the confirmation about registration generating trash (even with a captcha which I thought of). 2) I never did a registration and didn't know there was *another* checkbox in woo! I was using the Wordpress general setting! Found out thanks to Bootscore code :)

Now figuring out the best way to set this up (below picture). I think  `Allow customers to create an account on "My Account" page` should be off but I need to try it out. I guess letting the buying customer create an account if they want to it's alright. Without a purchase, not so sure.

![image](https://user-images.githubusercontent.com/2335805/211109910-fc0bdcd6-1870-4de1-a18d-a4edba1ddd2c.png)

**Comment by Lo1176** [comment]
Happy new year to all of you.
🍀🚀🔥

**Comment by crftwrk** [comment]
Happy new year!

I reopened this issue, so we have it on the radar.

`my-offcanvas-account.php` is a copy with modified id's and classes of https://github.com/bootscore/bootscore/blob/main/woocommerce/myaccount/form-login.php. So, both offcanvas login and default Woo login https://bootscore.me/account/ should have the same functionality.

@cdsaenz do your settings with default Woo login?

**Comment by cdsaenz** [comment]
Oh good info.  My partner asked me about this (allowing the user to create an account, forcing them to register etc) and I thought it wasn't that easy (I was playing with wp-signup at first). But the basics are there I see!

In line with what you said I wouldn't allow registration without buying, but they have some special prices for certain types of business so early registration might be required. I may make a custom register form with a *customer type* field etc and capture the data in `woocommerce_register_post` , who knows. 

If I add fields maybe the form will not be in the offcanvas, but full screen, thanks to the info you provided above about `form-login.php` being basically the same as `my-offcanvas-account.php`

I will also use all this learning in this inherited customer site (not Bootscore) to add more fields to the registration form they offer (in design they resolved it interestingly with a title link to show either login or register)
[https://ottech.ar/my-account-2/](url)

**Comment by crftwrk** [comment]
All new fields added to `form-login.php` must be added in `my-account-offcanvas.php` as well. But note that `my-account-offcanvas.php` **is not** a Woo template and cannot be overriden in the same way. When storing a copy of it in your child, path to it must be changed in `header.php` from main-theme to child.

Find:
`<?php include get_template_directory() . '/woocommerce/myaccount/my-account-offcanvas.php'; ?>`

Replace:
`<?php include get_stylesheet_directory() . '/woocommerce/myaccount/my-account-offcanvas.php'; ?>`

Does this help?

**Comment by cdsaenz** [comment]
I *just* found about that yes, good tip, thanks :)

**Comment by crftwrk** [comment]
Perfect 👍
