### ISSUE TITLE
New GDPR cookie plugin ready to test

### ISSUE THREAD

**Issue by crftwrk** [bootscore/bootscore#65]
https://github.com/bootscore/bs-cookie-settings

Live demo on a client site: https://intelligent-heizen.info

@justinkruit, @Axos11 , @Lo1176 let me know what you think.

**Comment by Lo1176** [comment]
Everything looks good in this new plugin cookie.
Didn't try it yet in a WP site because I already use one. But I'll try it in the future and give you my humble opinion.
