### ISSUE TITLE
[Feature Request] Remove limitation wpsites_query

### ISSUE THREAD

**Issue by sir-lexonarkz** [bootscore/bootscore#653]
### Describe the feature that you'd like

Remove posts per page from code

### Why is this feature needed? What problem does it solve?

I don't know what the point of this function is, it puts all the archives at 24 posts per page and if we use pre_get_posts in our file it doesn't work.

### Checklist

- [X] I have searched the issues and this feature has not been requested.

**Comment by crftwrk** [comment]
What do you mean? You can use a simple function to set amount of posts?

```php
function wpsites_query($query) {
  if ($query->is_archive() && $query->is_main_query() && !is_admin()) {
    $query->set('posts_per_page', 100);
  }
}
add_action('pre_get_posts', 'wpsites_query');
```

**Comment by sir-lexonarkz** [comment]
No, for it to work in my file I have to put it in higher priority (11), it took me a moment to see that it came from the loop.php file and so I asked myself the question of why Bootscore had put that by default for all archives especially since it can be configured in the WordPress reading settings.

**Comment by crftwrk** [comment]
> since it can be configured in the WordPress reading setting.

You're right, seems the script is from a time when that wasn't possible. Want to create a PR?
