### ISSUE TITLE
Unable to close a photo from the media gallery when enlarged or go back

### ISSUE THREAD

**Issue by akvrmvlakis** [bootscore/bootscore#666]
### Describe the bug

When an image from the media gallery is clicked in order to enlarge it it then goes to the media gallery url where the image is hosted but there is no option to close it or go back. I am inspecting the page and it seems pretty raw there's not much to do. I am unable to find a lightbox option to disable as advised on other wordpress themes. I would appreciate your help and suggestions very much. Thanks

### Steps to reproduce

Click on any image on this page: https://etsak.cloud/clinic/

### Website link

https://etsak.cloud/clinic/

**Comment by crftwrk** [comment]
Hi,

if you using an image block, there is an option to enable the lightbox. See https://dev.bootscore.me/theme/blocks/

![Lightbox](https://github.com/bootscore/bootscore/assets/51531217/1871957f-6d02-4f53-8c02-2e5ec6e74283)


Your images are in a `hcf-isotope-item` and I do not know if it's custom coded or a plugin, but this has nothing to do with the theme.

```html
<div class="col-12 col-md-6 hcf-isotope-item">
  <a class="hcf-masonry-card" href="http://etsak.cloud/wp-content/uploads/2023/12/masonry-1.jpg">
    <img class="card-img img-fluid" loading="lazy" src="http://etsak.cloud/wp-content/uploads/2023/12/masonry-1.jpg" alt="">
  </a>
</div>
```

You should check if code/plugin supports lightbox gallery.

**Comment by akvrmvlakis** [comment]
Hello Basti, It's raw html code I got from a snippet in order to create a quick masonry effect I am not using any plugins as of yet and not using gutenberg blocks either but it happens in all my Bootscore projects and I think it makes sense because when clicked it takes the visitor to the image url and there shouldn't be anything there. I will consider using either Gutenberg blocks (I suck at php and will have to find a way to add it within the page templates..) or a lightbox plugin. Yes the child is complaining due to some custom JS code for the image slider on the main page I haven't found a way around it yet but the fullscreen slider is working so I am leaving it for last :) Thanks for your time and the help I will go with either of the above discussed options. I wish you a happy new year my friend!

**Comment by akvrmvlakis** [comment]
Btw the lightbox on https://dev.bootscore.me/theme/blocks/ looks awesome! :))) This is exactly what I am looking for. I can't wait for the next Bootscore release. Thanks

**Comment by crftwrk** [comment]
> It's raw html code I got from a snippet in order... happens in all my Bootscore projects and I think it makes sense because when clicked it takes the visitor to the image

Does this snippet work with other themes?

**Comment by akvrmvlakis** [comment]
Yeah definitely I suppose especially with static sites and other Bootstrap-based themes I got it from here: https://htmlcssfreebies.com/demo/?id=850

**Comment by crftwrk** [comment]
This is a HTML site and images do not open in a lightbox. WordPress links all media files to the library by default, that is different to HTML sites. If you want that images open in a lightbox you need a script which supports this for example http://feimosi.github.io/baguetteBox.js/.

Question: Does your code work well with a default WP theme like https://wordpress.org/themes/twentytwentyone/?

**Comment by akvrmvlakis** [comment]
Thank you very much Basti the Lightbox JS script looks like a lifesaver! I will def use it :) Not sure I understand what you mean if the code is working with another theme It is endless Bootstrap classes meant to work only on Bootscore. What I do is just create page templates from scratch I just include the get_header() and get_footer(), I leave the #content# #primary and #main and all the rest is pure Bootstrap. All of this thanks to you guys and the excellent piece of work you've put out that's called Bootscore! :)))

**Comment by crftwrk** [comment]
> Not sure I understand what you mean if the code is working with another theme

I am asking this, because we have to check if this is a bug in Bootscore theme or not. If something works fine with other themes and not working here, we have to fix this.

BTW, coming back to your code. The image src is linked, that's why click on image leads to the media source:

```html
<div class="col-12 col-md-6 hcf-isotope-item">
  <a class="hcf-masonry-card" href="http://etsak.cloud/wp-content/uploads/2023/12/masonry-1.jpg">
    <img class="card-img img-fluid" loading="lazy" src="http://etsak.cloud/wp-content/uploads/2023/12/masonry-1.jpg" alt="">
  </a>
</div>
```

Why not simply remove the link?

```html
<div class="col-12 col-md-6 hcf-isotope-item">
  <div class="hcf-masonry-card">
    <img class="card-img img-fluid" loading="lazy" src="http://etsak.cloud/wp-content/uploads/2023/12/masonry-1.jpg" alt="">
  </div>
</div>
```

**Comment by akvrmvlakis** [comment]
Thank you very much for taking the taking the time to look into this Basti I will definitely use the Lightbox script you recommended.
