### ISSUE TITLE
Create assets folder

### ISSUE THREAD

**Issue by justinkruit** [bootscore/bootscore#669]
The amount of folders in the main folder is growing and growing. Do we want to switch to using an /assets folder?
That way we can put /css, /img, /js, /scss and /fontawesome in folder.

This can be a breaking change in our new big version.

**Comment by crftwrk** [comment]
/css folder does not exists and moving compiled css will break existing installations. When moving /scss files we have to rewrite paths?

**Comment by justinkruit** [comment]
> /css folder does not exists and moving compiled css will break existing installations. 

Yes, they'll need to change the path in the enqueue.php file. The SCSS compiler will put it in the new place for them. But the SCSS itself will also need to be moved. As why I suggest it for the next big release, which will most likely have more breaking changes.

> When moving /scss files we have to rewrite paths?

No, only the import folder path needs to be changed in the SCSS compiler. The relative paths being used in the SCSS itself stay the same.

**Comment by r3fl3x** [comment]
Hi, I think it's a good idea to merge the folders under the assets folder. It turns out that the child theme will also have changes as a result, right?

**Comment by crftwrk** [comment]
Added this to v6, there we can do what we want. We also have to make a plan where we want to go https://github.com/orgs/bootscore/discussions/655.
