### ISSUE TITLE
[BUG] Potential Woocommerce Bug in the Slide out Basket 

### ISSUE THREAD

**Issue by hsankala** [bootscore/bootscore#674]
### Describe the bug

I'm seeing a malformed infomation and error message in the Slide out, Cart.  After upgrading to WooCommerce 8.5.1, this issue was not seen in WooCommerce Version 8.4.0, when running latest Bootscore theme  5.3.4

Here is the add message in the cart: 

![image](https://github.com/bootscore/bootscore/assets/14014749/c10a2583-e4a3-4d2a-a027-a9694cd745d9)

Also, the error message is not formatted correctly:

![image](https://github.com/bootscore/bootscore/assets/14014749/368866b7-fe32-4537-87f6-9984a28f5cdd)

I'm expecting messages to look like this:

![image](https://github.com/bootscore/bootscore/assets/14014749/ad597db3-227d-4016-a5c4-1c1aac3644ce)

In WooCommerce 8.4.0 the error message markup looks like this:

```
<ul class="woocommerce-error" role="alert">
<li>
      <a href="https://mysite.com/basket/" class="button wc-forward">View basket</a> You cannot add that amount to the basket — we have 1 in stock and you already have 1 in your basket.		
</li>
</ul>

```

But after upgrading to WC 8.51 the error message HTML has changed

```
<div class="wc-block-components-notice-banner is-error" role="alert">
	<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" focusable="false">
		<path d="M12 3.2c-4.8 0-8.8 3.9-8.8 8.8 0 4.8 3.9 8.8 8.8 8.8 4.8 0 8.8-3.9 8.8-8.8 0-4.8-4-8.8-8.8-8.8zm0 16c-4 0-7.2-3.3-7.2-7.2C4.8 8 8 4.8 12 4.8s7.2 3.3 7.2 7.2c0 4-3.2 7.2-7.2 7.2zM11 17h2v-6h-2v6zm0-8h2V7h-2v2z"></path>
	</svg>
	<div class="wc-block-components-notice-banner__content">
		<a href="https://mysite.com/basket/" class="button wc-forward">View basket</a> You cannot add that amount to the basket — we have 1 in stock and you already have 1 in your basket.	</div>
</div>
```

**Comment by crftwrk** [comment]
Yes, https://bootscore.me/blog/woocommerce-8-5-issues/. There you will find a download link to a patch which fixes the alerts.

**Comment by hsankala** [comment]
Didn't think to look on your blog, ohh some nasty surprises in woo 8.5!  

No worries on the site, I spotted this on staging before upgrading the live site so will wait until the next release for the fixes.

Many thanks.
