### ISSUE TITLE
[BUG/Help Wanted] Pagination for Post

### ISSUE THREAD

**Issue by gurpreetbhachu** [bootscore/bootscore#677]
### Describe the bug

Hi Team,

Came across an issue in the pagination of the posts.
Please correct me if I am wrong.

Pagination is not correct, I thought there is something on my website that has caused this issue but Today I realized that same thing is on your official site.

As per the image (screenshot - https://bootscore.me/documentation/theme/alert-icons/)
Currently I am on Alert page and the pagination is displaying "Font Awesome" is next post/page. Shouldn't be the "Google Font" be the next?

![image](https://github.com/bootscore/bootscore/assets/35268356/8f1638ef-a22f-4bda-bb06-09a87b7ff5a3)

Also, I **need help** - How can rename pagination as "Next Post/Previous Post" instead of post title? because long post title disturbs the responsive design.

Regards,
Gurpreet

### Steps to reproduce

1. Go to Any post.
2. For example: https://bootscore.me/documentation/theme/alert-icons/
3. Check the Pagination

### Screenshots and Additional Info

![image](https://github.com/bootscore/bootscore/assets/35268356/9d1ffa8f-f114-4a97-bdc2-cdaa487f1518)

N= Should be Next Post
P= Should be Previous Post

### Website link

https://bootscore.me/documentation/theme/alert-icons/

**Comment by gurpreetbhachu** [comment]
Hi,

Adding more to my previous message.

Pagination works normal on localhost.
![image](https://github.com/bootscore/bootscore/assets/35268356/163a4835-2848-44dd-8d35-fa9505dc2f7b)

Thanks
Gurpreet

**Comment by crftwrk** [comment]
Hello Gurpreet,

no, this isn't a bug, let me explain. In the [WordPress Developer Resources](https://developer.wordpress.org/reference/functions/next_posts_link/), they say:

> Because post queries are usually sorted in reverse chronological order, [next_posts_link()](https://developer.wordpress.org/reference/functions/next_posts_link/) usually points to older entries (toward the end of the set) and [previous_posts_link()](https://developer.wordpress.org/reference/functions/previous_posts_link/) usually points to newer entries (toward the beginning of the set).

Pagination is in all `single-*.php` files, `previous_post_link` links to newer and `next_post_link` to older posts.

https://github.com/bootscore/bootscore/blob/d5020992453713aa0d5040c0ac32066fe8bbfe17/single.php#L52-L57

Having a look to the publishing date, you will see that Google Fonts post is older while Font Awesome post is newer than the Alert icons post. 


![screenshot](https://github.com/bootscore/bootscore/assets/51531217/a61a6117-1f9d-4b05-a5c0-b23e25f7c463)

You can simply change the direction by switching those lines, placing the `next_post_link` above the `previous_post_link`. In this case you need a bit of additional CSS to get `«` `»` in place, but this is not a big deal.

> Also, I need help - How can rename pagination as "Next Post/Previous Post" instead of post title? because long post title disturbs the responsive design.

This can also be achieved in the `single-*.php` files by adding the string to the snippet:

```php
<?php previous_post_link( '%link', 'Previuos post' ); ?>
``` 
and 
```php
<?php next_post_link( '%link', 'Next post' ); ?>
```

| Before  | After |
| ------------- | ------------- |
| <img width="691" alt="before" src="https://github.com/bootscore/bootscore/assets/51531217/ce2a7dbc-8173-4974-8cea-6d468ab6de74">  | <img width="696" alt="after" src="https://github.com/bootscore/bootscore/assets/51531217/470cfdc6-059e-42cb-be0e-11cf5b20d319"> |

Solved?

Basti

**Comment by gurpreetbhachu** [comment]
Hi Basti,

Yes, Solved.
Thank you for your help :)

Regards,
Gurpreet
