### ISSUE TITLE
Reason of using fixed-top

### ISSUE THREAD

**Issue by justinkruit** [bootscore/bootscore#692]
What is the reason we're using `fixed-top` for the header?
In this case, wouldn't it actually be better to use a sticky position on the header tag itself?

That way we can also immediately replace some stuff like the following:
```scss
html,
body,
#page {
  height: 100%;
}
```

Which results in the #page height not going fully with the page content (this is the #pade div highlighted in devtools):
![image](https://github.com/bootscore/bootscore/assets/1642830/94a5c33b-7cc6-4b66-88c4-2bb9014120f1)

**Comment by crftwrk** [comment]
Have this already on the list, check here https://projekte.crftwrk.de/boilerplate-sample-content/

After the filters PR is merged, I want to open a new v6 branch and go wild. 😜
