### ISSUE TITLE
Fatal error in checkout

### ISSUE THREAD

**Issue by 7Rinzler** [bootscore/bootscore#70]
![FireShot Capture 007 - Finalizar compra – Osmar - osmar solutions](https://user-images.githubusercontent.com/62086058/148811827-bac6bedf-eca3-4454-905e-7342e3e3aedb.png)
Fatal error: Uncaught Error: Call to undefined function bootscore_wc_get_corrected_terms() in /home/osmarsol/public_html/wp-content/themes/bootscore-main/woocommerce/checkout/terms.php:14 Stack trace: #0 /home/osmarsol/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include() #1 /home/osmarsol/public_html/wp-content/themes/bootscore-main/woocommerce/checkout/payment.php(49): wc_get_template('checkout/terms....') #2 /home/osmarsol/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/home/osmarsol/...') #3 /home/osmarsol/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php(2337): wc_get_template('checkout/paymen...', Array) #4 /home/osmarsol/public_html/wp-includes/class-wp-hook.php(303): woocommerce_checkout_payment('') #5 /home/osmarsol/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #6 /home/osmarsol/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #7 /home/osmarsol/public_ht in /home/osmarsol/public_html/wp-content/themes/bootscore-main/woocommerce/checkout/terms.php on line 14

**Comment by crftwrk** [comment]
Yes, that's because it seems that you want to use a shop with bootscore-child theme. This child has no WooCommerce support. 

You have to install bootcommerce-child https://bootscore.me/shop/products/child-themes/bootcommerce-child-theme/ to activate WC. 

Check also WC docs https://bootscore.me/documentation/woocommerce/

Solved?

**Comment by crftwrk** [comment]
Haven't heard anything here for a while. Close the issue now.
