### ISSUE TITLE
Text instead of logo

### ISSUE THREAD

**Issue by starwebgraphics** [bootscore/bootscore#76]
Is there a way to force the theme to use the text header instead of the logo? The option appears missing in the site settings and theme customization. My client does not have a log and I want to revert back to the text header. I tried deleting the logo from the server thinking that it might revert back to text but it didn't. It was still being dynamically generated. Do I need to change something in header.php? Or just the CSS style?

**Comment by crftwrk** [comment]
Theme has no customizer settings. All changes must be made by code. But, that's super-simple. If you haven't done already, copy header.php to your child.

In lines 49 and 50 you will find this:

```html
<a class="navbar-brand xs d-md-none" href="<?php echo esc_url(home_url()); ?>"><img src="<?php echo esc_url(get_stylesheet_directory_uri()); ?>/img/logo/logo-sm.svg" alt="logo" class="logo xs"></a>
<a class="navbar-brand md d-none d-md-block" href="<?php echo esc_url(home_url()); ?>"><img src="<?php echo esc_url(get_stylesheet_directory_uri()); ?>/img/logo/logo.svg" alt="logo" class="logo md"></a>

```

Replace both lines with this and change text:

```html
<a class="navbar-brand" href="<?php echo esc_url(home_url()); ?>">My new text</a>
```

Does this help?

**Comment by starwebgraphics** [comment]
thanks :)

**Comment by crftwrk** [comment]
You're welcome
