### ISSUE TITLE
How to add additional top-bar with menu location

### ISSUE THREAD

**Issue by sheherezade88** [bootscore/bootscore#77]
I could not find this in the repository-- the old method of adding a top menu did not work (using php).  What is the correct way to add a new top menu (right justified) to bootscore theme?

**Comment by crftwrk** [comment]
What do you mean exactly. A top bar above the main nav with a registered nav-walker inside? Please describe a bit more detailed and maybe add a screenshot to better understand what you need.

**Comment by sheherezade88** [comment]
Yes, a top bar above the main nav (dropdown is not required but would be okay).  I would like to add menu items (links) and also buttons (like for social media links).

[Top-Menu-example.pdf](https://github.com/bootscore/bootscore/files/7945281/Top-Menu-example.pdf)

**Comment by sheherezade88** [comment]
I should have added this would be an additional menu location (designated as top menu).

**Comment by sheherezade88** [comment]
Oops did not mean to close the issue-- please help-- thank you!

**Comment by crftwrk** [comment]
> Oops did not mean to close the issue-- please help-- thank you!

All good ;-)

There are several ways to do this. If there are just three menu links, I would prefer hard-code this. Here are two ways to add a top-bar with social icons left and menu right. Change HTML classes as you want.

<img src="https://lh3.googleusercontent.com/pw/AM-JKLX3N3qsOeodEt8h3-grUwvF_fZlP_KMJx12b8clLvjkoXRZxgOli699JChSu3MpttYEUmgMzoNzCwjYfHHx3FnHTNyjXVPbUratnrECi-AyMxk1hw4e2YkISeQJdicIyE1cNL_ZkoPRKrBayPK_si5fOg=w1932-h230-no">

In header.php line 44 you will find div `class="fixed-top bg-light"`. Add top-bar direct after this.

```html
<div class="fixed-top bg-light">
<!-- paste top-bar here -->
```

### hard-code

This is the simplest way

#### header.php
```html
<!-- top-bar -->
<div class="bg-dark py-2">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <a class="text-light" href="#"><i class="fab fa-facebook-f"></i></a> <a class="text-light" href="#"><i class="fab fa-instagram"></i></a>
      </div>
    <div class="col-6 text-end">
      <a class="text-light" href="#">Menu item</a> <a class="text-light" href="#">Menu item</a>
    </div>
    </div>
  </div>
</div>
```

### Widget and nav-walker 

If you want to use a WordPress menu and a widget instead, register both in your functions.php

#### functions.php

```php
// Top-bar menu
register_nav_menu('top-bar-menu', 'Top bar menu');

// Register top-bar widget
function top_bar_widget_init() {
  // Top Nav
  register_sidebar(array(
    'name' => esc_html__('Top Bar', 'bootscore'),
    'id' => 'top-bar-widget',
    'description' => esc_html__('Add widgets here.', 'bootscore'),
    'before_widget' => '<div class="your-class">',
    'after_widget' => '</div>',
    'before_title' => '<div class="widget-title d-none">',
    'after_title' => '</div>'
  ));
}
add_action('widgets_init', 'top_bar_widget_init');
```

and reference them in your header.

#### header.php
```php
<!-- top-bar -->
<div class="bg-dark py-2">
  <div class="container">
    <div class="row">
      <div class="col-6 text-light">
        <!-- Register widget -->
        <?php if (is_active_sidebar('top-bar-widget')) : ?>
            <?php dynamic_sidebar('top-bar-widget'); ?>
        <?php endif; ?>
        <!-- Register widget -->
      </div>
    <div class="col-6 text-end">
        <!-- Bootstrap 5 Nav Walker Main Menu -->
        <?php
        wp_nav_menu(array(
          'theme_location' => 'top-bar-menu',
          'container' => false,
          'menu_class' => '',
          'fallback_cb' => '__return_false',
          'items_wrap' => '<ul id="top-bar-menu" class="nav justify-content-end %2$s">%3$s</ul>',
          'depth' => 2,
          'walker' => new bootstrap_5_wp_nav_menu_walker()
        ));
        ?>
        <!-- Bootstrap 5 Nav Walker Main Menu End -->
      </div>
    </div>
  </div>
</div>  
```

Now add in WordPress backend a new menu and a widget.

Does this help?

**Comment by sheherezade88** [comment]
Thank you!  I will try this and let you know how it goes.
