### ISSUE TITLE
[Feature Request] A solution for a "Drill Down Menu"

### ISSUE THREAD

**Issue by anyway** [bootscore/bootscore#770]
### Describe the feature that you'd like

A solution for a "Drill Down Menu", like the one in "Foundation CSS", would be very nice.
[Drill Down Menu](https://get.foundation/sites/docs/drilldown-menu.html)

So that the submenus of the mobile nav don't expand downwards, but slide sideways.

### Why is this feature needed? What problem does it solve?

Some customers ask for it and think of it as standard.

### Checklist

- [X] I have searched the issues and this feature has not been requested.

**Comment by Remzi1993** [comment]
If it's not standard in Bootstrap then it means the team needs to implement it and that would be either too much work or out of scope of this WP theme since it's a theme based on Bootstrap.

I'm just thinking out loud and maybe it's easy to implement. I don't think this is something standard in the web industry. There are all kinds of menu's and this is just one of the most use UI elements like the Hamburger menu or 3 dots.

**Comment by crftwrk** [comment]
Agree that this would be a nice feature. However, as @Remzi1993 mentioned, it would be too much work to develop and maintain in the long term. 

Additionally, it's not a Bootstrap component, meaning we would be adding a new component that doesn't exist in Bootstrap. We previously did this with offcanvas and dark mode, which were implemented here long before they were available in Bootstrap. Migrating them to Bootstrap's default components was challenging. As a result, we strictly follow Bootstrap and do not add new components that do not exist in Bootstrap. Better to open a [feature request](https://github.com/twbs/bootstrap/issues) there.

If someone has the time and wants to code a drill down menu, we can share it here and add a note to the documentation, but it will not be included in the theme's core.

**Comment by anyway** [comment]
Thank you very much for your detailed comment. Your reasons are absolutely understandable. Programming and maintaining the walker on its own is probably a lot of work, I am absolutely aware of that. If someone already has a working solution that integrates well with Bootstrap and WordPress, I would be happy to hear it. And I will open a feature request at Bootstrap at the next opportunity.

**Comment by crftwrk** [comment]
You're welcome 👍
