### ISSUE TITLE
thumbnails in loops are not rectangular

### ISSUE THREAD

**Issue by gurkenschnitzel** [bootscore/bootscore#78]
Hey guys - l am not sure if this is the right place - When I do loops in a page the preview thumbnails of posts sometimes are rectangular ..... Sometimes not. I am not sure if this a WP problem or a bootscore problem? I am not the big php master-but my css is good and I can't find a clue to this problem... Cheers As

**Comment by crftwrk** [comment]
Hi,

please share a link to your site to reproduce the issue. Thanks.

**Comment by gurkenschnitzel** [comment]
it's local sorry

**Comment by crftwrk** [comment]
https://bootscore.me/documentation/support-contribute/

Unfortunately it's impossible to check issues on your local computer ;-) If you want that we check this, please transfer your site to a live server and share a link.
