### ISSUE TITLE
[BUG] Plugin incompability: YITH Woocommerce Advanced Reviews

### ISSUE THREAD

**Issue by orjansteffensen** [bootscore/bootscore#789]
### Describe the bug

This is more FYI, than an urgent issue.

YITH Woocommerce Advanced Reviews recently had a larger update, after which it did not work on Bootscore. (It worked before this update.) I've also tested on other themes where it worked fine.

YITH have looked at it, and found that the code on line 19 in woocommerce/inc/wc-forms.php is what breaks it. 

```
add_action('wp_enqueue_scripts', 'bootscore_dequeue_stylesandscripts_select2', 100);
```

Did not seem to work to comment this out in child theme. Which means for now, that I need to take care after theme updates.

**Comment by crftwrk** [comment]
Thank you for pointing this out. May I ask you what exactly do this with the plugin?

We can make this function pluggable, so you can disable it simply by adding the empty function in your child. Go to:


https://github.com/bootscore/bootscore/blob/36d69fadc5ba98595edd5c96c8a9a99687ca6dbf/woocommerce/inc/wc-forms.php#L15-L29


And replace entire snippet with:

```php
/**
 * Remove CSS and/or JS for Select2 used by WooCommerce
 * https://gist.github.com/Willem-Siebe/c6d798ccba249d5bf080.
 */
if (!function_exists('bootscore_dequeue_stylesandscripts_select2')) {
  function bootscore_dequeue_stylesandscripts_select2() {
    if (class_exists('woocommerce')) {
      wp_dequeue_style('selectWoo');
      wp_deregister_style('selectWoo');

      wp_dequeue_script('selectWoo');
      wp_deregister_script('selectWoo');
    }
  }
}

add_action('wp_enqueue_scripts', 'bootscore_dequeue_stylesandscripts_select2', 100);
```

Now add empty function to your child's `functions.php`:

```php
function bootscore_dequeue_stylesandscripts_select2() {

}
```

Let me know if that helps.

**Comment by justinkruit** [comment]
No need to make it pluggable 😉 
```php
remove_action('wp_enqueue_scripts', 'bootscore_dequeue_stylesandscripts_select2', 100);
```

Put this line in the child theme for the time being, and it will work.

**Comment by orjansteffensen** [comment]
Thanks for helping. 

> May I ask you what exactly do this with the plugin?

Here's what YITH wrote:
> Your theme removes the SelectWoo script that the plugin needs. As a result, all plugin scripts are not loaded because of this missing dependency.
> The problem is located in this file here: wp-content/themes/bootscore-main/woocommerce/inc/wc-forms.php

Tested the solutions above.
- remove_action() in child functions.php did not work.
- The first solution did work, but wc-forms.php will of course be overwritten when updating, so I'll have to remember that.

**Comment by crftwrk** [comment]
I can confirm that `remove_action()` won't work.

> The first solution did work, but wc-forms.php will of course be overwritten when updating, so I'll have to remember that.

That's why we should fix this general.

**Comment by orjansteffensen** [comment]
Sorry, I forgot to save the user. Here's a new id: JhvsUNsHUuOWHR1cwzqmFCwicjus886D

**Comment by justinkruit** [comment]
Seems like my original code worked, just not in the correct order. Because a child theme gets initialized before a parent theme, it triggers the remove_action before the add_action. With the following code, the remove_action gets triggered after the themes have been loaded, resulting in successfully removing the action!

```php
function remove_parent_theme_function() {
    remove_action('wp_enqueue_scripts', 'bootscore_dequeue_stylesandscripts_select2', 100);
}
add_action('after_setup_theme', 'remove_parent_theme_function');
```

I've put the code in your child's functions.php, and restored the wc-forms.php file in the main theme as original. This way your main theme is safe to be updated again without getting errors.

**Comment by orjansteffensen** [comment]
Great, thanks for your help! Much appreciated.
