### ISSUE TITLE
[BUG] Outdated WooCommerce template: bootscore/woocommerce/myaccount/navigation.php

### ISSUE THREAD

**Issue by Remzi1993** [bootscore/bootscore#795]
### Describe the bug

WooCommerce is reporting that there is an outdated WooCommerce template: bootscore/woocommerce/myaccount/navigation.php

### Screenshots and Additional Info

![Screenshot 2024-06-20 160003](https://github.com/bootscore/bootscore/assets/980950/01def98d-0b6b-4a93-aeef-9e6b8a069b0a)

**Comment by crftwrk** [comment]
- https://bootscore.me/blog/woocommerce-9/
- https://github.com/bootscore/bootscore/pull/788

**Comment by Remzi1993** [comment]
> * https://bootscore.me/blog/woocommerce-9/
> * [Minor fixes to v6 stable #788](https://github.com/bootscore/bootscore/pull/788)

Thanks for the quick reply. May I ask what's stopping the merge of #788?

**Comment by crftwrk** [comment]
There are still 4 PR‘s for stable release open that are not ready to review yet included this one you mentionend.

**Comment by Remzi1993** [comment]
Okay, thanks for the clarification. 👍😊

**Comment by crftwrk** [comment]
You‘re welcome. Think in two weeks it should be ready.
