### ISSUE TITLE
Conflict with WooCoommerce/Subscriptions

### ISSUE THREAD

**Issue by smileBeda** [bootscore/bootscore#799]
### Describe the bug

When adding a variable product to cart (from single product page) the spinner spins forever, however the product IS added to cart. 

### Steps to reproduce

1. I setup fresh WP Install with BS theme (no child)
2. Added WooCommerce and WooCommerce Subscriptions (but happens also with just WC)
3. Created a variable product with one variation (subscription monthly membership)
4. Tried to add that product to cart

### Screenshots and Additional Info

<img width="498" alt="Screenshot 2024-06-26 at 18 09 38" src="https://github.com/bootscore/bootscore/assets/11800236/bd461474-5215-4e00-ba92-cbde89d29553">

---

- Issue goes away immediately when using another theme, in which case, adding the product to cart will shortly spin the button spinner then reload the page and go to cart, as expected
- Product is added to cart ANYWAY, but page isn't reloaded and redirected to cart as it should (and does with another theme)
- No error in console
- Requests show that the product IS added to cart in network console
- Enable AJAX add to cart buttons on archives is active, but if deactivated, no change.

This issue happens only with the BS theme, child or parent, no matter. Parent is fresh download from two days ago via composer. Sole change to theme: _Change the name into what it should be: `bootscore` instead of `bootscore-main`_

**Comment by crftwrk** [comment]
Yes, if subscription plugin has setting that allows to change already purchased memberships from for example premium to basic, tha ajax cart is not able to handle this product settings. Please check https://bootscore.me/documentation/woocommerce/#ajax-cart for more info about ajax cart and subscription plugin and disable ajax cart as described on the same page.

**Comment by smileBeda** [comment]
This is unrelated. If it works on another theme, how could that be the issue? Also, as mentioned I did disable the option, at the same results.

**Comment by crftwrk** [comment]
Has the other theme an ajax cart?

**Comment by smileBeda** [comment]
There is no other item in the cart.

This issue is unrelated to cart since it works in another theme.

Note - the `checkout?add-to-cart=11111` where 11111 is variation ID, also doesnt work but works just fine with theme 2024

**Comment by crftwrk** [comment]
Again, here https://bootscore.me/documentation/woocommerce/#overview is described why subscription plugin may have conflicts with ajax cart if plugin has some special settings. Here is a reference issue https://github.com/bootscore/bootscore/issues/564. You must disable ajax cart and it will work fine.

**Comment by smileBeda** [comment]
But @crftwrk - this works juts fine on the same site with Theme 2024.
And, as said, it makes no difference, if the option for AJAX on archive is disabled.

This has absolutely nothing to do with AJAX.

Just call the url /checkout/?add-to-cart=146 where 146 is your variation ID.
It works with Theme 2024 (redirects to cart with product added to it). It redirects to empty cart with Theme BS.
Same result with or without AJAX enabled.

**Comment by crftwrk** [comment]
Yes, but what is Theme 2024?

**Comment by smileBeda** [comment]
![Uploading Screenshot 2024-06-26 at 18.34.32.png…]()
Native, default WordPress Theme.

**Comment by crftwrk** [comment]
But native WP theme has no ajax cart and you can restore default Woo settings by a filter as well https://bootscore.me/documentation/woocommerce/#disable-ajax-cart. There are no other changes made in Woo area.

**Comment by crftwrk** [comment]
Ah, maybe I got it. You cloned latest main branch. There where changes in 

Please download 6.0.0-beta1 https://github.com/bootscore/bootscore/releases and disable ajax cart, it should work.

There is already an open pr to fix that https://github.com/bootscore/bootscore/pull/792

**Comment by smileBeda** [comment]
Apparently with that new - breaking - version it works when that checkbox is disabled (which is still not how it should work IMO, since that is a setting for _archives_, not for single product add-buttons and even less for add-by-url-parameter, but I am fine with that).

Very reluctant however to do a migration to a breaking beta-1 because of a bug.

**Comment by smileBeda** [comment]
yeah no - sorry but I cannot use that theme version.

1. This is an extremely major break
2. It is not stable, and I cannot afford to put a beta version into live production sites
3. It appears to me there is just too much work required to even consider a migration. One better starts over once it is stable, and leaves 5.x versions at 5.x. 

---

I will see if the commits at https://github.com/bootscore/bootscore/pull/792/files are what fixes the issue of not being able to add ANY product to cart, when using direct URL like `checkout/?add-to-cart=146`, but I doubt it strongly.

This is very unfortunate. We cannot wait for business critical bugs existing in stable releases, to be fixed in major breaking future releases!
That is very disruptive.

Composer has indeed downloaded the latest stable is 5.3.4 from November, as that is what the version says I got from composer `Version: 5.3.4`.
It said `-main` in the folder name because of the whole wrong packaging to start with, but that is just a detail.

Truly unfortunate.

**Comment by smileBeda** [comment]
@crftwrk - if composer (I followed https://bootscore.me/documentation/installation/#Composer > method 1) would pull _main_, I would have this main style.css file in my local https://github.com/bootscore/bootscore/blob/main/style.css.
I don't, I have this: https://github.com/bootscore/bootscore/blob/v5.3.4/style.css

Testing results:
- if I _enable_ the "Enable ajax add to cart buttons on archives" and _disable_ the "Redirect to cart page after successful addition", then _simple products are added WITH AJAX (no page reload) to the cart when added from the archive_, and _variable products are added WITH AJAX (no page reload) to the cart when added from the single product page_. Same on v6 as on v5.
- if I _enable_ the "Enable ajax add to cart buttons on archives" and _enable_ the "Redirect to cart page after successful addition", then same as above, but I am also redirected to cart after the Ajax-add-to-cart happens (on v5, on v6 it will just use AJAX anyway and no redirect will happen), _for simple product_. For _variable product, the add to cart will be broken: spins indefinitely. BUT the product is added ANYWAY to the cart!_ (both on v5 and v6)
- If I disable both options, the entire experience is nuked on v5: add to cart won't even work anymore for simple product, because it still tries to do it with AJAX, even if the options are disabled. It works on v6 as expected in this case.
- in ALL those scenarios adding the product to cart using the URL `checkout?add-to-cart=146` is entirely broken, it never adds the product, both simple and variable. On v6, it is broken in all cases, unless I _disable_ the AJAX option, in which case it adds the product as expected using the URL.

I do struggle to understand how you can call any of this expected. This is clearly _not_ how things work in any other theme, with or without ajax, and the main issue is in the _stable_ variant of the BS Theme, as seen from the version downloaded by composer, not due to some unexpected checkout of main or else.
I use the add-to-cart url parameter very often on WC sites, and never had to disable the AJAX add to cart just to use that, this with or without WooCom subscriptions. I can however live with disabling that option, which at least on v6, appears to "resolve" things.

---

The problem I have with v6 is, I had a quick look at the migration documentation and starting at the first step:
> The folders scss, js, and img have been moved from the root location into the assets folder. Compiled CSS will be created now in /assets/css/main.css. As a result, the [enqueue script](https://github.com/bootscore/bootscore-child/blob/main/functions.php) in the child theme has been modified. If you have Google fonts installed as described [here](https://bootscore.me/documentation/google-fonts/), move fonts folder into assets as well.

That link leading to the example functions file leads to `main`. It has code in it as such:
```
function bootscore_child_enqueue_styles() {

  // Compiled main.css
  $modified_bootscoreChildCss = date('YmdHi', filemtime(get_stylesheet_directory() . '/assets/css/main.css'));
  wp_enqueue_style('main', get_stylesheet_directory_uri() . '/assets/css/main.css', array('parent-style'), $modified_bootscoreChildCss);

  // style.css
  wp_enqueue_style('parent-style', get_template_directory_uri() . '/style.css');
  
  // custom.js
  // Get modification time. Enqueue file with modification date to prevent browser from loading cached scripts when file content changes. 
  $modificated_CustomJS = date('YmdHi', filemtime(get_stylesheet_directory() . '/assets/js/custom.js'));
  wp_enqueue_script('custom-js', get_stylesheet_directory_uri() . '/assets/js/custom.js', array('jquery'), $modificated_CustomJS, false, true);
}
```

Is there any reason  you enqueue the child theme style _before_ the parent? Like it was done in the stable version see https://github.com/bootscore/bootscore-child/blob/v5.3.0/functions.php (it might just work, due to the $requires array set, but still, this is wrong)
**This led me to understand this is a _beta_ version, in development, bugs and issues are welcome and expected in it, but I couldn't use it for live sites.** 

If you can somehow guarantee that between the current _tag_ v6 and the planned-to-be stable release of v6 there won't be _breaking_ changes, I guess I could bite that sour apple and migrate my current work to this new version, which would at lest resolve the WooCommerce issue to a certain extent. But I am aware of hard it is to make such guarantees, specially when dev is still ongoing, so I am very wary of doing this step.

I hope you understand where Im coming from in this perspective?

**Comment by crftwrk** [comment]
To be honest, I do not know what version composer installs, maybe composer is not able to handle prereleases. But if that creates issues, I prefer to remove composer, pressing a download button and install via theme uploader isn't that difficult. In fact, use releases and not dev branches on production sites.

For the enqueue script, except the path to the `main.css` nothing has changed here compared to v5. If you have ideas for improvements, any PR is highly appreciated.

**Comment by smileBeda** [comment]
https://github.com/bootscore/bootscore-child/blob/5477d6c7b8c9ea6bd06314e18a86e597898baaa5/functions.php#L8-L12
vs
https://github.com/bootscore/bootscore-child/blob/4b9d151303f90206f53d0d9d3e9297ee529e80a7/functions.php#L21-L25

yes, it has changed.

I will open an issue tomorrow, since the 6th argument passed to it wouldn't exist.

---

About composer... it clearly installs a release, otherwise I wouldn't have (had) 5.x locally
However, I am not going to spend the time to prove that the bug exists in the stable 5.x release, I dumped the stuff and redid it with the beta-1 v6, hoping it will stay "stable"
