### ISSUE TITLE
Custom scss won't change anymore

### ISSUE THREAD

**Issue by lennertfabriek** [bootscore/bootscore#85]
Hi Basti! On this website: caddsign.nl the custom scss isn't working correctly anymore (for a week now). New changes are not loading (cache is deleted). Changes in other css files works right. Also the old css inside the custom scss is still working correctly. Only new changes won't work. 

I can't find the fix..

also when home page is loading you see the slider images big. Do you know a quick fix for this? Some loading fix.

**Comment by lennertfabriek** [comment]
When I am downloading the file from the directory the changes are in there!

**Comment by crftwrk** [comment]
Hi Lennert,

if compiler stops working, add `define('WP_ENVIRONMENT_TYPE', 'development');` to `wp-config.php`. Check here https://github.com/bootscore/bootscore/issues/40 about this new feature. Now it recompiles on every page load. Delete it when finished. I had the same problem on a site. It seems that this sometimes happen.

> also when home page is loading you see the slider images big. Do you know a quick fix for this? Some loading fix.

To hide ugly page loading issues, use the great preloader https://github.com/bootscore/bs-preloader.

Does this help?

**Comment by lennertfabriek** [comment]
Thanks! first thing is solved.

The preloader looks really cool but it is taking too long.. Maybe if I do some more work about the page speed but I was happy with the speed load.

**Comment by crftwrk** [comment]
> The preloader looks really cool but it is taking too long

This is because you enabled dev_mode `define('WP_ENVIRONMENT_TYPE', 'development');` to recompile on every page load. Remove it and preloader is fast as your page load.

**Comment by lennertfabriek** [comment]
Oh duhh.. Is it possible to do the preloader only at the homepage?

**Comment by crftwrk** [comment]
No, preloader is on every page to create smooth page transitions.

**Comment by lennertfabriek** [comment]
Aah okay. Thanks for your quick replies.

**Comment by crftwrk** [comment]
You're welcome. Solved?

**Comment by lennertfabriek** [comment]
Yes you can make this solved

**Comment by crftwrk** [comment]
👍
