### ISSUE TITLE
Mini cart display error on single page, single post, archives, etc.

### ISSUE THREAD

**Issue by marclgo84** [bootscore/bootscore#86]
First, I would like to say thanks for this awesome theme - great work!

However, my mini cart has an error and I can't figure out why. On each WooCommerce page and WooCommerce category, everything is fine. On single pages, posts, archives, etc. (basically, everything that is NOT WooCommerce) the mini cart layout is broken. See here for example: https://kuestenvibes.de/datenschutz/ (add something to the cart first: https://kuestenvibes.de/shop/)

Apparently, it's not a plugin issue as I already tried to deactivate all plugins. At this point, I don't know where the error could come from so I do appreciate every help.

**Comment by crftwrk** [comment]
Thank you!

A CSS markup is missing:

```css
img {
  max-width: 100%;
  height: auto;
}
```

Add this to `_bscore_custom.scss` and mini-cart image looks well everywhere.

I see that you enabled WooCommerce in main-theme and change code there. This is not a good idea, much better to use bootscommerce-child and do changes there. This will prevent bugs like this as well.

Does this help?

**Comment by marclgo84** [comment]
Can't believe it was that simple. Well, sometimes we miss the easiest solutions :)

Thank you for your help. I'm going to change to child theme soon...

**Comment by crftwrk** [comment]
👍 You're welcome.
