### ISSUE TITLE
Incorrect Filter Name in Documentation for Disabling Environment Check

### ISSUE THREAD

**Issue by kemalkastrataj** [bootscore/bootscore#871]
### Description
The documentation for Bootscore’s CSS/SCSS compiler contains an incorrect filter name under the section.

### Problem
The documentation suggests the following code to disable the environment check in functions.php:

`// Disable environment check
add_filter('bootscore_scss_skip_environment_check', '__return_true');
`

**However, the Bootscore source code uses a different filter name:**

`$this->skip_environment_check = apply_filters('bootscore/scss/skip_environment_check', (defined('BOOTSCORE_SCSS_SKIP_ENVIRONMENT_CHECK') && BOOTSCORE_SCSS_SKIP_ENVIRONMENT_CHECK));
`

### Discovery
While integrating the SCSS compiler feature, I noticed that the environment check was not being disabled as expected. After inspecting the Bootscore source code, I found that the filter name used in apply_filters() is 'bootscore/scss/skip_environment_check', which does not match the filter name provided in the documentation.

### Suggested Fix
Update the documentation to use the correct filter name:

`// Correct way to disable environment check
add_filter('bootscore/scss/skip_environment_check', '__return_true');
`

### References

- Documentation URL: https://bootscore.me/documentation/theme/css-scss-compiler/#disable-environment-check
- Source Code Reference: Code snippet from the Bootscore theme where the filter is applied.

**Comment by crftwrk** [comment]
You're absolutely right, thank you for pointing this out. It was overlooked in v6 docs but has been fixed now https://bootscore.me/documentation/theme/css-scss-compiler/#disable-environment-check. Filter to disable scssphp has been changed as well.
