### ISSUE TITLE
This theme keeps crashing wordpress-what happened?

### ISSUE THREAD

**Issue by rvakid82** [bootscore/bootscore#912]
### Discussed in https://github.com/orgs/bootscore/discussions/911

<div type='discussions-op-text'>

<sup>Originally posted by **rvakid82** December 28, 2024</sup>
I've used bootscore for years and years without any issue. I upgraded to v6 and i get an error message "There has been a critical error on this website." with no instructions. What happened? I used ot use this framework to build so many sites and now none of them work. What's wrong? Please help.</div>

**Comment by crftwrk** [comment]
Closed, because already discussed here https://github.com/orgs/bootscore/discussions/911 and this is not an issue. v6 requires migration.
