### ISSUE TITLE
laravel mix 

### ISSUE THREAD

**Issue by vahidalvandi** [bootscore/bootscore#94]
I think laravel mix should be used to manage sass
i am laravel developer and have same idea for incrase sass compile and incrase sass build and watch time during development wp templete .

**Comment by justinkruit** [comment]
The idea behind behind bootScore is that it's easy to add to an existing Wordpress installation, on any PHP environment. If we would use anything like Laravel, the setup would be incredibly more difficult, and not what bootScore is intended to be.

**Comment by vahidalvandi** [comment]
We don't need install laravel .

Laravel ream created a Web pack module as name laravel mix

https://laravel-mix.com/

This just need npm

**Comment by vahidalvandi** [comment]
Dear npm is very modern from your sass compilers. Worldwide frontend
developers work with npm also is very fast and after development ended with
command
Npm run production create final style.css

**Comment by justinkruit** [comment]
I'm very familiar with NPM, I'm a developer myself. Still, it's simply not how bootScore is intended. No additional tools are needed to make bootScore work as a theme, while with NPM the user is required to know how a terminal works, and have access to one on their simple webhosting (almost none do).

**Comment by justinkruit** [comment]
> Agree. Name bootstrap.min.css and folder structure...

Then my vote definitely goes for the first branch.

> Tried already, but failed. Think a source map is very useful for debugging.

Alright, I'll probably give it a shot this weekend! I'll create a new issue for it
